// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activities.sql

package sqlcgen

import (
	"context"
	"time"
)

const countActivitiesByAttendance = `-- name: CountActivitiesByAttendance :one
SELECT count(*) AS n
FROM attendance_activities
WHERE attendance_id = $1
  AND deleted_at IS NULL
`

// Count of live activities on a record — the clock-out gate (AA-7). Read inside the
// clock-out transaction so a racing add/delete resolves on the persisted count (C-12).
func (q *Queries) CountActivitiesByAttendance(ctx context.Context, attendanceID string) (int64, error) {
	row := q.db.QueryRow(ctx, countActivitiesByAttendance, attendanceID)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const createActivity = `-- name: CreateActivity :one

INSERT INTO attendance_activities (attendance_id, employee_id, note)
VALUES ($1, $2, $3)
RETURNING id, attendance_id, employee_id, note, recorded_at, created_at
`

type CreateActivityParams struct {
	AttendanceID string
	EmployeeID   string
	Note         string
}

type CreateActivityRow struct {
	ID           string
	AttendanceID string
	EmployeeID   string
	Note         string
	RecordedAt   time.Time
	CreatedAt    time.Time
}

// E5 attendance activity log queries (F5.8 / SWP-ACT-*). An agent logs free-text activity
// notes onto their own OPEN attendance record; agent clock-out is gated on >=1 non-deleted
// activity (INV-7 / AA-7). recorded_at is server-set (DB default now()). `make gen` writes
// internal/repository/sqlc (NEVER hand-edit).
// Insert one activity. id + recorded_at + created_at default server-side. Open-record and
// scope:self checks are enforced in the service before calling this.
func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (CreateActivityRow, error) {
	row := q.db.QueryRow(ctx, createActivity, arg.AttendanceID, arg.EmployeeID, arg.Note)
	var i CreateActivityRow
	err := row.Scan(
		&i.ID,
		&i.AttendanceID,
		&i.EmployeeID,
		&i.Note,
		&i.RecordedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActivity = `-- name: GetActivity :one
SELECT id, attendance_id, employee_id, note, recorded_at, created_at
FROM attendance_activities
WHERE id = $1
  AND deleted_at IS NULL
`

type GetActivityRow struct {
	ID           string
	AttendanceID string
	EmployeeID   string
	Note         string
	RecordedAt   time.Time
	CreatedAt    time.Time
}

// One live activity by id — used for the delete ownership/while-open check.
func (q *Queries) GetActivity(ctx context.Context, id string) (GetActivityRow, error) {
	row := q.db.QueryRow(ctx, getActivity, id)
	var i GetActivityRow
	err := row.Scan(
		&i.ID,
		&i.AttendanceID,
		&i.EmployeeID,
		&i.Note,
		&i.RecordedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActivitiesByAttendance = `-- name: ListActivitiesByAttendance :many
SELECT id, attendance_id, employee_id, note, recorded_at, created_at
FROM attendance_activities
WHERE attendance_id = $1
  AND deleted_at IS NULL
  AND (
        $2::timestamptz IS NULL
        OR recorded_at > $2::timestamptz
        OR (recorded_at = $2::timestamptz AND id > $3::text)
      )
ORDER BY recorded_at ASC, id ASC
LIMIT $4
`

type ListActivitiesByAttendanceParams struct {
	AttendanceID     string
	CursorRecordedAt *time.Time
	CursorID         *string
	PageLimit        int32
}

type ListActivitiesByAttendanceRow struct {
	ID           string
	AttendanceID string
	EmployeeID   string
	Note         string
	RecordedAt   time.Time
	CreatedAt    time.Time
}

// Chronological (recorded_at asc, id asc) live activities for one attendance record.
// Keyset cursor: pass cursor_recorded_at + cursor_id from the previous page tail.
func (q *Queries) ListActivitiesByAttendance(ctx context.Context, arg ListActivitiesByAttendanceParams) ([]ListActivitiesByAttendanceRow, error) {
	rows, err := q.db.Query(ctx, listActivitiesByAttendance,
		arg.AttendanceID,
		arg.CursorRecordedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivitiesByAttendanceRow{}
	for rows.Next() {
		var i ListActivitiesByAttendanceRow
		if err := rows.Scan(
			&i.ID,
			&i.AttendanceID,
			&i.EmployeeID,
			&i.Note,
			&i.RecordedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteActivity = `-- name: SoftDeleteActivity :execrows
UPDATE attendance_activities
SET deleted_at = now()
WHERE id = $1
  AND attendance_id = $2
  AND employee_id = $3
  AND deleted_at IS NULL
`

type SoftDeleteActivityParams struct {
	ID           string
	AttendanceID string
	EmployeeID   string
}

// Soft-delete the creator's own live activity. Returns rows affected (0 → not found /
// not owner / already deleted → handler maps to 404). Scope:self enforced via employee_id.
func (q *Queries) SoftDeleteActivity(ctx context.Context, arg SoftDeleteActivityParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteActivity, arg.ID, arg.AttendanceID, arg.EmployeeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
