// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agreement_attachments.sql

package sqlcgen

import (
	"context"
	"time"
)

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO agreement_attachments (
    id, agreement_id, category, caption, file_name, mime, size_bytes, blob, uploaded_by
) VALUES (
    'SWP-FILE-' || swp_next_id('FILE'),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, agreement_id, category, caption, file_name, mime, size_bytes, created_at
`

type CreateAttachmentParams struct {
	AgreementID string
	Category    string
	Caption     string
	FileName    string
	Mime        string
	SizeBytes   int64
	Blob        []byte
	UploadedBy  *string
}

type CreateAttachmentRow struct {
	ID          string
	AgreementID string
	Category    string
	Caption     string
	FileName    string
	Mime        string
	SizeBytes   int64
	CreatedAt   time.Time
}

// Allocates the SWP-FILE id inline from the per-prefix sequence.
// Returns metadata only (not the blob) — callers use GetAttachmentByID for download.
func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (CreateAttachmentRow, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.AgreementID,
		arg.Category,
		arg.Caption,
		arg.FileName,
		arg.Mime,
		arg.SizeBytes,
		arg.Blob,
		arg.UploadedBy,
	)
	var i CreateAttachmentRow
	err := row.Scan(
		&i.ID,
		&i.AgreementID,
		&i.Category,
		&i.Caption,
		&i.FileName,
		&i.Mime,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const getAttachmentByID = `-- name: GetAttachmentByID :one
SELECT id, file_name, mime, size_bytes, blob
FROM agreement_attachments
WHERE id = $1
`

type GetAttachmentByIDRow struct {
	ID        string
	FileName  string
	Mime      string
	SizeBytes int64
	Blob      []byte
}

// Returns file metadata + blob for the authenticated file-download handler.
func (q *Queries) GetAttachmentByID(ctx context.Context, id string) (GetAttachmentByIDRow, error) {
	row := q.db.QueryRow(ctx, getAttachmentByID, id)
	var i GetAttachmentByIDRow
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.Mime,
		&i.SizeBytes,
		&i.Blob,
	)
	return i, err
}
