// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agreements.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAgreement = `-- name: CreateAgreement :one
INSERT INTO employment_agreements (
    id, employee_id, type, agreement_no, start_date, end_date,
    predecessor_id, base_salary_idr, annual_leave_entitlement_days, bpjs_terms, tax_profile, comp_effective_date, created_by
) VALUES (
    'SWP-AG-' || swp_next_id('AG'),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
RETURNING id, employee_id, type, agreement_no, start_date, end_date, status,
          predecessor_id, successor_id, closed_reason, closed_at,
          base_salary_idr, annual_leave_entitlement_days, bpjs_terms, tax_profile, comp_effective_date,
          created_by, created_at, updated_at
`

type CreateAgreementParams struct {
	EmployeeID                 string
	Type                       string
	AgreementNo                string
	StartDate                  pgtype.Date
	EndDate                    pgtype.Date
	PredecessorID              *string
	BaseSalaryIdr              pgtype.Numeric
	AnnualLeaveEntitlementDays *int32
	BpjsTerms                  []byte
	TaxProfile                 *string
	CompEffectiveDate          pgtype.Date
	CreatedBy                  *string
}

type CreateAgreementRow struct {
	ID                         string
	EmployeeID                 string
	Type                       string
	AgreementNo                string
	StartDate                  pgtype.Date
	EndDate                    pgtype.Date
	Status                     string
	PredecessorID              *string
	SuccessorID                *string
	ClosedReason               *string
	ClosedAt                   *time.Time
	BaseSalaryIdr              pgtype.Numeric
	AnnualLeaveEntitlementDays *int32
	BpjsTerms                  []byte
	TaxProfile                 *string
	CompEffectiveDate          pgtype.Date
	CreatedBy                  *string
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
}

// Allocates the SWP-AG id inline from the per-prefix sequence.
func (q *Queries) CreateAgreement(ctx context.Context, arg CreateAgreementParams) (CreateAgreementRow, error) {
	row := q.db.QueryRow(ctx, createAgreement,
		arg.EmployeeID,
		arg.Type,
		arg.AgreementNo,
		arg.StartDate,
		arg.EndDate,
		arg.PredecessorID,
		arg.BaseSalaryIdr,
		arg.AnnualLeaveEntitlementDays,
		arg.BpjsTerms,
		arg.TaxProfile,
		arg.CompEffectiveDate,
		arg.CreatedBy,
	)
	var i CreateAgreementRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Type,
		&i.AgreementNo,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.PredecessorID,
		&i.SuccessorID,
		&i.ClosedReason,
		&i.ClosedAt,
		&i.BaseSalaryIdr,
		&i.AnnualLeaveEntitlementDays,
		&i.BpjsTerms,
		&i.TaxProfile,
		&i.CompEffectiveDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveAgreementForEmployee = `-- name: GetActiveAgreementForEmployee :one
SELECT id, employee_id, type, agreement_no, start_date, end_date, status,
       predecessor_id, successor_id, closed_reason, closed_at,
       base_salary_idr, annual_leave_entitlement_days, bpjs_terms, tax_profile, comp_effective_date,
       created_by, created_at, updated_at
FROM employment_agreements
WHERE employee_id = $1
  AND status = 'active'
  AND deleted_at IS NULL
`

type GetActiveAgreementForEmployeeRow struct {
	ID                         string
	EmployeeID                 string
	Type                       string
	AgreementNo                string
	StartDate                  pgtype.Date
	EndDate                    pgtype.Date
	Status                     string
	PredecessorID              *string
	SuccessorID                *string
	ClosedReason               *string
	ClosedAt                   *time.Time
	BaseSalaryIdr              pgtype.Numeric
	AnnualLeaveEntitlementDays *int32
	BpjsTerms                  []byte
	TaxProfile                 *string
	CompEffectiveDate          pgtype.Date
	CreatedBy                  *string
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
}

// EA-2 pre-check + predecessor lookup for :renew/:close operations.
func (q *Queries) GetActiveAgreementForEmployee(ctx context.Context, employeeID string) (GetActiveAgreementForEmployeeRow, error) {
	row := q.db.QueryRow(ctx, getActiveAgreementForEmployee, employeeID)
	var i GetActiveAgreementForEmployeeRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Type,
		&i.AgreementNo,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.PredecessorID,
		&i.SuccessorID,
		&i.ClosedReason,
		&i.ClosedAt,
		&i.BaseSalaryIdr,
		&i.AnnualLeaveEntitlementDays,
		&i.BpjsTerms,
		&i.TaxProfile,
		&i.CompEffectiveDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgreementByID = `-- name: GetAgreementByID :one
SELECT id, employee_id, type, agreement_no, start_date, end_date, status,
       predecessor_id, successor_id, closed_reason, closed_at,
       base_salary_idr, annual_leave_entitlement_days, bpjs_terms, tax_profile, comp_effective_date,
       created_by, created_at, updated_at
FROM employment_agreements
WHERE id = $1
  AND deleted_at IS NULL
`

type GetAgreementByIDRow struct {
	ID                         string
	EmployeeID                 string
	Type                       string
	AgreementNo                string
	StartDate                  pgtype.Date
	EndDate                    pgtype.Date
	Status                     string
	PredecessorID              *string
	SuccessorID                *string
	ClosedReason               *string
	ClosedAt                   *time.Time
	BaseSalaryIdr              pgtype.Numeric
	AnnualLeaveEntitlementDays *int32
	BpjsTerms                  []byte
	TaxProfile                 *string
	CompEffectiveDate          pgtype.Date
	CreatedBy                  *string
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
}

func (q *Queries) GetAgreementByID(ctx context.Context, id string) (GetAgreementByIDRow, error) {
	row := q.db.QueryRow(ctx, getAgreementByID, id)
	var i GetAgreementByIDRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Type,
		&i.AgreementNo,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.PredecessorID,
		&i.SuccessorID,
		&i.ClosedReason,
		&i.ClosedAt,
		&i.BaseSalaryIdr,
		&i.AnnualLeaveEntitlementDays,
		&i.BpjsTerms,
		&i.TaxProfile,
		&i.CompEffectiveDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgreements = `-- name: ListAgreements :many
SELECT id, employee_id, type, agreement_no, start_date, end_date, status,
       predecessor_id, successor_id, closed_reason, closed_at,
       base_salary_idr, annual_leave_entitlement_days, bpjs_terms, tax_profile, comp_effective_date,
       created_by, created_at, updated_at
FROM employment_agreements
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR employee_id = $1::text)
  AND ($2::text IS NULL OR status = $2::text)
  AND ($3::text IS NULL OR type = $3::text)
  AND ($4::date IS NULL OR end_date <= $4::date)
  AND (
        $5::timestamptz IS NULL
        OR (created_at, id) < ($5::timestamptz, $6::text)
      )
ORDER BY created_at DESC, id DESC
LIMIT $7
`

type ListAgreementsParams struct {
	EmployeeID      *string
	Status          *string
	Type            *string
	EndDateLte      pgtype.Date
	CursorCreatedAt *time.Time
	CursorID        *string
	RowLimit        int32
}

type ListAgreementsRow struct {
	ID                         string
	EmployeeID                 string
	Type                       string
	AgreementNo                string
	StartDate                  pgtype.Date
	EndDate                    pgtype.Date
	Status                     string
	PredecessorID              *string
	SuccessorID                *string
	ClosedReason               *string
	ClosedAt                   *time.Time
	BaseSalaryIdr              pgtype.Numeric
	AnnualLeaveEntitlementDays *int32
	BpjsTerms                  []byte
	TaxProfile                 *string
	CompEffectiveDate          pgtype.Date
	CreatedBy                  *string
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
}

// Cursor page ordered by (created_at desc, id desc). Fetch limit+1 for has_more.
// Filters: employee_id, status, type, end_date__lte (agreements expiring on or before).
func (q *Queries) ListAgreements(ctx context.Context, arg ListAgreementsParams) ([]ListAgreementsRow, error) {
	rows, err := q.db.Query(ctx, listAgreements,
		arg.EmployeeID,
		arg.Status,
		arg.Type,
		arg.EndDateLte,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgreementsRow{}
	for rows.Next() {
		var i ListAgreementsRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.Type,
			&i.AgreementNo,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.PredecessorID,
			&i.SuccessorID,
			&i.ClosedReason,
			&i.ClosedAt,
			&i.BaseSalaryIdr,
			&i.AnnualLeaveEntitlementDays,
			&i.BpjsTerms,
			&i.TaxProfile,
			&i.CompEffectiveDate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAgreementStatus = `-- name: SetAgreementStatus :one
UPDATE employment_agreements
SET status        = $1,
    closed_reason = $2,
    closed_at     = $3,
    successor_id  = $4,
    updated_at    = now()
WHERE id = $5
RETURNING id, employee_id, type, agreement_no, start_date, end_date, status,
          predecessor_id, successor_id, closed_reason, closed_at,
          base_salary_idr, annual_leave_entitlement_days, bpjs_terms, tax_profile, comp_effective_date,
          created_by, created_at, updated_at
`

type SetAgreementStatusParams struct {
	Status       string
	ClosedReason *string
	ClosedAt     *time.Time
	SuccessorID  *string
	ID           string
}

type SetAgreementStatusRow struct {
	ID                         string
	EmployeeID                 string
	Type                       string
	AgreementNo                string
	StartDate                  pgtype.Date
	EndDate                    pgtype.Date
	Status                     string
	PredecessorID              *string
	SuccessorID                *string
	ClosedReason               *string
	ClosedAt                   *time.Time
	BaseSalaryIdr              pgtype.Numeric
	AnnualLeaveEntitlementDays *int32
	BpjsTerms                  []byte
	TaxProfile                 *string
	CompEffectiveDate          pgtype.Date
	CreatedBy                  *string
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
}

// Drives :close (status='closed') and supersede-on-renew (status='superseded').
// Also sets closed_reason, closed_at, successor_id as applicable.
func (q *Queries) SetAgreementStatus(ctx context.Context, arg SetAgreementStatusParams) (SetAgreementStatusRow, error) {
	row := q.db.QueryRow(ctx, setAgreementStatus,
		arg.Status,
		arg.ClosedReason,
		arg.ClosedAt,
		arg.SuccessorID,
		arg.ID,
	)
	var i SetAgreementStatusRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Type,
		&i.AgreementNo,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.PredecessorID,
		&i.SuccessorID,
		&i.ClosedReason,
		&i.ClosedAt,
		&i.BaseSalaryIdr,
		&i.AnnualLeaveEntitlementDays,
		&i.BpjsTerms,
		&i.TaxProfile,
		&i.CompEffectiveDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
