// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: approved_leave_days.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteApprovedLeaveDaysForRequest = `-- name: DeleteApprovedLeaveDaysForRequest :execrows
DELETE FROM approved_leave_days
WHERE leave_request_id = $1
`

// INV-3 reverse (cancel/shorten restore — used by later cancel paths; added now).
func (q *Queries) DeleteApprovedLeaveDaysForRequest(ctx context.Context, leaveRequestID *string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteApprovedLeaveDaysForRequest, leaveRequestID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findApprovedLeaveForAgentDate = `-- name: FindApprovedLeaveForAgentDate :one

SELECT ald.leave_request_id, ald.leave_type, ald.leave_date
FROM approved_leave_days ald
WHERE ald.employee_id = $1
  AND ald.leave_date = $2
LIMIT 1
`

type FindApprovedLeaveForAgentDateParams struct {
	EmployeeID string
	LeaveDate  pgtype.Date
}

type FindApprovedLeaveForAgentDateRow struct {
	LeaveRequestID *string
	LeaveType      *string
	LeaveDate      pgtype.Date
}

// E4-owned approved-leave read source (Phase 6). Drives the SHIFT_OVER_LEAVE /
// CANCELLED_BY_LEAVE conflict branch until E6 (Phase 8) wires the production
// leave_requests source. See migration 00025 for the ownership / hand-off note.
// SHIFT_OVER_LEAVE source: the approved-leave row (if any) for an agent on a date.
func (q *Queries) FindApprovedLeaveForAgentDate(ctx context.Context, arg FindApprovedLeaveForAgentDateParams) (FindApprovedLeaveForAgentDateRow, error) {
	row := q.db.QueryRow(ctx, findApprovedLeaveForAgentDate, arg.EmployeeID, arg.LeaveDate)
	var i FindApprovedLeaveForAgentDateRow
	err := row.Scan(&i.LeaveRequestID, &i.LeaveType, &i.LeaveDate)
	return i, err
}

const insertApprovedLeaveDay = `-- name: InsertApprovedLeaveDay :exec
INSERT INTO approved_leave_days (employee_id, leave_date, leave_request_id, leave_type)
VALUES ($1, $2, $3, $4)
ON CONFLICT (employee_id, leave_date) DO UPDATE
  SET leave_request_id = EXCLUDED.leave_request_id, leave_type = EXCLUDED.leave_type
`

type InsertApprovedLeaveDayParams struct {
	EmployeeID     string
	LeaveDate      pgtype.Date
	LeaveRequestID *string
	LeaveType      *string
}

// INV-3 write-through (E6 / Phase 8): on final/override leave approval the REAL
// leave_requests.id replaces the Phase-6 fixture. ON CONFLICT upsert is required
// because (employee_id, leave_date) is unique (a re-approve / overlapping day must
// not 23505).
func (q *Queries) InsertApprovedLeaveDay(ctx context.Context, arg InsertApprovedLeaveDayParams) error {
	_, err := q.db.Exec(ctx, insertApprovedLeaveDay,
		arg.EmployeeID,
		arg.LeaveDate,
		arg.LeaveRequestID,
		arg.LeaveType,
	)
	return err
}
