// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package sqlcgen

import (
	"context"
	"time"
)

const getAuditLogByID = `-- name: GetAuditLogByID :one
SELECT id, actor_user_id, actor_role, action, entity_type, entity_id,
       before_state, after_state, request_id, created_at
FROM audit_log
WHERE id = $1
`

func (q *Queries) GetAuditLogByID(ctx context.Context, id string) (AuditLog, error) {
	row := q.db.QueryRow(ctx, getAuditLogByID, id)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.ActorRole,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.BeforeState,
		&i.AfterState,
		&i.RequestID,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT id, actor_user_id, actor_role, action, entity_type, entity_id,
       before_state, after_state, request_id, created_at
FROM audit_log
WHERE ($1::text IS NULL OR actor_user_id = $1)
  AND ($2::text        IS NULL OR action = $2)
  AND ($3::text   IS NULL OR entity_type = $3)
  AND ($4::text     IS NULL OR entity_id = $4)
  AND ($5::timestamptz IS NULL OR created_at >= $5)
  AND ($6::timestamptz IS NULL OR created_at <= $6)
  AND ($7::text IS NULL OR action ILIKE '%' || $7 || '%' OR entity_id ILIKE '%' || $7 || '%')
  AND (
        $8::timestamptz IS NULL
        OR (created_at, id) < ($8::timestamptz, $9::text)
      )
ORDER BY created_at DESC, id DESC
LIMIT $10
`

type ListAuditLogParams struct {
	ActorUserID     *string
	Action          *string
	EntityType      *string
	EntityID        *string
	CreatedGte      *time.Time
	CreatedLte      *time.Time
	Q               *string
	CursorCreatedAt *time.Time
	CursorID        *string
	RowLimit        int32
}

// Cursor page ordered by (created_at desc, id desc), fetch limit+1. All filters optional.
func (q *Queries) ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLog,
		arg.ActorUserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.CreatedGte,
		arg.CreatedLte,
		arg.Q,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.ActorRole,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.BeforeState,
			&i.AfterState,
			&i.RequestID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
