// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: change_requests.sql

package sqlcgen

import (
	"context"
	"time"
)

const createChangeRequest = `-- name: CreateChangeRequest :one
INSERT INTO change_requests (
    id, employee_id, changes, request_type, note
) VALUES (
    'SWP-CHG-' || swp_next_id('CHG'),
    $1,
    $2,
    $3,
    $4
)
RETURNING id, employee_id, status, changes, request_type, note,
          submitted_at, resolved_at, resolved_by, rejection_reason
`

type CreateChangeRequestParams struct {
	EmployeeID  string
	Changes     []byte
	RequestType string
	Note        *string
}

// Allocates the SWP-CHG id inline from the per-prefix sequence.
func (q *Queries) CreateChangeRequest(ctx context.Context, arg CreateChangeRequestParams) (ChangeRequest, error) {
	row := q.db.QueryRow(ctx, createChangeRequest,
		arg.EmployeeID,
		arg.Changes,
		arg.RequestType,
		arg.Note,
	)
	var i ChangeRequest
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Status,
		&i.Changes,
		&i.RequestType,
		&i.Note,
		&i.SubmittedAt,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.RejectionReason,
	)
	return i, err
}

const getChangeRequestByID = `-- name: GetChangeRequestByID :one
SELECT id, employee_id, status, changes, request_type, note,
       submitted_at, resolved_at, resolved_by, rejection_reason
FROM change_requests
WHERE id = $1
`

func (q *Queries) GetChangeRequestByID(ctx context.Context, id string) (ChangeRequest, error) {
	row := q.db.QueryRow(ctx, getChangeRequestByID, id)
	var i ChangeRequest
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Status,
		&i.Changes,
		&i.RequestType,
		&i.Note,
		&i.SubmittedAt,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.RejectionReason,
	)
	return i, err
}

const listChangeRequests = `-- name: ListChangeRequests :many
SELECT id, employee_id, status, changes, request_type, note,
       submitted_at, resolved_at, resolved_by, rejection_reason
FROM change_requests
WHERE ($1::text IS NULL OR status = $1::text)
  AND ($2::text IS NULL OR employee_id = $2::text)
  AND ($3::text IS NULL OR request_type = $3::text)
  AND (
        $4::timestamptz IS NULL
        OR (submitted_at, id) < ($4::timestamptz, $5::text)
      )
ORDER BY submitted_at DESC, id DESC
LIMIT $6
`

type ListChangeRequestsParams struct {
	Status            *string
	EmployeeID        *string
	RequestType       *string
	CursorSubmittedAt *time.Time
	CursorID          *string
	RowLimit          int32
}

// Cursor page ordered by (submitted_at desc, id desc). Fetch limit+1 for has_more.
// Filters: status, employee_id, request_type.
func (q *Queries) ListChangeRequests(ctx context.Context, arg ListChangeRequestsParams) ([]ChangeRequest, error) {
	rows, err := q.db.Query(ctx, listChangeRequests,
		arg.Status,
		arg.EmployeeID,
		arg.RequestType,
		arg.CursorSubmittedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChangeRequest{}
	for rows.Next() {
		var i ChangeRequest
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.Status,
			&i.Changes,
			&i.RequestType,
			&i.Note,
			&i.SubmittedAt,
			&i.ResolvedAt,
			&i.ResolvedBy,
			&i.RejectionReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveChangeRequest = `-- name: ResolveChangeRequest :one
UPDATE change_requests
SET status           = $1,
    resolved_at      = $2,
    resolved_by      = $3,
    rejection_reason = $4
WHERE id = $5
RETURNING id, employee_id, status, changes, request_type, note,
          submitted_at, resolved_at, resolved_by, rejection_reason
`

type ResolveChangeRequestParams struct {
	Status          string
	ResolvedAt      *time.Time
	ResolvedBy      *string
	RejectionReason *string
	ID              string
}

// Drives :approve (status='approved') and :reject (status='rejected').
// Sets resolved_at, resolved_by (optional), and rejection_reason (on reject).
func (q *Queries) ResolveChangeRequest(ctx context.Context, arg ResolveChangeRequestParams) (ChangeRequest, error) {
	row := q.db.QueryRow(ctx, resolveChangeRequest,
		arg.Status,
		arg.ResolvedAt,
		arg.ResolvedBy,
		arg.RejectionReason,
		arg.ID,
	)
	var i ChangeRequest
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Status,
		&i.Changes,
		&i.RequestType,
		&i.Note,
		&i.SubmittedAt,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.RejectionReason,
	)
	return i, err
}
