// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: client_sites.sql

package sqlcgen

import (
	"context"
	"time"
)

const createSite = `-- name: CreateSite :one
INSERT INTO client_sites (id, client_company_id, name, code, address, geo_lat, geo_lng,
                          geofence_radius_m, is_primary, pic_name, phone)
VALUES (
    'SWP-SITE-' || swp_next_id('SITE'),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, client_company_id, name, code, address, geo_lat, geo_lng,
          geofence_radius_m, is_primary, pic_name, phone, status, created_at, updated_at
`

type CreateSiteParams struct {
	ClientCompanyID string
	Name            string
	Code            *string
	Address         string
	GeoLat          *float64
	GeoLng          *float64
	GeofenceRadiusM int32
	IsPrimary       bool
	PicName         *string
	Phone           *string
}

type CreateSiteRow struct {
	ID              string
	ClientCompanyID string
	Name            string
	Code            *string
	Address         string
	GeoLat          *float64
	GeoLng          *float64
	GeofenceRadiusM int32
	IsPrimary       bool
	PicName         *string
	Phone           *string
	Status          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

// Allocates the SWP-SITE id inline from the per-prefix sequence.
func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) (CreateSiteRow, error) {
	row := q.db.QueryRow(ctx, createSite,
		arg.ClientCompanyID,
		arg.Name,
		arg.Code,
		arg.Address,
		arg.GeoLat,
		arg.GeoLng,
		arg.GeofenceRadiusM,
		arg.IsPrimary,
		arg.PicName,
		arg.Phone,
	)
	var i CreateSiteRow
	err := row.Scan(
		&i.ID,
		&i.ClientCompanyID,
		&i.Name,
		&i.Code,
		&i.Address,
		&i.GeoLat,
		&i.GeoLng,
		&i.GeofenceRadiusM,
		&i.IsPrimary,
		&i.PicName,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const demoteOtherPrimaries = `-- name: DemoteOtherPrimaries :exec
UPDATE client_sites
SET is_primary = false,
    updated_at = now()
WHERE client_company_id = $1
  AND id <> $2
  AND deleted_at IS NULL
`

type DemoteOtherPrimariesParams struct {
	ClientCompanyID string
	ID              string
}

// Clears is_primary on all other sites of the company when a new primary is set.
// Call inside the same tx before SetSitePrimary (INV-5).
func (q *Queries) DemoteOtherPrimaries(ctx context.Context, arg DemoteOtherPrimariesParams) error {
	_, err := q.db.Exec(ctx, demoteOtherPrimaries, arg.ClientCompanyID, arg.ID)
	return err
}

const getSiteByID = `-- name: GetSiteByID :one
SELECT id, client_company_id, name, code, address, geo_lat, geo_lng,
       geofence_radius_m, is_primary, pic_name, phone, status, created_at, updated_at
FROM client_sites
WHERE id = $1
  AND deleted_at IS NULL
`

type GetSiteByIDRow struct {
	ID              string
	ClientCompanyID string
	Name            string
	Code            *string
	Address         string
	GeoLat          *float64
	GeoLng          *float64
	GeofenceRadiusM int32
	IsPrimary       bool
	PicName         *string
	Phone           *string
	Status          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) GetSiteByID(ctx context.Context, id string) (GetSiteByIDRow, error) {
	row := q.db.QueryRow(ctx, getSiteByID, id)
	var i GetSiteByIDRow
	err := row.Scan(
		&i.ID,
		&i.ClientCompanyID,
		&i.Name,
		&i.Code,
		&i.Address,
		&i.GeoLat,
		&i.GeoLng,
		&i.GeofenceRadiusM,
		&i.IsPrimary,
		&i.PicName,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSitesForCompany = `-- name: ListSitesForCompany :many
SELECT id, client_company_id, name, code, address, geo_lat, geo_lng,
       geofence_radius_m, is_primary, pic_name, phone, status, created_at, updated_at
FROM client_sites
WHERE client_company_id = $1
  AND deleted_at IS NULL
  AND ($2::text IS NULL OR status = $2::text)
  AND (
        $3::timestamptz IS NULL
        OR (created_at, id) < ($3::timestamptz, $4::text)
      )
ORDER BY is_primary DESC, created_at DESC, id DESC
LIMIT $5
`

type ListSitesForCompanyParams struct {
	ClientCompanyID string
	Status          *string
	CursorCreatedAt *time.Time
	CursorID        *string
	RowLimit        int32
}

type ListSitesForCompanyRow struct {
	ID              string
	ClientCompanyID string
	Name            string
	Code            *string
	Address         string
	GeoLat          *float64
	GeoLng          *float64
	GeofenceRadiusM int32
	IsPrimary       bool
	PicName         *string
	Phone           *string
	Status          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

// Cursor page: primary first, then created_at desc, id desc.
// Keyset cursor on (created_at, id); is_primary DESC is the primary sort but
// keyset uses the sub-sort (created_at, id) for stable pagination.
func (q *Queries) ListSitesForCompany(ctx context.Context, arg ListSitesForCompanyParams) ([]ListSitesForCompanyRow, error) {
	rows, err := q.db.Query(ctx, listSitesForCompany,
		arg.ClientCompanyID,
		arg.Status,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSitesForCompanyRow{}
	for rows.Next() {
		var i ListSitesForCompanyRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientCompanyID,
			&i.Name,
			&i.Code,
			&i.Address,
			&i.GeoLat,
			&i.GeoLng,
			&i.GeofenceRadiusM,
			&i.IsPrimary,
			&i.PicName,
			&i.Phone,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSitePrimary = `-- name: SetSitePrimary :one
UPDATE client_sites
SET is_primary = true,
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, client_company_id, name, code, address, geo_lat, geo_lng,
          geofence_radius_m, is_primary, pic_name, phone, status, created_at, updated_at
`

type SetSitePrimaryRow struct {
	ID              string
	ClientCompanyID string
	Name            string
	Code            *string
	Address         string
	GeoLat          *float64
	GeoLng          *float64
	GeofenceRadiusM int32
	IsPrimary       bool
	PicName         *string
	Phone           *string
	Status          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) SetSitePrimary(ctx context.Context, id string) (SetSitePrimaryRow, error) {
	row := q.db.QueryRow(ctx, setSitePrimary, id)
	var i SetSitePrimaryRow
	err := row.Scan(
		&i.ID,
		&i.ClientCompanyID,
		&i.Name,
		&i.Code,
		&i.Address,
		&i.GeoLat,
		&i.GeoLng,
		&i.GeofenceRadiusM,
		&i.IsPrimary,
		&i.PicName,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setSiteStatus = `-- name: SetSiteStatus :one
UPDATE client_sites
SET status     = $1,
    updated_at = now()
WHERE id = $2
  AND deleted_at IS NULL
RETURNING id, client_company_id, name, code, address, geo_lat, geo_lng,
          geofence_radius_m, is_primary, pic_name, phone, status, created_at, updated_at
`

type SetSiteStatusParams struct {
	Status string
	ID     string
}

type SetSiteStatusRow struct {
	ID              string
	ClientCompanyID string
	Name            string
	Code            *string
	Address         string
	GeoLat          *float64
	GeoLng          *float64
	GeofenceRadiusM int32
	IsPrimary       bool
	PicName         *string
	Phone           *string
	Status          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

// Drives :deactivate (status='inactive') and :reactivate (status='active').
func (q *Queries) SetSiteStatus(ctx context.Context, arg SetSiteStatusParams) (SetSiteStatusRow, error) {
	row := q.db.QueryRow(ctx, setSiteStatus, arg.Status, arg.ID)
	var i SetSiteStatusRow
	err := row.Scan(
		&i.ID,
		&i.ClientCompanyID,
		&i.Name,
		&i.Code,
		&i.Address,
		&i.GeoLat,
		&i.GeoLng,
		&i.GeofenceRadiusM,
		&i.IsPrimary,
		&i.PicName,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSite = `-- name: UpdateSite :one
UPDATE client_sites
SET name              = $1,
    code              = $2,
    address           = $3,
    geo_lat           = $4,
    geo_lng           = $5,
    geofence_radius_m = $6,
    pic_name          = $7,
    phone             = $8,
    updated_at        = now()
WHERE id = $9
  AND deleted_at IS NULL
RETURNING id, client_company_id, name, code, address, geo_lat, geo_lng,
          geofence_radius_m, is_primary, pic_name, phone, status, created_at, updated_at
`

type UpdateSiteParams struct {
	Name            string
	Code            *string
	Address         string
	GeoLat          *float64
	GeoLng          *float64
	GeofenceRadiusM int32
	PicName         *string
	Phone           *string
	ID              string
}

type UpdateSiteRow struct {
	ID              string
	ClientCompanyID string
	Name            string
	Code            *string
	Address         string
	GeoLat          *float64
	GeoLng          *float64
	GeofenceRadiusM int32
	IsPrimary       bool
	PicName         *string
	Phone           *string
	Status          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) UpdateSite(ctx context.Context, arg UpdateSiteParams) (UpdateSiteRow, error) {
	row := q.db.QueryRow(ctx, updateSite,
		arg.Name,
		arg.Code,
		arg.Address,
		arg.GeoLat,
		arg.GeoLng,
		arg.GeofenceRadiusM,
		arg.PicName,
		arg.Phone,
		arg.ID,
	)
	var i UpdateSiteRow
	err := row.Scan(
		&i.ID,
		&i.ClientCompanyID,
		&i.Name,
		&i.Code,
		&i.Address,
		&i.GeoLat,
		&i.GeoLng,
		&i.GeofenceRadiusM,
		&i.IsPrimary,
		&i.PicName,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
