// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clock.sql

package sqlcgen

import (
	"context"
	"time"
)

const autoCloseAttendance = `-- name: AutoCloseAttendance :one
UPDATE attendance
SET check_out_at        = $1,
    worked_minutes      = $2,
    auto_closed         = true,
    flags               = $3,
    status              = $4,
    verification_status = $5,
    updated_at          = now()
WHERE id = $6
  AND check_out_at IS NULL
  AND deleted_at IS NULL
RETURNING id
`

type AutoCloseAttendanceParams struct {
	CheckOutAt         *time.Time
	WorkedMinutes      *int32
	Flags              []string
	Status             string
	VerificationStatus string
	ID                 string
}

// Auto-close a STALE open record at clock-in time (F5.1 flexible check-in): the agent
// clocked in, never clocked out, and the checkout window has elapsed. check_out_at is
// stamped at the computed shift_end (NOT now — they did not actually work past it),
// auto_closed=true, the AUTO_CLOSED flag added, status INCOMPLETE, verification PENDING
// (enters the leader queue as an anomaly). Synchronous complement to the absence sweep,
// for users/companies the cron skips. Guarded by check_out_at IS NULL so a concurrent
// clock-out wins the race (yields no row → repo treats as already-closed, no-op).
func (q *Queries) AutoCloseAttendance(ctx context.Context, arg AutoCloseAttendanceParams) (string, error) {
	row := q.db.QueryRow(ctx, autoCloseAttendance,
		arg.CheckOutAt,
		arg.WorkedMinutes,
		arg.Flags,
		arg.Status,
		arg.VerificationStatus,
		arg.ID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const clockInAttendance = `-- name: ClockInAttendance :one
INSERT INTO attendance (
    employee_id, placement_id, schedule_id, company_id,
    site_id, position,
    shift_start_at, shift_end_at,
    check_in_at, lat_in, lng_in, photo_in_id,
    wfo, is_late, late_minutes,
    in_geofence, in_distance_m, geofence_radius_m,
    status, verification_status, flags
)
VALUES (
    $1, $2, $3,
    $4,
    $5, $6,
    $7, $8,
    $9, $10, $11, $12,
    $13, $14, $15,
    $16, $17, $18,
    $19, $20, $21
)
ON CONFLICT (schedule_id) WHERE schedule_id IS NOT NULL AND deleted_at IS NULL
DO NOTHING
RETURNING id
`

type ClockInAttendanceParams struct {
	EmployeeID         string
	PlacementID        string
	ScheduleID         *string
	CompanyID          string
	SiteID             string
	Position           string
	ShiftStartAt       *time.Time
	ShiftEndAt         *time.Time
	CheckInAt          *time.Time
	LatIn              *float64
	LngIn              *float64
	PhotoInID          *string
	Wfo                bool
	IsLate             bool
	LateMinutes        int32
	InGeofence         *bool
	InDistanceM        *int32
	GeofenceRadiusM    int32
	Status             string
	VerificationStatus string
	Flags              []string
}

// Insert ONE clock-in row. id fires via the column DEFAULT (omitted). schedule_id is
// nullable (NULL ⇒ unscheduled). ON CONFLICT (the partial schedule_id unique index)
// DO NOTHING makes a concurrent absence-sweep / double-tap a no-op — RETURNING then
// yields NO row (pgx.ErrNoRows), which the repo maps to created=false so the service
// emits ALREADY_CLOCKED_IN. flags is text[].
func (q *Queries) ClockInAttendance(ctx context.Context, arg ClockInAttendanceParams) (string, error) {
	row := q.db.QueryRow(ctx, clockInAttendance,
		arg.EmployeeID,
		arg.PlacementID,
		arg.ScheduleID,
		arg.CompanyID,
		arg.SiteID,
		arg.Position,
		arg.ShiftStartAt,
		arg.ShiftEndAt,
		arg.CheckInAt,
		arg.LatIn,
		arg.LngIn,
		arg.PhotoInID,
		arg.Wfo,
		arg.IsLate,
		arg.LateMinutes,
		arg.InGeofence,
		arg.InDistanceM,
		arg.GeofenceRadiusM,
		arg.Status,
		arg.VerificationStatus,
		arg.Flags,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const clockOutAttendance = `-- name: ClockOutAttendance :one
UPDATE attendance
SET check_out_at        = $1,
    lat_out             = $2,
    lng_out             = $3,
    photo_out_id        = $4,
    out_geofence        = $5,
    out_distance_m      = $6,
    worked_minutes      = $7,
    flags               = $8,
    status              = $9,
    verification_status = $10,
    updated_at          = now()
WHERE id = $11
  AND deleted_at IS NULL
RETURNING id
`

type ClockOutAttendanceParams struct {
	CheckOutAt         *time.Time
	LatOut             *float64
	LngOut             *float64
	PhotoOutID         *string
	OutGeofence        *bool
	OutDistanceM       *int32
	WorkedMinutes      *int32
	Flags              []string
	Status             string
	VerificationStatus string
	ID                 string
}

// Close one open record: stamp the clock-out columns + recomputed worked_minutes /
// flags / status / verification_status. Guarded by deleted_at — yields NO row
// (pgx.ErrNoRows) if the record vanished, which the service treats as a 500/NotFound.
func (q *Queries) ClockOutAttendance(ctx context.Context, arg ClockOutAttendanceParams) (string, error) {
	row := q.db.QueryRow(ctx, clockOutAttendance,
		arg.CheckOutAt,
		arg.LatOut,
		arg.LngOut,
		arg.PhotoOutID,
		arg.OutGeofence,
		arg.OutDistanceM,
		arg.WorkedMinutes,
		arg.Flags,
		arg.Status,
		arg.VerificationStatus,
		arg.ID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getOpenAttendanceForEmployee = `-- name: GetOpenAttendanceForEmployee :one

SELECT a.id
FROM attendance a
WHERE a.employee_id = $1
  AND a.check_out_at IS NULL
  AND a.deleted_at IS NULL
ORDER BY a.check_in_at DESC
LIMIT 1
`

// E5 agent clock-in/out queries (F5.1 / SWP-ATT-*). The mobile agent flow:
// resolve the active placement + site geofence (existing generated queries), find
// today's schedule entry for lateness eval, detect an already-open record, then
// INSERT a clock-in (ON CONFLICT on the partial schedule_id unique index → no-op for
// a concurrent absence-sweep / double-tap) or UPDATE a clock-out. schedule_entries
// carries NO stored shift timestamptz — the window is computed from work_date +
// start_time/end_time (HH:MM, Asia/Jakarta wall-clock) via `AT TIME ZONE` (CLAUDE.md
// TZ layer); cross_midnight adds a day to the end. `make gen` writes
// internal/repository/sqlc (NEVER hand-edit).
// The caller's currently-open record (clocked in, not yet clocked out). Drives
// ALREADY_CLOCKED_IN (clock-in) / NOT_CLOCKED_IN (clock-out). Most-recent first so a
// stale half-open row never masks the latest.
func (q *Queries) GetOpenAttendanceForEmployee(ctx context.Context, employeeID string) (string, error) {
	row := q.db.QueryRow(ctx, getOpenAttendanceForEmployee, employeeID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getTodayScheduleForEmployee = `-- name: GetTodayScheduleForEmployee :one
SELECT
    se.id AS schedule_id,
    ((se.work_date + se.start_time::time) AT TIME ZONE 'Asia/Jakarta')::timestamptz AS shift_start_at,
    (((se.work_date + se.end_time::time)
        + (CASE WHEN se.cross_midnight THEN interval '1 day' ELSE interval '0' END))
        AT TIME ZONE 'Asia/Jakarta')::timestamptz AS shift_end_at
FROM schedule_entries se
WHERE se.employee_id = $1
  AND se.work_date = ($2::timestamptz AT TIME ZONE 'Asia/Jakarta')::date
  AND se.deleted_at IS NULL
  AND se.is_day_off = false
  AND se.status <> 'CANCELLED_BY_LEAVE'
  AND se.start_time IS NOT NULL
  AND se.end_time   IS NOT NULL
ORDER BY se.start_time
LIMIT 1
`

type GetTodayScheduleForEmployeeParams struct {
	EmployeeID string
	Now        time.Time
}

type GetTodayScheduleForEmployeeRow struct {
	ScheduleID   string
	ShiftStartAt time.Time
	ShiftEndAt   time.Time
}

// Today's (Asia/Jakarta) live schedule entry for the employee — the basis for the
// lateness eval and the schedule_id stamped on the clock-in record. Mirrors
// absence.sql's shift-window computation. is_day_off / CANCELLED_BY_LEAVE entries are
// not work days; both times must be present. Earliest shift wins when more than one.
func (q *Queries) GetTodayScheduleForEmployee(ctx context.Context, arg GetTodayScheduleForEmployeeParams) (GetTodayScheduleForEmployeeRow, error) {
	row := q.db.QueryRow(ctx, getTodayScheduleForEmployee, arg.EmployeeID, arg.Now)
	var i GetTodayScheduleForEmployeeRow
	err := row.Scan(&i.ScheduleID, &i.ShiftStartAt, &i.ShiftEndAt)
	return i, err
}
