// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const agentRecentAttendance = `-- name: AgentRecentAttendance :one
SELECT
    count(*) FILTER (WHERE status IN ('PRESENT','LATE'))::bigint AS last_7d_present,
    count(*) FILTER (WHERE is_late)::bigint                      AS last_7d_late,
    count(*) FILTER (WHERE status = 'ABSENT')::bigint            AS last_7d_absent
FROM attendance
WHERE deleted_at IS NULL
  AND employee_id = $1
  AND check_in_at::date >= ($2::date - 7)
  AND check_in_at::date <= $2::date
`

type AgentRecentAttendanceParams struct {
	EmployeeID string
	Today      pgtype.Date
}

type AgentRecentAttendanceRow struct {
	Last7dPresent int64
	Last7dLate    int64
	Last7dAbsent  int64
}

// AgentDashboard.recent_attendance: last-7-day present/late/absent for one agent.
func (q *Queries) AgentRecentAttendance(ctx context.Context, arg AgentRecentAttendanceParams) (AgentRecentAttendanceRow, error) {
	row := q.db.QueryRow(ctx, agentRecentAttendance, arg.EmployeeID, arg.Today)
	var i AgentRecentAttendanceRow
	err := row.Scan(&i.Last7dPresent, &i.Last7dLate, &i.Last7dAbsent)
	return i, err
}

const countActiveCompanies = `-- name: CountActiveCompanies :one
SELECT count(DISTINCT client_company_id)::bigint AS total
FROM placements
WHERE deleted_at IS NULL
  AND lifecycle_status IN ('ACTIVE','EXTENDED','EXPIRING')
`

// HrDashboard.kpis.active_companies = companies with >=1 active placement.
func (q *Queries) CountActiveCompanies(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveCompanies)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countActivePlacements = `-- name: CountActivePlacements :one
SELECT count(*)::bigint AS total
FROM placements
WHERE deleted_at IS NULL
  AND lifecycle_status IN ('ACTIVE','EXTENDED','EXPIRING')
`

// HrDashboard.kpis.active_placements.
func (q *Queries) CountActivePlacements(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActivePlacements)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countExpiringAgreements30d = `-- name: CountExpiringAgreements30d :one
SELECT count(*)::bigint AS expiring
FROM employment_agreements
WHERE deleted_at IS NULL
  AND status = 'active'
  AND end_date IS NOT NULL
  AND end_date >= $1::date
  AND end_date <= ($1::date + 30)
`

// Employment agreements ending within the next 30 days (HrDashboard).
func (q *Queries) CountExpiringAgreements30d(ctx context.Context, today pgtype.Date) (int64, error) {
	row := q.db.QueryRow(ctx, countExpiringAgreements30d, today)
	var expiring int64
	err := row.Scan(&expiring)
	return expiring, err
}

const countExpiringPlacements30d = `-- name: CountExpiringPlacements30d :one
SELECT count(*)::bigint AS expiring
FROM placements
WHERE deleted_at IS NULL
  AND lifecycle_status IN ('ACTIVE','EXTENDED','EXPIRING')
  AND end_date IS NOT NULL
  AND end_date >= $1::date
  AND end_date <= ($1::date + 30)
  AND ($2::text IS NULL OR client_company_id = $2::text)
`

type CountExpiringPlacements30dParams struct {
	Today     pgtype.Date
	CompanyID *string
}

// Active/expiring placements ending within the next 30 days (inclusive of today).
func (q *Queries) CountExpiringPlacements30d(ctx context.Context, arg CountExpiringPlacements30dParams) (int64, error) {
	row := q.db.QueryRow(ctx, countExpiringPlacements30d, arg.Today, arg.CompanyID)
	var expiring int64
	err := row.Scan(&expiring)
	return expiring, err
}

const countPendingAttendanceVerify = `-- name: CountPendingAttendanceVerify :one

SELECT count(*)::bigint AS pending
FROM attendance
WHERE deleted_at IS NULL
  AND verification_status IN ('PENDING','ESCALATED')
  AND ($1::text IS NULL OR company_id = $1::text)
`

// E10 F10.2 dashboard aggregations (GET /dashboards/me). Read-only live counts
// over the existing E2..E8 tables — no rollup table (live for honesty, CONTEXT
// decision). All scope params are nullable: NULL = global (HR/super), a company id
// scopes to one company (shift_leader). The service passes role-derived scope.
//
// SCHEMA-ALIGNMENT NOTE [11-01 DECISION]: the plan prose used placeholder enum
// values that differ from the real Phase-7..9 schema. Aligned to reality:
//   - attendance.verification_status = 'PENDING' (NOT 'PENDING_VERIFY') —
//     00026_attendance.sql CHECK (AUTO_APPROVED/PENDING/VERIFIED/REJECTED/ESCALATED).
//     The leader queue counts PENDING + ESCALATED (both await action).
//   - leave_requests.status IN ('PENDING_L1','PENDING_HR') — 00028.
//   - overtime.status IN ('PENDING_L1','PENDING_HR') (NOT a bare 'PENDING') — 00031.
//   - placements use client_company_id + lifecycle_status + end_date — 00020.
//   - attendance carries company_id directly (denormalized); leave_requests +
//     overtime carry company_id (denormalized) too; schedule_entries does NOT, so
//     LeaderTodayStatus joins schedule_entries -> placements for company scope.
//
// Attendance awaiting leader verification (PENDING or ESCALATED).
func (q *Queries) CountPendingAttendanceVerify(ctx context.Context, companyID *string) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingAttendanceVerify, companyID)
	var pending int64
	err := row.Scan(&pending)
	return pending, err
}

const countPendingLeaveApprove = `-- name: CountPendingLeaveApprove :one
SELECT count(*)::bigint AS pending
FROM leave_requests
WHERE deleted_at IS NULL
  AND status IN ('PENDING_L1','PENDING_HR')
  AND ($1::text IS NULL OR company_id = $1::text)
`

// Leave requests pending either approval level.
func (q *Queries) CountPendingLeaveApprove(ctx context.Context, companyID *string) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingLeaveApprove, companyID)
	var pending int64
	err := row.Scan(&pending)
	return pending, err
}

const countPendingLeaveApproveHR = `-- name: CountPendingLeaveApproveHR :one
SELECT count(*)::bigint AS pending
FROM leave_requests
WHERE deleted_at IS NULL
  AND status = 'PENDING_HR'
  AND ($1::text IS NULL OR company_id = $1::text)
`

// HR-level-only pending leave (HrDashboard.kpis.leave_pending = PENDING_HR).
func (q *Queries) CountPendingLeaveApproveHR(ctx context.Context, companyID *string) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingLeaveApproveHR, companyID)
	var pending int64
	err := row.Scan(&pending)
	return pending, err
}

const countPendingOtApprove = `-- name: CountPendingOtApprove :one
SELECT count(*)::bigint AS pending
FROM overtime
WHERE deleted_at IS NULL
  AND status IN ('PENDING_L1','PENDING_HR')
  AND ($1::text IS NULL OR company_id = $1::text)
`

// Overtime pending either approval level.
func (q *Queries) CountPendingOtApprove(ctx context.Context, companyID *string) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingOtApprove, companyID)
	var pending int64
	err := row.Scan(&pending)
	return pending, err
}

const countPendingRequestsForEmployee = `-- name: CountPendingRequestsForEmployee :one
SELECT
    (SELECT count(*) FROM leave_requests lr
       WHERE lr.deleted_at IS NULL AND lr.employee_id = $1
         AND lr.status IN ('PENDING_L1','PENDING_HR'))::bigint AS leave_pending,
    (SELECT count(*) FROM overtime o
       WHERE o.deleted_at IS NULL AND o.employee_id = $1
         AND o.status IN ('PENDING_AGENT_CONFIRM','PENDING_L1','PENDING_HR'))::bigint AS ot_pending
`

type CountPendingRequestsForEmployeeRow struct {
	LeavePending int64
	OtPending    int64
}

// AgentDashboard.pending_requests: this agent's own pending leave + OT.
func (q *Queries) CountPendingRequestsForEmployee(ctx context.Context, employeeID string) (CountPendingRequestsForEmployeeRow, error) {
	row := q.db.QueryRow(ctx, countPendingRequestsForEmployee, employeeID)
	var i CountPendingRequestsForEmployeeRow
	err := row.Scan(&i.LeavePending, &i.OtPending)
	return i, err
}

const leaderTodayStatus = `-- name: LeaderTodayStatus :one
WITH sched AS (
    SELECT count(*)::bigint AS shifts_total
    FROM schedule_entries se
    JOIN placements p ON p.id = se.placement_id
    WHERE se.deleted_at IS NULL
      AND se.is_day_off = false
      AND se.work_date = $1::date
      AND ($2::text IS NULL OR p.client_company_id = $2::text)
),
att AS (
    SELECT
        count(*) FILTER (WHERE check_out_at IS NOT NULL OR check_in_at IS NOT NULL)::bigint AS clocked_in,
        count(*) FILTER (WHERE is_late)::bigint                                              AS late_count,
        count(*) FILTER (WHERE status = 'ABSENT')::bigint                                    AS absent_count,
        count(*) FILTER (WHERE verification_status IN ('PENDING','ESCALATED'))::bigint       AS pending_verifications
    FROM attendance
    WHERE deleted_at IS NULL
      AND check_in_at::date = $1::date
      AND ($2::text IS NULL OR company_id = $2::text)
)
SELECT
    COALESCE(sched.shifts_total, 0)        AS shifts_total,
    COALESCE(att.clocked_in, 0)            AS clocked_in,
    COALESCE(att.late_count, 0)            AS late_count,
    COALESCE(att.absent_count, 0)          AS absent_count,
    COALESCE(att.pending_verifications, 0) AS pending_verifications
FROM sched, att
`

type LeaderTodayStatusParams struct {
	Today     pgtype.Date
	CompanyID *string
}

type LeaderTodayStatusRow struct {
	ShiftsTotal          int64
	ClockedIn            int64
	LateCount            int64
	AbsentCount          int64
	PendingVerifications int64
}

// LeaderDashboard.today: today's shift roll-up for one company. shifts_total from
// schedule_entries (joined to placements for company scope); the attendance-derived
// counts read today's attendance rows (check_in_at::date = today). COALESCE to 0.
func (q *Queries) LeaderTodayStatus(ctx context.Context, arg LeaderTodayStatusParams) (LeaderTodayStatusRow, error) {
	row := q.db.QueryRow(ctx, leaderTodayStatus, arg.Today, arg.CompanyID)
	var i LeaderTodayStatusRow
	err := row.Scan(
		&i.ShiftsTotal,
		&i.ClockedIn,
		&i.LateCount,
		&i.AbsentCount,
		&i.PendingVerifications,
	)
	return i, err
}
