// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exports.sql

package sqlcgen

import (
	"context"
	"time"
)

const cancelExportJob = `-- name: CancelExportJob :one
UPDATE export_jobs
SET status       = 'CANCELLED',
    completed_at = now()
WHERE id = $1 AND status IN ('QUEUED','RUNNING')
RETURNING id, report_type, status, format, confidential, filters,
          progress_percent, row_count, artifact_ref, error_message,
          audit_log_entry_id, expires_at,
          requested_by_id, requested_by_name,
          requested_at, started_at, completed_at
`

type CancelExportJobRow struct {
	ID              string
	ReportType      string
	Status          string
	Format          string
	Confidential    bool
	Filters         []byte
	ProgressPercent *int32
	RowCount        *int32
	ArtifactRef     *string
	ErrorMessage    *string
	AuditLogEntryID *string
	ExpiresAt       *time.Time
	RequestedByID   string
	RequestedByName *string
	RequestedAt     time.Time
	StartedAt       *time.Time
	CompletedAt     *time.Time
}

// Cancel a still-running job (QUEUED/RUNNING -> CANCELLED). No-op-safe: the
// service re-reads via GetExportJob when 0 rows return (already terminal).
func (q *Queries) CancelExportJob(ctx context.Context, id string) (CancelExportJobRow, error) {
	row := q.db.QueryRow(ctx, cancelExportJob, id)
	var i CancelExportJobRow
	err := row.Scan(
		&i.ID,
		&i.ReportType,
		&i.Status,
		&i.Format,
		&i.Confidential,
		&i.Filters,
		&i.ProgressPercent,
		&i.RowCount,
		&i.ArtifactRef,
		&i.ErrorMessage,
		&i.AuditLogEntryID,
		&i.ExpiresAt,
		&i.RequestedByID,
		&i.RequestedByName,
		&i.RequestedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getExportJobGeneric = `-- name: GetExportJobGeneric :one
SELECT id, report_type, status, format, confidential, filters,
       progress_percent, row_count, artifact_ref, error_message,
       audit_log_entry_id, expires_at,
       requested_by_id, requested_by_name,
       requested_at, started_at, completed_at
FROM export_jobs
WHERE id = $1
`

type GetExportJobGenericRow struct {
	ID              string
	ReportType      string
	Status          string
	Format          string
	Confidential    bool
	Filters         []byte
	ProgressPercent *int32
	RowCount        *int32
	ArtifactRef     *string
	ErrorMessage    *string
	AuditLogEntryID *string
	ExpiresAt       *time.Time
	RequestedByID   string
	RequestedByName *string
	RequestedAt     time.Time
	StartedAt       *time.Time
	CompletedAt     *time.Time
}

// Status poll / GET /exports/{id}. Requester scope enforced in the service.
// Named *Generic to avoid colliding with the Phase-10 payroll GetExportJob
// (sqlc shares one sqlcgen package — query names are globally unique).
func (q *Queries) GetExportJobGeneric(ctx context.Context, id string) (GetExportJobGenericRow, error) {
	row := q.db.QueryRow(ctx, getExportJobGeneric, id)
	var i GetExportJobGenericRow
	err := row.Scan(
		&i.ID,
		&i.ReportType,
		&i.Status,
		&i.Format,
		&i.Confidential,
		&i.Filters,
		&i.ProgressPercent,
		&i.RowCount,
		&i.ArtifactRef,
		&i.ErrorMessage,
		&i.AuditLogEntryID,
		&i.ExpiresAt,
		&i.RequestedByID,
		&i.RequestedByName,
		&i.RequestedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertExportJobGeneric = `-- name: InsertExportJobGeneric :one

INSERT INTO export_jobs (
    kind, report_type, format, confidential, filters,
    requested_by_id, requested_by_name, audit_log_entry_id, expires_at
) VALUES (
    $1, $1, $2,
    $3, $4,
    $5, $6,
    $7, $8
)
RETURNING id, report_type, status, format, confidential, filters,
          progress_percent, row_count, artifact_ref, error_message,
          audit_log_entry_id, expires_at,
          requested_by_id, requested_by_name,
          requested_at, started_at, completed_at
`

type InsertExportJobGenericParams struct {
	ReportType      string
	Format          string
	Confidential    bool
	Filters         []byte
	RequestedByID   string
	RequestedByName *string
	AuditLogEntryID *string
	ExpiresAt       *time.Time
}

type InsertExportJobGenericRow struct {
	ID              string
	ReportType      string
	Status          string
	Format          string
	Confidential    bool
	Filters         []byte
	ProgressPercent *int32
	RowCount        *int32
	ArtifactRef     *string
	ErrorMessage    *string
	AuditLogEntryID *string
	ExpiresAt       *time.Time
	RequestedByID   string
	RequestedByName *string
	RequestedAt     time.Time
	StartedAt       *time.Time
	CompletedAt     *time.Time
}

// E10 F10.4 generic export-framework queries over the GENERALIZED export_jobs
// table (00036). These are NEW, generic queries (report_type + filters jsonb);
// the Phase-10 payroll/export_jobs.sql queries (InsertExportJob / GetExportJob /
// UpdateExportJobStatus, PAYSLIP path) stay UNTOUCHED. The 11-02b export service
// uses these for ATTENDANCE_BILLABLE etc.
//
// DB status QUEUED/RUNNING/DONE/FAILED/CANCELLED; the service maps RUNNING<->
// PROCESSING and DONE<->COMPLETED to the wire ExportStatus at the DTO boundary.
// id allocated by the column DEFAULT 'SWP-EXP-' || swp_next_id('EXP') (omit id).
// Queue a generic report export. status defaults QUEUED. kind is set to the
// report_type for forward-compat with the Phase-10 'kind' column (the worker
// branches on report_type). format/confidential/filters per request.
func (q *Queries) InsertExportJobGeneric(ctx context.Context, arg InsertExportJobGenericParams) (InsertExportJobGenericRow, error) {
	row := q.db.QueryRow(ctx, insertExportJobGeneric,
		arg.ReportType,
		arg.Format,
		arg.Confidential,
		arg.Filters,
		arg.RequestedByID,
		arg.RequestedByName,
		arg.AuditLogEntryID,
		arg.ExpiresAt,
	)
	var i InsertExportJobGenericRow
	err := row.Scan(
		&i.ID,
		&i.ReportType,
		&i.Status,
		&i.Format,
		&i.Confidential,
		&i.Filters,
		&i.ProgressPercent,
		&i.RowCount,
		&i.ArtifactRef,
		&i.ErrorMessage,
		&i.AuditLogEntryID,
		&i.ExpiresAt,
		&i.RequestedByID,
		&i.RequestedByName,
		&i.RequestedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateExportJobStatusGeneric = `-- name: UpdateExportJobStatusGeneric :one
UPDATE export_jobs
SET status           = $1,
    progress_percent = COALESCE($2::int, progress_percent),
    row_count        = COALESCE($3::int, row_count),
    artifact_ref     = COALESCE($4::text, artifact_ref),
    error_message    = COALESCE($5::text, error_message),
    expires_at       = COALESCE($6::timestamptz, expires_at),
    started_at       = COALESCE(started_at, CASE WHEN $1 = 'RUNNING' THEN now() END),
    completed_at     = CASE WHEN $1 IN ('DONE','FAILED','CANCELLED') THEN now() ELSE completed_at END
WHERE id = $7
RETURNING id, report_type, status, format, confidential, filters,
          progress_percent, row_count, artifact_ref, error_message,
          audit_log_entry_id, expires_at,
          requested_by_id, requested_by_name,
          requested_at, started_at, completed_at
`

type UpdateExportJobStatusGenericParams struct {
	Status          string
	ProgressPercent *int32
	RowCount        *int32
	ArtifactRef     *string
	ErrorMessage    *string
	ExpiresAt       *time.Time
	ID              string
}

type UpdateExportJobStatusGenericRow struct {
	ID              string
	ReportType      string
	Status          string
	Format          string
	Confidential    bool
	Filters         []byte
	ProgressPercent *int32
	RowCount        *int32
	ArtifactRef     *string
	ErrorMessage    *string
	AuditLogEntryID *string
	ExpiresAt       *time.Time
	RequestedByID   string
	RequestedByName *string
	RequestedAt     time.Time
	StartedAt       *time.Time
	CompletedAt     *time.Time
}

// The generic worker's lifecycle writer. Sets status + progress + result fields;
// stamps started_at on RUNNING (once) and completed_at on the terminal states
// (DONE/FAILED/CANCELLED). filename mirrors artifact_ref on the wire (11-02b DTO).
func (q *Queries) UpdateExportJobStatusGeneric(ctx context.Context, arg UpdateExportJobStatusGenericParams) (UpdateExportJobStatusGenericRow, error) {
	row := q.db.QueryRow(ctx, updateExportJobStatusGeneric,
		arg.Status,
		arg.ProgressPercent,
		arg.RowCount,
		arg.ArtifactRef,
		arg.ErrorMessage,
		arg.ExpiresAt,
		arg.ID,
	)
	var i UpdateExportJobStatusGenericRow
	err := row.Scan(
		&i.ID,
		&i.ReportType,
		&i.Status,
		&i.Format,
		&i.Confidential,
		&i.Filters,
		&i.ProgressPercent,
		&i.RowCount,
		&i.ArtifactRef,
		&i.ErrorMessage,
		&i.AuditLogEntryID,
		&i.ExpiresAt,
		&i.RequestedByID,
		&i.RequestedByName,
		&i.RequestedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}
