// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instances.sql

package sqlcgen

import (
	"context"
	"time"
)

const getApprovalInstance = `-- name: GetApprovalInstance :one
SELECT id, request_type, request_id, company_id, template_id, template_version,
       current_line, line_count, status, requester_id, created_at, updated_at
FROM approval_instances
WHERE id = $1
`

func (q *Queries) GetApprovalInstance(ctx context.Context, id string) (ApprovalInstance, error) {
	row := q.db.QueryRow(ctx, getApprovalInstance, id)
	var i ApprovalInstance
	err := row.Scan(
		&i.ID,
		&i.RequestType,
		&i.RequestID,
		&i.CompanyID,
		&i.TemplateID,
		&i.TemplateVersion,
		&i.CurrentLine,
		&i.LineCount,
		&i.Status,
		&i.RequesterID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApprovalInstanceByRequest = `-- name: GetApprovalInstanceByRequest :one
SELECT id, request_type, request_id, company_id, template_id, template_version,
       current_line, line_count, status, requester_id, created_at, updated_at
FROM approval_instances
WHERE request_type = $1
  AND request_id   = $2
`

type GetApprovalInstanceByRequestParams struct {
	RequestType string
	RequestID   string
}

// Resolve the instance governing a given domain request (leave/OT read linkage).
func (q *Queries) GetApprovalInstanceByRequest(ctx context.Context, arg GetApprovalInstanceByRequestParams) (ApprovalInstance, error) {
	row := q.db.QueryRow(ctx, getApprovalInstanceByRequest, arg.RequestType, arg.RequestID)
	var i ApprovalInstance
	err := row.Scan(
		&i.ID,
		&i.RequestType,
		&i.RequestID,
		&i.CompanyID,
		&i.TemplateID,
		&i.TemplateVersion,
		&i.CurrentLine,
		&i.LineCount,
		&i.Status,
		&i.RequesterID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApprovalInstanceForUpdate = `-- name: GetApprovalInstanceForUpdate :one
SELECT id, request_type, request_id, company_id, template_id, template_version,
       current_line, line_count, status, requester_id, created_at, updated_at
FROM approval_instances
WHERE id = $1
FOR UPDATE
`

// Row-lock for the act/bypass transition (advance line / terminate). The service
// guards the legal transition before writing.
func (q *Queries) GetApprovalInstanceForUpdate(ctx context.Context, id string) (ApprovalInstance, error) {
	row := q.db.QueryRow(ctx, getApprovalInstanceForUpdate, id)
	var i ApprovalInstance
	err := row.Scan(
		&i.ID,
		&i.RequestType,
		&i.RequestID,
		&i.CompanyID,
		&i.TemplateID,
		&i.TemplateVersion,
		&i.CurrentLine,
		&i.LineCount,
		&i.Status,
		&i.RequesterID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCurrentLineMembers = `-- name: GetCurrentLineMembers :many
SELECT alm.user_id
FROM approval_instances ai
JOIN approval_lines al
     ON al.template_id = ai.template_id
    AND al.line_no     = ai.current_line
JOIN approval_line_members alm
     ON alm.line_id = al.id
WHERE ai.id = $1
`

// Members of an instance's CURRENT line — for the membership / self-approval check
// (INV-2 OR-set, INV-3). Resolves the live template's line at line_no = current_line.
func (q *Queries) GetCurrentLineMembers(ctx context.Context, instanceID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getCurrentLineMembers, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertApprovalInstance = `-- name: InsertApprovalInstance :one

INSERT INTO approval_instances (
    request_type, request_id, company_id, template_id, template_version,
    current_line, line_count, status, requester_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, request_type, request_id, company_id, template_id, template_version,
          current_line, line_count, status, requester_id, created_at, updated_at
`

type InsertApprovalInstanceParams struct {
	RequestType     string
	RequestID       string
	CompanyID       *string
	TemplateID      *string
	TemplateVersion *int32
	CurrentLine     int32
	LineCount       int32
	Status          string
	RequesterID     *string
}

// E11 approval-instance queries (F11.2 / SWP-APV-*). One live run of the engine per
// domain request (unique request_type+request_id). Keyset cursor on (created_at,id)
// DESC, mirroring ListLeaveRequests (CONVENTIONS §11). id from the column DEFAULT
// ('SWP-APV-' || swp_next_id('APV')).
// Build an instance from the company's template (template_id null = super-admin
// fallback, INV-7). line_count = configured lines (1 for fallback). id from DEFAULT.
func (q *Queries) InsertApprovalInstance(ctx context.Context, arg InsertApprovalInstanceParams) (ApprovalInstance, error) {
	row := q.db.QueryRow(ctx, insertApprovalInstance,
		arg.RequestType,
		arg.RequestID,
		arg.CompanyID,
		arg.TemplateID,
		arg.TemplateVersion,
		arg.CurrentLine,
		arg.LineCount,
		arg.Status,
		arg.RequesterID,
	)
	var i ApprovalInstance
	err := row.Scan(
		&i.ID,
		&i.RequestType,
		&i.RequestID,
		&i.CompanyID,
		&i.TemplateID,
		&i.TemplateVersion,
		&i.CurrentLine,
		&i.LineCount,
		&i.Status,
		&i.RequesterID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApprovalInstances = `-- name: ListApprovalInstances :many
SELECT id, request_type, request_id, company_id, template_id, template_version,
       current_line, line_count, status, requester_id, created_at, updated_at
FROM approval_instances
WHERE ($1::text   IS NULL OR company_id   = $1::text)
  AND ($2::text IS NULL OR request_type = $2::text)
  AND ($3::text       IS NULL OR status       = $3::text)
  AND ($4::timestamptz IS NULL OR
       (created_at, id) < ($4::timestamptz, $5::text))
ORDER BY created_at DESC, id DESC
LIMIT $6
`

type ListApprovalInstancesParams struct {
	CompanyID       *string
	RequestType     *string
	Status          *string
	CursorCreatedAt *time.Time
	CursorID        *string
	Lim             int32
}

// Queue / list load. Keyset cursor (created_at,id) DESC. Filters (all optional via
// narg): company_id, request_type, status.
func (q *Queries) ListApprovalInstances(ctx context.Context, arg ListApprovalInstancesParams) ([]ApprovalInstance, error) {
	rows, err := q.db.Query(ctx, listApprovalInstances,
		arg.CompanyID,
		arg.RequestType,
		arg.Status,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApprovalInstance{}
	for rows.Next() {
		var i ApprovalInstance
		if err := rows.Scan(
			&i.ID,
			&i.RequestType,
			&i.RequestID,
			&i.CompanyID,
			&i.TemplateID,
			&i.TemplateVersion,
			&i.CurrentLine,
			&i.LineCount,
			&i.Status,
			&i.RequesterID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApprovalInstancesForMember = `-- name: ListApprovalInstancesForMember :many
SELECT ai.id, ai.request_type, ai.request_id, ai.company_id, ai.template_id,
       ai.template_version, ai.current_line, ai.line_count, ai.status,
       ai.requester_id, ai.created_at, ai.updated_at
FROM approval_instances ai
JOIN approval_lines al
     ON al.template_id = ai.template_id
    AND al.line_no     = ai.current_line
JOIN approval_line_members alm
     ON alm.line_id = al.id
    AND alm.user_id = $1
WHERE ai.status = 'PENDING'
  AND (ai.requester_id IS NULL OR ai.requester_id <> $1)
  AND ($2::text   IS NULL OR ai.company_id   = $2::text)
  AND ($3::text IS NULL OR ai.request_type = $3::text)
  AND ($4::timestamptz IS NULL OR
       (ai.created_at, ai.id) < ($4::timestamptz, $5::text))
ORDER BY ai.created_at DESC, ai.id DESC
LIMIT $6
`

type ListApprovalInstancesForMemberParams struct {
	MemberUserID    string
	CompanyID       *string
	RequestType     *string
	CursorCreatedAt *time.Time
	CursorID        *string
	Lim             int32
}

// The `mine` inbox (F11.3): PENDING instances whose CURRENT line includes the given
// member (member_user_id), excluding the member's own requests (INV-3 self-approval
// block — requester_id != member). Same optional filters (company_id, request_type)
// + keyset cursor (created_at,id) DESC. The current line is resolved by joining the
// live template's line at line_no = current_line.
func (q *Queries) ListApprovalInstancesForMember(ctx context.Context, arg ListApprovalInstancesForMemberParams) ([]ApprovalInstance, error) {
	rows, err := q.db.Query(ctx, listApprovalInstancesForMember,
		arg.MemberUserID,
		arg.CompanyID,
		arg.RequestType,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApprovalInstance{}
	for rows.Next() {
		var i ApprovalInstance
		if err := rows.Scan(
			&i.ID,
			&i.RequestType,
			&i.RequestID,
			&i.CompanyID,
			&i.TemplateID,
			&i.TemplateVersion,
			&i.CurrentLine,
			&i.LineCount,
			&i.Status,
			&i.RequesterID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetPendingInstancesForCompany = `-- name: ResetPendingInstancesForCompany :exec
UPDATE approval_instances
SET current_line     = 1,
    template_version = $1,
    updated_at       = now()
WHERE company_id = $2
  AND status     = 'PENDING'
`

type ResetPendingInstancesForCompanyParams struct {
	TemplateVersion *int32
	CompanyID       *string
}

// INV-6 live-template reset: on a template edit, every non-terminal instance for the
// company restarts at line 1 on the new version (prior actions retained for audit
// but no longer count).
func (q *Queries) ResetPendingInstancesForCompany(ctx context.Context, arg ResetPendingInstancesForCompanyParams) error {
	_, err := q.db.Exec(ctx, resetPendingInstancesForCompany, arg.TemplateVersion, arg.CompanyID)
	return err
}

const updateApprovalInstanceProgress = `-- name: UpdateApprovalInstanceProgress :exec
UPDATE approval_instances
SET current_line = $1,
    status       = $2,
    updated_at   = now()
WHERE id = $3
`

type UpdateApprovalInstanceProgressParams struct {
	CurrentLine int32
	Status      string
	ID          string
}

// Advance the chain: set current_line + status after a line clears / terminal
// reject / bypass.
func (q *Queries) UpdateApprovalInstanceProgress(ctx context.Context, arg UpdateApprovalInstanceProgressParams) error {
	_, err := q.db.Exec(ctx, updateApprovalInstanceProgress, arg.CurrentLine, arg.Status, arg.ID)
	return err
}
