// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lead_assignments.sql

package sqlcgen

import (
	"context"
	"time"
)

const createLeadAssignment = `-- name: CreateLeadAssignment :one
INSERT INTO lead_assignments (
    employee_id, client_company_id, site_id, assigned_by
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, employee_id, client_company_id, site_id, assigned_at,
          unassigned_at, assigned_by, created_at, updated_at
`

type CreateLeadAssignmentParams struct {
	EmployeeID      string
	ClientCompanyID string
	SiteID          *string
	AssignedBy      *string
}

// id allocated by the column DEFAULT ('SWP-LA-' || swp_next_id('LA')).
func (q *Queries) CreateLeadAssignment(ctx context.Context, arg CreateLeadAssignmentParams) (LeadAssignment, error) {
	row := q.db.QueryRow(ctx, createLeadAssignment,
		arg.EmployeeID,
		arg.ClientCompanyID,
		arg.SiteID,
		arg.AssignedBy,
	)
	var i LeadAssignment
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.ClientCompanyID,
		&i.SiteID,
		&i.AssignedAt,
		&i.UnassignedAt,
		&i.AssignedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const endLeadAssignment = `-- name: EndLeadAssignment :exec
UPDATE lead_assignments
SET unassigned_at = now(),
    updated_at    = now()
WHERE id = $1
  AND unassigned_at IS NULL
`

// Sets unassigned_at=now() on the active row (releases lead_assignment_active_uq).
func (q *Queries) EndLeadAssignment(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, endLeadAssignment, id)
	return err
}

const listActiveLeadCompaniesForEmployee = `-- name: ListActiveLeadCompaniesForEmployee :many
SELECT client_company_id
FROM lead_assignments
WHERE employee_id = $1
  AND unassigned_at IS NULL
ORDER BY client_company_id
`

// The set of companies the lead currently covers — drives Principal.CompanyIDs.
func (q *Queries) ListActiveLeadCompaniesForEmployee(ctx context.Context, employeeID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listActiveLeadCompaniesForEmployee, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var client_company_id string
		if err := rows.Scan(&client_company_id); err != nil {
			return nil, err
		}
		items = append(items, client_company_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeadAssignments = `-- name: ListLeadAssignments :many

SELECT la.id, la.employee_id, la.client_company_id, la.site_id,
       la.assigned_at, la.unassigned_at, la.assigned_by,
       la.created_at, la.updated_at,
       c.name AS client_company_name,
       e.full_name AS employee_name
FROM lead_assignments la
LEFT JOIN client_companies c ON c.id = la.client_company_id
LEFT JOIN employees e        ON e.id = la.employee_id
WHERE ($1::text  IS NULL OR la.client_company_id = $1::text)
  AND ($2::text IS NULL OR la.employee_id       = $2::text)
  AND (NOT $3::boolean OR la.unassigned_at IS NULL)
ORDER BY la.assigned_at DESC, la.id DESC
`

type ListLeadAssignmentsParams struct {
	CompanyID  *string
	EmployeeID *string
	ActiveOnly bool
}

type ListLeadAssignmentsRow struct {
	ID                string
	EmployeeID        string
	ClientCompanyID   string
	SiteID            *string
	AssignedAt        time.Time
	UnassignedAt      *time.Time
	AssignedBy        *string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	ClientCompanyName *string
	EmployeeName      *string
}

// E3 lead_assignments queries. A lead (service-line operational approver) covers
// MANY client companies; the auth middleware derives Principal.CompanyIDs from the
// active rows here at request time (mirror of shift_leader_assignments derivation).
// Filters: employee_id, company_id, active (unassigned_at IS NULL).
func (q *Queries) ListLeadAssignments(ctx context.Context, arg ListLeadAssignmentsParams) ([]ListLeadAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listLeadAssignments, arg.CompanyID, arg.EmployeeID, arg.ActiveOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLeadAssignmentsRow{}
	for rows.Next() {
		var i ListLeadAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.ClientCompanyID,
			&i.SiteID,
			&i.AssignedAt,
			&i.UnassignedAt,
			&i.AssignedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientCompanyName,
			&i.EmployeeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
