// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leave_meter.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAnnualEntitlementForEmployee = `-- name: GetAnnualEntitlementForEmployee :one
SELECT annual_leave_entitlement_days
FROM employment_agreements
WHERE employee_id = $1
  AND status = 'active'
  AND deleted_at IS NULL
LIMIT 1
`

// ANNUAL_POOL entitlement source: the employee's active employment agreement
// (annual_leave_entitlement_days, migr. 00040). NULL when unset.
func (q *Queries) GetAnnualEntitlementForEmployee(ctx context.Context, employeeID string) (*int32, error) {
	row := q.db.QueryRow(ctx, getAnnualEntitlementForEmployee, employeeID)
	var annual_leave_entitlement_days *int32
	err := row.Scan(&annual_leave_entitlement_days)
	return annual_leave_entitlement_days, err
}

const getEmployeeGateInfo = `-- name: GetEmployeeGateInfo :one
SELECT gender, join_at
FROM employees
WHERE id = $1 AND deleted_at IS NULL
`

type GetEmployeeGateInfoRow struct {
	Gender *string
	JoinAt pgtype.Date
}

// Gender (nullable) + tenure source (join_at) for the request-time gates.
func (q *Queries) GetEmployeeGateInfo(ctx context.Context, id string) (GetEmployeeGateInfoRow, error) {
	row := q.db.QueryRow(ctx, getEmployeeGateInfo, id)
	var i GetEmployeeGateInfoRow
	err := row.Scan(&i.Gender, &i.JoinAt)
	return i, err
}

const getLeaveTypeCap = `-- name: GetLeaveTypeCap :one

SELECT id, code, name, cap_basis, cap_value, cap_unit, paid, gender,
       requires_document, notice_days, min_service_years, lead_days, trail_days
FROM leave_types
WHERE id = $1 AND deleted_at IS NULL
`

type GetLeaveTypeCapRow struct {
	ID               string
	Code             string
	Name             string
	CapBasis         string
	CapValue         *int32
	CapUnit          string
	Paid             bool
	Gender           string
	RequiresDocument bool
	NoticeDays       int32
	MinServiceYears  int32
	LeadDays         int32
	TrailDays        int32
}

// E6 per-type meter read queries (Phase 3, EPICS §8 2026-06-12). Source data the
// QuotaMeter needs to pick the window, gate eligibility, and size the annual pool.
// Cap mechanics for a leave type (leave_types, migr. 00050).
func (q *Queries) GetLeaveTypeCap(ctx context.Context, id string) (GetLeaveTypeCapRow, error) {
	row := q.db.QueryRow(ctx, getLeaveTypeCap, id)
	var i GetLeaveTypeCapRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.CapBasis,
		&i.CapValue,
		&i.CapUnit,
		&i.Paid,
		&i.Gender,
		&i.RequiresDocument,
		&i.NoticeDays,
		&i.MinServiceYears,
		&i.LeadDays,
		&i.TrailDays,
	)
	return i, err
}
