// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leave_quotas.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adjustQuotaEntitled = `-- name: AdjustQuotaEntitled :one
UPDATE leave_quotas
SET entitled_days   = entitled_days + $1,
    source          = 'ADJUSTMENT',
    remark          = $2,
    last_adjustment = $3,
    updated_at      = now()
WHERE id = $4
RETURNING id, employee_id, leave_type_id, last_adjustment, last_override, created_at, updated_at, period_key, entitled_days, used_days, pending_days, source, remark, expires_at, created_by
`

type AdjustQuotaEntitledParams struct {
	Delta          int32
	Remark         string
	LastAdjustment []byte
	ID             string
}

// HR per-type quota adjust (LQ-6): signed delta on entitled_days; service guards
// entitled cannot drop below used+pending and records last_adjustment.
func (q *Queries) AdjustQuotaEntitled(ctx context.Context, arg AdjustQuotaEntitledParams) (LeaveQuota, error) {
	row := q.db.QueryRow(ctx, adjustQuotaEntitled,
		arg.Delta,
		arg.Remark,
		arg.LastAdjustment,
		arg.ID,
	)
	var i LeaveQuota
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.LeaveTypeID,
		&i.LastAdjustment,
		&i.LastOverride,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PeriodKey,
		&i.EntitledDays,
		&i.UsedDays,
		&i.PendingDays,
		&i.Source,
		&i.Remark,
		&i.ExpiresAt,
		&i.CreatedBy,
	)
	return i, err
}

const commitQuotaDays = `-- name: CommitQuotaDays :one
UPDATE leave_quotas
SET pending_days = GREATEST(pending_days - $1, 0),
    used_days    = used_days + $1,
    updated_at   = now()
WHERE id = $2
RETURNING id, employee_id, leave_type_id, last_adjustment, last_override, created_at, updated_at, period_key, entitled_days, used_days, pending_days, source, remark, expires_at, created_by
`

type CommitQuotaDaysParams struct {
	Delta int32
	ID    string
}

// Final approval: move the reservation pending_days -> used_days.
func (q *Queries) CommitQuotaDays(ctx context.Context, arg CommitQuotaDaysParams) (LeaveQuota, error) {
	row := q.db.QueryRow(ctx, commitQuotaDays, arg.Delta, arg.ID)
	var i LeaveQuota
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.LeaveTypeID,
		&i.LastAdjustment,
		&i.LastOverride,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PeriodKey,
		&i.EntitledDays,
		&i.UsedDays,
		&i.PendingDays,
		&i.Source,
		&i.Remark,
		&i.ExpiresAt,
		&i.CreatedBy,
	)
	return i, err
}

const countApprovedRequestsForType = `-- name: CountApprovedRequestsForType :one
SELECT count(*)
FROM leave_requests lr
WHERE lr.employee_id   = $1
  AND lr.leave_type_id = $2
  AND lr.status IN ('PENDING_L1','PENDING_HR','APPROVED')
  AND lr.start_date >= $3::date
  AND lr.start_date <= $4::date
  AND lr.deleted_at IS NULL
`

type CountApprovedRequestsForTypeParams struct {
	EmployeeID  string
	LeaveTypeID string
	WindowStart pgtype.Date
	WindowEnd   pgtype.Date
}

// Occurrence/lifetime gate source (PER_YEAR_COUNT, LIFETIME_ONCE): how many
// non-terminal-rejected requests of this type the employee already has in the
// window [from,to]. Counts PENDING_*/APPROVED (reserved or committed).
func (q *Queries) CountApprovedRequestsForType(ctx context.Context, arg CountApprovedRequestsForTypeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countApprovedRequestsForType,
		arg.EmployeeID,
		arg.LeaveTypeID,
		arg.WindowStart,
		arg.WindowEnd,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const openQuotaWindow = `-- name: OpenQuotaWindow :one
INSERT INTO leave_quotas (
    employee_id, leave_type_id, period_key,
    entitled_days, source, remark, expires_at, created_by
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
ON CONFLICT (employee_id, leave_type_id, period_key) DO UPDATE
SET entitled_days = EXCLUDED.entitled_days,
    expires_at    = EXCLUDED.expires_at,
    updated_at    = now()
RETURNING id, employee_id, leave_type_id, last_adjustment, last_override, created_at, updated_at, period_key, entitled_days, used_days, pending_days, source, remark, expires_at, created_by
`

type OpenQuotaWindowParams struct {
	EmployeeID   string
	LeaveTypeID  string
	PeriodKey    *string
	EntitledDays int32
	Source       string
	Remark       string
	ExpiresAt    pgtype.Date
	CreatedBy    *string
}

// Auto-open a per-type window at its entitlement (annual: agreement days; other
// quota-bearing: cap_value). Idempotent on the (emp,type,period_key) unique index.
func (q *Queries) OpenQuotaWindow(ctx context.Context, arg OpenQuotaWindowParams) (LeaveQuota, error) {
	row := q.db.QueryRow(ctx, openQuotaWindow,
		arg.EmployeeID,
		arg.LeaveTypeID,
		arg.PeriodKey,
		arg.EntitledDays,
		arg.Source,
		arg.Remark,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i LeaveQuota
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.LeaveTypeID,
		&i.LastAdjustment,
		&i.LastOverride,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PeriodKey,
		&i.EntitledDays,
		&i.UsedDays,
		&i.PendingDays,
		&i.Source,
		&i.Remark,
		&i.ExpiresAt,
		&i.CreatedBy,
	)
	return i, err
}

const releaseQuotaDays = `-- name: ReleaseQuotaDays :one
UPDATE leave_quotas
SET pending_days = GREATEST(pending_days - $1, 0),
    updated_at   = now()
WHERE id = $2
RETURNING id, employee_id, leave_type_id, last_adjustment, last_override, created_at, updated_at, period_key, entitled_days, used_days, pending_days, source, remark, expires_at, created_by
`

type ReleaseQuotaDaysParams struct {
	Delta int32
	ID    string
}

// Reject/withdraw: release the held reservation.
func (q *Queries) ReleaseQuotaDays(ctx context.Context, arg ReleaseQuotaDaysParams) (LeaveQuota, error) {
	row := q.db.QueryRow(ctx, releaseQuotaDays, arg.Delta, arg.ID)
	var i LeaveQuota
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.LeaveTypeID,
		&i.LastAdjustment,
		&i.LastOverride,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PeriodKey,
		&i.EntitledDays,
		&i.UsedDays,
		&i.PendingDays,
		&i.Source,
		&i.Remark,
		&i.ExpiresAt,
		&i.CreatedBy,
	)
	return i, err
}

const reserveQuotaDays = `-- name: ReserveQuotaDays :one
UPDATE leave_quotas
SET pending_days = pending_days + $1,
    updated_at   = now()
WHERE id = $2
RETURNING id, employee_id, leave_type_id, last_adjustment, last_override, created_at, updated_at, period_key, entitled_days, used_days, pending_days, source, remark, expires_at, created_by
`

type ReserveQuotaDaysParams struct {
	Delta int32
	ID    string
}

// Submit: hold pending_days on the window (remaining must cover it — service guards).
func (q *Queries) ReserveQuotaDays(ctx context.Context, arg ReserveQuotaDaysParams) (LeaveQuota, error) {
	row := q.db.QueryRow(ctx, reserveQuotaDays, arg.Delta, arg.ID)
	var i LeaveQuota
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.LeaveTypeID,
		&i.LastAdjustment,
		&i.LastOverride,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PeriodKey,
		&i.EntitledDays,
		&i.UsedDays,
		&i.PendingDays,
		&i.Source,
		&i.Remark,
		&i.ExpiresAt,
		&i.CreatedBy,
	)
	return i, err
}

const resolveQuotaWindow = `-- name: ResolveQuotaWindow :one

SELECT lq.id, lq.employee_id, lq.leave_type_id, lq.last_adjustment, lq.last_override, lq.created_at, lq.updated_at, lq.period_key, lq.entitled_days, lq.used_days, lq.pending_days, lq.source, lq.remark, lq.expires_at, lq.created_by
FROM leave_quotas lq
WHERE lq.employee_id   = $1
  AND lq.leave_type_id = $2
  AND lq.period_key    = $3
FOR UPDATE
`

type ResolveQuotaWindowParams struct {
	EmployeeID  string
	LeaveTypeID string
	PeriodKey   *string
}

// E6 per-type leave-quota window queries (F6.1 LQ-13 / SWP-LQ-*). The cap_basis
// ledger meters per (employee, leave_type, period_key) window: reserve at submit,
// commit at approve, release at reject/cancel; remaining = entitled-used-pending is a
// DERIVED domain method. no-negative enforced by the entitled/used/pending CHECKs.
// last_adjustment / last_override are jsonb → []byte in sqlc.
// Row-locked lookup of the per-type window for reserve/commit/release.
func (q *Queries) ResolveQuotaWindow(ctx context.Context, arg ResolveQuotaWindowParams) (LeaveQuota, error) {
	row := q.db.QueryRow(ctx, resolveQuotaWindow, arg.EmployeeID, arg.LeaveTypeID, arg.PeriodKey)
	var i LeaveQuota
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.LeaveTypeID,
		&i.LastAdjustment,
		&i.LastOverride,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PeriodKey,
		&i.EntitledDays,
		&i.UsedDays,
		&i.PendingDays,
		&i.Source,
		&i.Remark,
		&i.ExpiresAt,
		&i.CreatedBy,
	)
	return i, err
}

const reverseCommittedQuotaDays = `-- name: ReverseCommittedQuotaDays :one
UPDATE leave_quotas
SET used_days  = GREATEST(used_days - $1, 0),
    updated_at = now()
WHERE id = $2
RETURNING id, employee_id, leave_type_id, last_adjustment, last_override, created_at, updated_at, period_key, entitled_days, used_days, pending_days, source, remark, expires_at, created_by
`

type ReverseCommittedQuotaDaysParams struct {
	Delta int32
	ID    string
}

// Cancel/shorten an APPROVED leave: return committed days to the balance.
func (q *Queries) ReverseCommittedQuotaDays(ctx context.Context, arg ReverseCommittedQuotaDaysParams) (LeaveQuota, error) {
	row := q.db.QueryRow(ctx, reverseCommittedQuotaDays, arg.Delta, arg.ID)
	var i LeaveQuota
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.LeaveTypeID,
		&i.LastAdjustment,
		&i.LastOverride,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PeriodKey,
		&i.EntitledDays,
		&i.UsedDays,
		&i.PendingDays,
		&i.Source,
		&i.Remark,
		&i.ExpiresAt,
		&i.CreatedBy,
	)
	return i, err
}
