// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leave_grants.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyConsumption = `-- name: ApplyConsumption :one
INSERT INTO leave_consumptions (leave_request_id, grant_id, days)
VALUES ($1, $2, $3)
RETURNING id, leave_request_id, grant_id, days, created_at
`

type ApplyConsumptionParams struct {
	LeaveRequestID string
	GrantID        string
	Days           int32
}

// Write one lot-drawdown row at APPROVE (one per lot the request drew). id allocated
// by column DEFAULT.
func (q *Queries) ApplyConsumption(ctx context.Context, arg ApplyConsumptionParams) (LeaveConsumption, error) {
	row := q.db.QueryRow(ctx, applyConsumption, arg.LeaveRequestID, arg.GrantID, arg.Days)
	var i LeaveConsumption
	err := row.Scan(
		&i.ID,
		&i.LeaveRequestID,
		&i.GrantID,
		&i.Days,
		&i.CreatedAt,
	)
	return i, err
}

const commitReservation = `-- name: CommitReservation :one
UPDATE leave_grants
SET pending_days  = GREATEST(pending_days - $1, 0),
    consumed_days = consumed_days + $1,
    updated_at    = now()
WHERE id = $2
RETURNING id, employee_id, amount_days, granted_at, effective_from, expires_at,
          source, earmark, remark, consumed_days, pending_days, created_by,
          created_at, updated_at
`

type CommitReservationParams struct {
	Days int32
	ID   string
}

type CommitReservationRow struct {
	ID            string
	EmployeeID    string
	AmountDays    int32
	GrantedAt     time.Time
	EffectiveFrom pgtype.Date
	ExpiresAt     pgtype.Date
	Source        string
	Earmark       *string
	Remark        *string
	ConsumedDays  int32
	PendingDays   int32
	CreatedBy     *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// Move days pending_days → consumed_days at APPROVE (commit). Paired with an
// ApplyConsumption (leave_consumptions) insert in the same tx.
func (q *Queries) CommitReservation(ctx context.Context, arg CommitReservationParams) (CommitReservationRow, error) {
	row := q.db.QueryRow(ctx, commitReservation, arg.Days, arg.ID)
	var i CommitReservationRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.AmountDays,
		&i.GrantedAt,
		&i.EffectiveFrom,
		&i.ExpiresAt,
		&i.Source,
		&i.Earmark,
		&i.Remark,
		&i.ConsumedDays,
		&i.PendingDays,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLeaveGrant = `-- name: CreateLeaveGrant :one

INSERT INTO leave_grants (
    employee_id, amount_days, granted_at, effective_from, expires_at,
    source, earmark, remark, created_by
) VALUES (
    $1,
    $2,
    now(),
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, employee_id, amount_days, granted_at, effective_from, expires_at,
          source, earmark, remark, consumed_days, pending_days, created_by,
          created_at, updated_at
`

type CreateLeaveGrantParams struct {
	EmployeeID    string
	AmountDays    int32
	EffectiveFrom pgtype.Date
	ExpiresAt     pgtype.Date
	Source        string
	Earmark       *string
	Remark        *string
	CreatedBy     *string
}

type CreateLeaveGrantRow struct {
	ID            string
	EmployeeID    string
	AmountDays    int32
	GrantedAt     time.Time
	EffectiveFrom pgtype.Date
	ExpiresAt     pgtype.Date
	Source        string
	Earmark       *string
	Remark        *string
	ConsumedDays  int32
	PendingDays   int32
	CreatedBy     *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// E6 leave-grant ledger queries (F6.1 / SWP-LG-* / SWP-LC-*). One lot per
// leave_grants row; remaining_days = amount_days - consumed_days - pending_days is a
// DERIVED domain method (not a column). FIFO allocation orders by soonest expires_at,
// then granted_at, then id. Dates come back as pgtype.Date (repo converts).
// HR POST /leave-grants — inserts one lot. id allocated by column DEFAULT when omitted.
func (q *Queries) CreateLeaveGrant(ctx context.Context, arg CreateLeaveGrantParams) (CreateLeaveGrantRow, error) {
	row := q.db.QueryRow(ctx, createLeaveGrant,
		arg.EmployeeID,
		arg.AmountDays,
		arg.EffectiveFrom,
		arg.ExpiresAt,
		arg.Source,
		arg.Earmark,
		arg.Remark,
		arg.CreatedBy,
	)
	var i CreateLeaveGrantRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.AmountDays,
		&i.GrantedAt,
		&i.EffectiveFrom,
		&i.ExpiresAt,
		&i.Source,
		&i.Earmark,
		&i.Remark,
		&i.ConsumedDays,
		&i.PendingDays,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLeaveGrantWithID = `-- name: CreateLeaveGrantWithID :one
INSERT INTO leave_grants (
    id, employee_id, amount_days, granted_at, effective_from, expires_at,
    source, earmark, remark, consumed_days, pending_days, created_by
) VALUES (
    $1,
    $2,
    $3,
    now(),
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
ON CONFLICT (id) DO NOTHING
RETURNING id, employee_id, amount_days, granted_at, effective_from, expires_at,
          source, earmark, remark, consumed_days, pending_days, created_by,
          created_at, updated_at
`

type CreateLeaveGrantWithIDParams struct {
	ID            string
	EmployeeID    string
	AmountDays    int32
	EffectiveFrom pgtype.Date
	ExpiresAt     pgtype.Date
	Source        string
	Earmark       *string
	Remark        *string
	ConsumedDays  int32
	PendingDays   int32
	CreatedBy     *string
}

type CreateLeaveGrantWithIDRow struct {
	ID            string
	EmployeeID    string
	AmountDays    int32
	GrantedAt     time.Time
	EffectiveFrom pgtype.Date
	ExpiresAt     pgtype.Date
	Source        string
	Earmark       *string
	Remark        *string
	ConsumedDays  int32
	PendingDays   int32
	CreatedBy     *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// Seed / migration-repair variant that supplies an explicit id.
func (q *Queries) CreateLeaveGrantWithID(ctx context.Context, arg CreateLeaveGrantWithIDParams) (CreateLeaveGrantWithIDRow, error) {
	row := q.db.QueryRow(ctx, createLeaveGrantWithID,
		arg.ID,
		arg.EmployeeID,
		arg.AmountDays,
		arg.EffectiveFrom,
		arg.ExpiresAt,
		arg.Source,
		arg.Earmark,
		arg.Remark,
		arg.ConsumedDays,
		arg.PendingDays,
		arg.CreatedBy,
	)
	var i CreateLeaveGrantWithIDRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.AmountDays,
		&i.GrantedAt,
		&i.EffectiveFrom,
		&i.ExpiresAt,
		&i.Source,
		&i.Earmark,
		&i.Remark,
		&i.ConsumedDays,
		&i.PendingDays,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConsumptionsForRequest = `-- name: DeleteConsumptionsForRequest :exec
DELETE FROM leave_consumptions WHERE leave_request_id = $1
`

// Reversal: drop the request's consumption rows after reversing each lot's consumed.
func (q *Queries) DeleteConsumptionsForRequest(ctx context.Context, leaveRequestID string) error {
	_, err := q.db.Exec(ctx, deleteConsumptionsForRequest, leaveRequestID)
	return err
}

const expireLeaveLots = `-- name: ExpireLeaveLots :many
SELECT lg.id, lg.employee_id, lg.expires_at, lg.pending_days
FROM leave_grants lg
WHERE lg.deleted_at IS NULL
  AND lg.expires_at < $1::date
  AND lg.pending_days > 0
ORDER BY lg.expires_at ASC, lg.id ASC
LIMIT $2
FOR UPDATE
`

type ExpireLeaveLotsParams struct {
	Today pgtype.Date
	Lim   int32
}

type ExpireLeaveLotsRow struct {
	ID          string
	EmployeeID  string
	ExpiresAt   pgtype.Date
	PendingDays int32
}

// Expiry sweep: find lots whose expires_at < today that still hold pending_days
// (dangling reservations on an expired lot) so the sweep can release them, and report
// the lot for the audit/zeroing. We do NOT mutate amount/consumed — remaining is
// DERIVED and already 0 for an inactive lot (now >= expires_at) at the read boundary.
// We DO zero any leftover pending_days (releasing dangling reservations). FOR UPDATE
// locks the batch.
func (q *Queries) ExpireLeaveLots(ctx context.Context, arg ExpireLeaveLotsParams) ([]ExpireLeaveLotsRow, error) {
	rows, err := q.db.Query(ctx, expireLeaveLots, arg.Today, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpireLeaveLotsRow{}
	for rows.Next() {
		var i ExpireLeaveLotsRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.ExpiresAt,
			&i.PendingDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveLotsForAllocation = `-- name: GetActiveLotsForAllocation :many
SELECT lg.id, lg.employee_id, lg.amount_days, lg.granted_at, lg.effective_from,
       lg.expires_at, lg.source, lg.earmark, lg.remark, lg.consumed_days,
       lg.pending_days, lg.created_by, lg.created_at, lg.updated_at
FROM leave_grants lg
WHERE lg.employee_id = $1
  AND lg.deleted_at IS NULL
  AND lg.expires_at > $2::date
  AND lg.effective_from <= $2::date
  AND (($3::text = '__null' AND lg.earmark IS NULL)
       OR ($3::text <> '__null' AND lg.earmark = $3::text))
ORDER BY lg.expires_at ASC, lg.granted_at ASC, lg.id ASC
FOR UPDATE
`

type GetActiveLotsForAllocationParams struct {
	EmployeeID   string
	NowDate      pgtype.Date
	EarmarkMatch string
}

type GetActiveLotsForAllocationRow struct {
	ID            string
	EmployeeID    string
	AmountDays    int32
	GrantedAt     time.Time
	EffectiveFrom pgtype.Date
	ExpiresAt     pgtype.Date
	Source        string
	Earmark       *string
	Remark        *string
	ConsumedDays  int32
	PendingDays   int32
	CreatedBy     *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// FIFO allocation source. Returns the employee's ACTIVE lots (now < expires_at,
// effective_from <= now) matching the request's earmark: ordinary requests draw ONLY
// unearmarked lots (earmark_match='__null'); an earmarked request draws ONLY lots with
// the matching earmark (LQ-10 isolation). Ordered FIFO (expires_at, granted_at, id).
// FOR UPDATE locks the lots for the reserve/commit/release tx.
func (q *Queries) GetActiveLotsForAllocation(ctx context.Context, arg GetActiveLotsForAllocationParams) ([]GetActiveLotsForAllocationRow, error) {
	rows, err := q.db.Query(ctx, getActiveLotsForAllocation, arg.EmployeeID, arg.NowDate, arg.EarmarkMatch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveLotsForAllocationRow{}
	for rows.Next() {
		var i GetActiveLotsForAllocationRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.AmountDays,
			&i.GrantedAt,
			&i.EffectiveFrom,
			&i.ExpiresAt,
			&i.Source,
			&i.Earmark,
			&i.Remark,
			&i.ConsumedDays,
			&i.PendingDays,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLeaveGrant = `-- name: GetLeaveGrant :one
SELECT lg.id, lg.employee_id, lg.amount_days, lg.granted_at, lg.effective_from,
       lg.expires_at, lg.source, lg.earmark, lg.remark, lg.consumed_days,
       lg.pending_days, lg.created_by, lg.created_at, lg.updated_at,
       e.full_name AS employee_name
FROM leave_grants lg
LEFT JOIN employees e ON e.id = lg.employee_id
WHERE lg.id = $1
  AND lg.deleted_at IS NULL
`

type GetLeaveGrantRow struct {
	ID            string
	EmployeeID    string
	AmountDays    int32
	GrantedAt     time.Time
	EffectiveFrom pgtype.Date
	ExpiresAt     pgtype.Date
	Source        string
	Earmark       *string
	Remark        *string
	ConsumedDays  int32
	PendingDays   int32
	CreatedBy     *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	EmployeeName  *string
}

// Single lot with denormalized employee_name.
func (q *Queries) GetLeaveGrant(ctx context.Context, id string) (GetLeaveGrantRow, error) {
	row := q.db.QueryRow(ctx, getLeaveGrant, id)
	var i GetLeaveGrantRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.AmountDays,
		&i.GrantedAt,
		&i.EffectiveFrom,
		&i.ExpiresAt,
		&i.Source,
		&i.Earmark,
		&i.Remark,
		&i.ConsumedDays,
		&i.PendingDays,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmployeeName,
	)
	return i, err
}

const getLeaveGrantForUpdate = `-- name: GetLeaveGrantForUpdate :one
SELECT lg.id, lg.employee_id, lg.amount_days, lg.granted_at, lg.effective_from,
       lg.expires_at, lg.source, lg.earmark, lg.remark, lg.consumed_days,
       lg.pending_days, lg.created_by, lg.created_at, lg.updated_at
FROM leave_grants lg
WHERE lg.id = $1
  AND lg.deleted_at IS NULL
FOR UPDATE
`

type GetLeaveGrantForUpdateRow struct {
	ID            string
	EmployeeID    string
	AmountDays    int32
	GrantedAt     time.Time
	EffectiveFrom pgtype.Date
	ExpiresAt     pgtype.Date
	Source        string
	Earmark       *string
	Remark        *string
	ConsumedDays  int32
	PendingDays   int32
	CreatedBy     *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// Row-lock for PATCH (adjust amount/expires_at/earmark).
func (q *Queries) GetLeaveGrantForUpdate(ctx context.Context, id string) (GetLeaveGrantForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getLeaveGrantForUpdate, id)
	var i GetLeaveGrantForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.AmountDays,
		&i.GrantedAt,
		&i.EffectiveFrom,
		&i.ExpiresAt,
		&i.Source,
		&i.Earmark,
		&i.Remark,
		&i.ConsumedDays,
		&i.PendingDays,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConsumptionsForGrant = `-- name: ListConsumptionsForGrant :many
SELECT lc.id, lc.leave_request_id, lc.grant_id, lc.days, lc.created_at
FROM leave_consumptions lc
WHERE lc.grant_id = $1
ORDER BY lc.created_at ASC, lc.id ASC
`

// GET /leave-grants/{id} consumptions[] embed.
func (q *Queries) ListConsumptionsForGrant(ctx context.Context, grantID string) ([]LeaveConsumption, error) {
	rows, err := q.db.Query(ctx, listConsumptionsForGrant, grantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeaveConsumption{}
	for rows.Next() {
		var i LeaveConsumption
		if err := rows.Scan(
			&i.ID,
			&i.LeaveRequestID,
			&i.GrantID,
			&i.Days,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConsumptionsForRequest = `-- name: ListConsumptionsForRequest :many
SELECT lc.id, lc.leave_request_id, lc.grant_id, lc.days, lc.created_at
FROM leave_consumptions lc
WHERE lc.leave_request_id = $1
ORDER BY lc.created_at ASC, lc.id ASC
`

// Reversal source (cancel/shorten): the exact lots a request drew, to reverse.
func (q *Queries) ListConsumptionsForRequest(ctx context.Context, leaveRequestID string) ([]LeaveConsumption, error) {
	rows, err := q.db.Query(ctx, listConsumptionsForRequest, leaveRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeaveConsumption{}
	for rows.Next() {
		var i LeaveConsumption
		if err := rows.Scan(
			&i.ID,
			&i.LeaveRequestID,
			&i.GrantID,
			&i.Days,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeaveBalances = `-- name: ListLeaveBalances :many
SELECT e.id                                                         AS employee_id,
       e.full_name                                                  AS full_name,
       e.nik                                                        AS nik,
       e.nip                                                        AS nip,
       COALESCE(SUM(lg.amount_days)   FILTER (WHERE lg.earmark IS NULL), 0)::bigint AS pool_total,
       COALESCE(SUM(lg.consumed_days) FILTER (WHERE lg.earmark IS NULL), 0)::bigint AS pool_consumed,
       COALESCE(SUM(lg.pending_days)  FILTER (WHERE lg.earmark IS NULL), 0)::bigint AS pool_pending,
       COALESCE(SUM(lg.amount_days - lg.consumed_days - lg.pending_days)
                FILTER (WHERE lg.earmark IS NULL), 0)::bigint        AS pool_remaining,
       COALESCE(SUM(lg.amount_days - lg.consumed_days - lg.pending_days)
                FILTER (WHERE lg.earmark IS NOT NULL), 0)::bigint    AS earmarked_remaining,
       MIN(lg.expires_at) FILTER (
           WHERE (lg.amount_days - lg.consumed_days - lg.pending_days) > 0
       )::date                                                       AS next_expiry,
       COUNT(*)::bigint                                              AS lot_count
FROM leave_grants lg
JOIN employees e ON e.id = lg.employee_id AND e.deleted_at IS NULL
WHERE lg.deleted_at IS NULL
  AND lg.expires_at > $1::date
  AND (
        $2::text IS NULL
        OR e.full_name ILIKE '%' || $2::text || '%'
        OR e.nik       ILIKE '%' || $2::text || '%'
        OR e.nip       ILIKE '%' || $2::text || '%'
      )
  AND (
        $3::text IS NULL
        OR (e.full_name, e.id) > ($3::text, $4::text)
      )
GROUP BY e.id, e.full_name, e.nik, e.nip
ORDER BY e.full_name ASC, e.id ASC
LIMIT $5
`

type ListLeaveBalancesParams struct {
	NowDate        pgtype.Date
	Q              *string
	CursorFullName *string
	CursorID       *string
	Lim            int32
}

type ListLeaveBalancesRow struct {
	EmployeeID         string
	FullName           string
	Nik                string
	Nip                string
	PoolTotal          int64
	PoolConsumed       int64
	PoolPending        int64
	PoolRemaining      int64
	EarmarkedRemaining int64
	NextExpiry         pgtype.Date
	LotCount           int64
}

// The /leave/quotas screen: ONE ROW PER EMPLOYEE, aggregating ALL of the employee's
// ACTIVE lots (now < expires_at AND deleted_at IS NULL). JOINs employees for the
// name/nik/nip display + the q ILIKE filter (mirrors people/employees.sql ListEmployees:
// ILIKE over full_name/nik/nip ONLY). An employee appears iff they hold >= 1 ACTIVE lot
// regardless of remaining (an employee whose lots are all consumed still lists as long
// as a lot is non-expired); an employee with ONLY expired lots is excluded by the
// expires_at > now_date predicate. Pool fields aggregate unearmarked lots (earmark IS
// NULL); earmarked_remaining sums remaining across earmarked lots. next_expiry is the
// MIN(expires_at) over active lots that still have remaining > 0. Keyset cursor on
// (full_name, employee_id); deterministic ORDER BY full_name ASC, employee_id ASC.
func (q *Queries) ListLeaveBalances(ctx context.Context, arg ListLeaveBalancesParams) ([]ListLeaveBalancesRow, error) {
	rows, err := q.db.Query(ctx, listLeaveBalances,
		arg.NowDate,
		arg.Q,
		arg.CursorFullName,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLeaveBalancesRow{}
	for rows.Next() {
		var i ListLeaveBalancesRow
		if err := rows.Scan(
			&i.EmployeeID,
			&i.FullName,
			&i.Nik,
			&i.Nip,
			&i.PoolTotal,
			&i.PoolConsumed,
			&i.PoolPending,
			&i.PoolRemaining,
			&i.EarmarkedRemaining,
			&i.NextExpiry,
			&i.LotCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeaveGrants = `-- name: ListLeaveGrants :many
SELECT lg.id, lg.employee_id, lg.amount_days, lg.granted_at, lg.effective_from,
       lg.expires_at, lg.source, lg.earmark, lg.remark, lg.consumed_days,
       lg.pending_days, lg.created_by, lg.created_at, lg.updated_at,
       e.full_name AS employee_name
FROM leave_grants lg
LEFT JOIN employees e ON e.id = lg.employee_id
WHERE lg.deleted_at IS NULL
  AND ($1::text IS NULL OR lg.employee_id = $1::text)
  AND ($2::text     IS NULL OR lg.source      = $2::text)
  AND ($3::text IS NULL
       OR ($3::text = '__null' AND lg.earmark IS NULL)
       OR ($3::text <> '__null' AND lg.earmark = $3::text))
  AND ($4::bool IS TRUE OR lg.expires_at > $5::date)
  AND ($6::text IS NULL OR EXISTS (
        SELECT 1 FROM placements p
        WHERE p.employee_id = lg.employee_id
          AND p.client_company_id = $6::text
          AND p.deleted_at IS NULL))
  AND ($7::date IS NULL OR
       (lg.expires_at, lg.id) > ($7::date, $8::text))
ORDER BY lg.expires_at ASC, lg.id ASC
LIMIT $9
`

type ListLeaveGrantsParams struct {
	EmployeeID      *string
	Source          *string
	EarmarkFilter   *string
	IncludeExpired  *bool
	NowDate         pgtype.Date
	CompanyID       *string
	CursorExpiresAt pgtype.Date
	CursorID        *string
	Lim             int32
}

type ListLeaveGrantsRow struct {
	ID            string
	EmployeeID    string
	AmountDays    int32
	GrantedAt     time.Time
	EffectiveFrom pgtype.Date
	ExpiresAt     pgtype.Date
	Source        string
	Earmark       *string
	Remark        *string
	ConsumedDays  int32
	PendingDays   int32
	CreatedBy     *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	EmployeeName  *string
}

// The ledger. Keyset cursor (expires_at ASC, id) — FIFO-aligned order. Filters
// (narg): employee_id, earmark ('__null' sentinel → unearmarked only), source,
// include_expired (default: active only), company_id (via covering placement).
func (q *Queries) ListLeaveGrants(ctx context.Context, arg ListLeaveGrantsParams) ([]ListLeaveGrantsRow, error) {
	rows, err := q.db.Query(ctx, listLeaveGrants,
		arg.EmployeeID,
		arg.Source,
		arg.EarmarkFilter,
		arg.IncludeExpired,
		arg.NowDate,
		arg.CompanyID,
		arg.CursorExpiresAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLeaveGrantsRow{}
	for rows.Next() {
		var i ListLeaveGrantsRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.AmountDays,
			&i.GrantedAt,
			&i.EffectiveFrom,
			&i.ExpiresAt,
			&i.Source,
			&i.Earmark,
			&i.Remark,
			&i.ConsumedDays,
			&i.PendingDays,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmployeeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchLeaveGrant = `-- name: PatchLeaveGrant :one
UPDATE leave_grants
SET amount_days = COALESCE($1, amount_days),
    expires_at  = COALESCE($2, expires_at),
    earmark     = CASE WHEN $3::bool THEN $4 ELSE earmark END,
    remark      = $5,
    updated_at  = now()
WHERE id = $6
  AND deleted_at IS NULL
RETURNING id, employee_id, amount_days, granted_at, effective_from, expires_at,
          source, earmark, remark, consumed_days, pending_days, created_by,
          created_at, updated_at
`

type PatchLeaveGrantParams struct {
	AmountDays *int32
	ExpiresAt  pgtype.Date
	SetEarmark bool
	Earmark    *string
	Remark     *string
	ID         string
}

type PatchLeaveGrantRow struct {
	ID            string
	EmployeeID    string
	AmountDays    int32
	GrantedAt     time.Time
	EffectiveFrom pgtype.Date
	ExpiresAt     pgtype.Date
	Source        string
	Earmark       *string
	Remark        *string
	ConsumedDays  int32
	PendingDays   int32
	CreatedBy     *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// HR PATCH /leave-grants/{id}: adjust amount_days/expires_at/earmark (+ remark). The
// service guards amount_days >= consumed_days+pending_days (422) before calling. nargs
// left NULL keep the current value (COALESCE).
func (q *Queries) PatchLeaveGrant(ctx context.Context, arg PatchLeaveGrantParams) (PatchLeaveGrantRow, error) {
	row := q.db.QueryRow(ctx, patchLeaveGrant,
		arg.AmountDays,
		arg.ExpiresAt,
		arg.SetEarmark,
		arg.Earmark,
		arg.Remark,
		arg.ID,
	)
	var i PatchLeaveGrantRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.AmountDays,
		&i.GrantedAt,
		&i.EffectiveFrom,
		&i.ExpiresAt,
		&i.Source,
		&i.Earmark,
		&i.Remark,
		&i.ConsumedDays,
		&i.PendingDays,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const releasePending = `-- name: ReleasePending :one
UPDATE leave_grants
SET pending_days = GREATEST(pending_days - $1, 0),
    updated_at   = now()
WHERE id = $2
RETURNING id, employee_id, amount_days, granted_at, effective_from, expires_at,
          source, earmark, remark, consumed_days, pending_days, created_by,
          created_at, updated_at
`

type ReleasePendingParams struct {
	Days int32
	ID   string
}

type ReleasePendingRow struct {
	ID            string
	EmployeeID    string
	AmountDays    int32
	GrantedAt     time.Time
	EffectiveFrom pgtype.Date
	ExpiresAt     pgtype.Date
	Source        string
	Earmark       *string
	Remark        *string
	ConsumedDays  int32
	PendingDays   int32
	CreatedBy     *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// Release pending_days at REJECT/CANCEL (a still-pending request never consumed).
func (q *Queries) ReleasePending(ctx context.Context, arg ReleasePendingParams) (ReleasePendingRow, error) {
	row := q.db.QueryRow(ctx, releasePending, arg.Days, arg.ID)
	var i ReleasePendingRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.AmountDays,
		&i.GrantedAt,
		&i.EffectiveFrom,
		&i.ExpiresAt,
		&i.Source,
		&i.Earmark,
		&i.Remark,
		&i.ConsumedDays,
		&i.PendingDays,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reservePending = `-- name: ReservePending :one
UPDATE leave_grants
SET pending_days = pending_days + $1,
    updated_at   = now()
WHERE id = $2
RETURNING id, employee_id, amount_days, granted_at, effective_from, expires_at,
          source, earmark, remark, consumed_days, pending_days, created_by,
          created_at, updated_at
`

type ReservePendingParams struct {
	Days int32
	ID   string
}

type ReservePendingRow struct {
	ID            string
	EmployeeID    string
	AmountDays    int32
	GrantedAt     time.Time
	EffectiveFrom pgtype.Date
	ExpiresAt     pgtype.Date
	Source        string
	Earmark       *string
	Remark        *string
	ConsumedDays  int32
	PendingDays   int32
	CreatedBy     *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// Move days into pending_days at SUBMIT (FIFO reserve). Never drives a lot negative:
// the service caps the delta at the lot's remaining before calling.
func (q *Queries) ReservePending(ctx context.Context, arg ReservePendingParams) (ReservePendingRow, error) {
	row := q.db.QueryRow(ctx, reservePending, arg.Days, arg.ID)
	var i ReservePendingRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.AmountDays,
		&i.GrantedAt,
		&i.EffectiveFrom,
		&i.ExpiresAt,
		&i.Source,
		&i.Earmark,
		&i.Remark,
		&i.ConsumedDays,
		&i.PendingDays,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reverseConsumption = `-- name: ReverseConsumption :one
UPDATE leave_grants
SET consumed_days = GREATEST(consumed_days - $1, 0),
    updated_at    = now()
WHERE id = $2
RETURNING id, employee_id, amount_days, granted_at, effective_from, expires_at,
          source, earmark, remark, consumed_days, pending_days, created_by,
          created_at, updated_at
`

type ReverseConsumptionParams struct {
	Days int32
	ID   string
}

type ReverseConsumptionRow struct {
	ID            string
	EmployeeID    string
	AmountDays    int32
	GrantedAt     time.Time
	EffectiveFrom pgtype.Date
	ExpiresAt     pgtype.Date
	Source        string
	Earmark       *string
	Remark        *string
	ConsumedDays  int32
	PendingDays   int32
	CreatedBy     *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// Reverse committed consumed_days at CANCEL-APPROVED / SHORTEN (paired with deleting
// the leave_consumptions rows). Returns days to the lot.
func (q *Queries) ReverseConsumption(ctx context.Context, arg ReverseConsumptionParams) (ReverseConsumptionRow, error) {
	row := q.db.QueryRow(ctx, reverseConsumption, arg.Days, arg.ID)
	var i ReverseConsumptionRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.AmountDays,
		&i.GrantedAt,
		&i.EffectiveFrom,
		&i.ExpiresAt,
		&i.Source,
		&i.Earmark,
		&i.Remark,
		&i.ConsumedDays,
		&i.PendingDays,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sumActiveBalanceByEarmark = `-- name: SumActiveBalanceByEarmark :many
SELECT lg.earmark,
       COALESCE(SUM(lg.amount_days - lg.consumed_days - lg.pending_days), 0)::bigint AS remaining_days,
       COALESCE(SUM(lg.pending_days), 0)::bigint AS pending_days,
       MIN(lg.expires_at)::date AS next_expiry
FROM leave_grants lg
WHERE lg.employee_id = $1
  AND lg.deleted_at IS NULL
  AND lg.expires_at > $2::date
GROUP BY lg.earmark
`

type SumActiveBalanceByEarmarkParams struct {
	EmployeeID string
	NowDate    pgtype.Date
}

type SumActiveBalanceByEarmarkRow struct {
	Earmark       *string
	RemainingDays int64
	PendingDays   int64
	NextExpiry    pgtype.Date
}

// Computed balance over ACTIVE lots (now < expires_at), grouped by earmark. The
// unearmarked group (earmark IS NULL) is the flat pool; each non-null earmark is one
// per-purpose line. Returns Σ(amount-consumed-pending) and the soonest expiry per group.
func (q *Queries) SumActiveBalanceByEarmark(ctx context.Context, arg SumActiveBalanceByEarmarkParams) ([]SumActiveBalanceByEarmarkRow, error) {
	rows, err := q.db.Query(ctx, sumActiveBalanceByEarmark, arg.EmployeeID, arg.NowDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumActiveBalanceByEarmarkRow{}
	for rows.Next() {
		var i SumActiveBalanceByEarmarkRow
		if err := rows.Scan(
			&i.Earmark,
			&i.RemainingDays,
			&i.PendingDays,
			&i.NextExpiry,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const zeroLotPending = `-- name: ZeroLotPending :one
UPDATE leave_grants
SET pending_days = 0,
    updated_at   = now()
WHERE id = $1
RETURNING id, employee_id, amount_days, granted_at, effective_from, expires_at,
          source, earmark, remark, consumed_days, pending_days, created_by,
          created_at, updated_at
`

type ZeroLotPendingRow struct {
	ID            string
	EmployeeID    string
	AmountDays    int32
	GrantedAt     time.Time
	EffectiveFrom pgtype.Date
	ExpiresAt     pgtype.Date
	Source        string
	Earmark       *string
	Remark        *string
	ConsumedDays  int32
	PendingDays   int32
	CreatedBy     *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// Expiry sweep: release dangling pending on an expired lot.
func (q *Queries) ZeroLotPending(ctx context.Context, id string) (ZeroLotPendingRow, error) {
	row := q.db.QueryRow(ctx, zeroLotPending, id)
	var i ZeroLotPendingRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.AmountDays,
		&i.GrantedAt,
		&i.EffectiveFrom,
		&i.ExpiresAt,
		&i.Source,
		&i.Earmark,
		&i.Remark,
		&i.ConsumedDays,
		&i.PendingDays,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
