// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leave_entitlements.sql

package sqlcgen

import (
	"context"
	"time"
)

const deactivateEmployeeEntitlement = `-- name: DeactivateEmployeeEntitlement :one
UPDATE employee_leave_entitlements
SET active      = false,
    assigned_by = $1,
    updated_at  = now()
WHERE employee_id   = $2
  AND leave_type_id = $3
  AND active
  AND deleted_at IS NULL
RETURNING id, employee_id, leave_type_id, entitled_days, active, note, assigned_by,
          created_at, updated_at
`

type DeactivateEmployeeEntitlementParams struct {
	AssignedBy  *string
	EmployeeID  string
	LeaveTypeID string
}

type DeactivateEmployeeEntitlementRow struct {
	ID           string
	EmployeeID   string
	LeaveTypeID  string
	EntitledDays *int32
	Active       bool
	Note         string
	AssignedBy   *string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

// Remove a type from an employee (DELETE) — soft on/off, keeps the row + history.
func (q *Queries) DeactivateEmployeeEntitlement(ctx context.Context, arg DeactivateEmployeeEntitlementParams) (DeactivateEmployeeEntitlementRow, error) {
	row := q.db.QueryRow(ctx, deactivateEmployeeEntitlement, arg.AssignedBy, arg.EmployeeID, arg.LeaveTypeID)
	var i DeactivateEmployeeEntitlementRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.LeaveTypeID,
		&i.EntitledDays,
		&i.Active,
		&i.Note,
		&i.AssignedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmployeeEntitlement = `-- name: GetEmployeeEntitlement :one

SELECT id, employee_id, leave_type_id, entitled_days, active, note, assigned_by,
       created_at, updated_at
FROM employee_leave_entitlements
WHERE employee_id   = $1
  AND leave_type_id = $2
  AND active
  AND deleted_at IS NULL
`

type GetEmployeeEntitlementParams struct {
	EmployeeID  string
	LeaveTypeID string
}

type GetEmployeeEntitlementRow struct {
	ID           string
	EmployeeID   string
	LeaveTypeID  string
	EntitledDays *int32
	Active       bool
	Note         string
	AssignedBy   *string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

// E6 HR-assigned leave entitlements (PRD leave-entitlement-assignment, 2026-06-15).
// The base policy: which leave types an employee is entitled to + the per-period
// quota. The QuotaMeter reads GetEmployeeEntitlement to auto-open windows (ELE-2);
// HR CRUDs assignments via the list/upsert/update/deactivate queries.
// The active entitlement for one (employee, leave_type) — the entitlementFor source.
// Returns no rows when the type is not assigned (caller falls back to cap_value).
func (q *Queries) GetEmployeeEntitlement(ctx context.Context, arg GetEmployeeEntitlementParams) (GetEmployeeEntitlementRow, error) {
	row := q.db.QueryRow(ctx, getEmployeeEntitlement, arg.EmployeeID, arg.LeaveTypeID)
	var i GetEmployeeEntitlementRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.LeaveTypeID,
		&i.EntitledDays,
		&i.Active,
		&i.Note,
		&i.AssignedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEmployeeEntitlements = `-- name: ListEmployeeEntitlements :many
SELECT ele.id, ele.employee_id, ele.leave_type_id, ele.entitled_days, ele.active,
       ele.note, ele.assigned_by, ele.created_at, ele.updated_at,
       lt.code, lt.name, lt.cap_basis, lt.cap_value, lt.cap_unit, lt.paid,
       lt.requires_document, lt.color, lt.applies_to, lt.common
FROM employee_leave_entitlements ele
JOIN leave_types lt ON lt.id = ele.leave_type_id AND lt.deleted_at IS NULL
WHERE ele.employee_id = $1
  AND ele.active
  AND ele.deleted_at IS NULL
ORDER BY lt.code
`

type ListEmployeeEntitlementsRow struct {
	ID               string
	EmployeeID       string
	LeaveTypeID      string
	EntitledDays     *int32
	Active           bool
	Note             string
	AssignedBy       *string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	Code             string
	Name             string
	CapBasis         string
	CapValue         *int32
	CapUnit          string
	Paid             bool
	RequiresDocument bool
	Color            string
	AppliesTo        string
	Common           bool
}

// An employee's active assignments + the leave-type display/cap metadata (HR "Hak
// Cuti" grid + the agent picker scope). Only active, non-deleted rows whose type is
// still in the catalog. Ordered by type code for a stable grid.
func (q *Queries) ListEmployeeEntitlements(ctx context.Context, employeeID string) ([]ListEmployeeEntitlementsRow, error) {
	rows, err := q.db.Query(ctx, listEmployeeEntitlements, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeeEntitlementsRow{}
	for rows.Next() {
		var i ListEmployeeEntitlementsRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.LeaveTypeID,
			&i.EntitledDays,
			&i.Active,
			&i.Note,
			&i.AssignedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Code,
			&i.Name,
			&i.CapBasis,
			&i.CapValue,
			&i.CapUnit,
			&i.Paid,
			&i.RequiresDocument,
			&i.Color,
			&i.AppliesTo,
			&i.Common,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmployeeEntitlement = `-- name: UpdateEmployeeEntitlement :one
UPDATE employee_leave_entitlements
SET entitled_days = $1,
    active        = true,
    note          = COALESCE($2, note),
    assigned_by   = $3,
    updated_at    = now()
WHERE employee_id   = $4
  AND leave_type_id = $5
  AND deleted_at IS NULL
RETURNING id, employee_id, leave_type_id, entitled_days, active, note, assigned_by,
          created_at, updated_at
`

type UpdateEmployeeEntitlementParams struct {
	EntitledDays *int32
	Note         *string
	AssignedBy   *string
	EmployeeID   string
	LeaveTypeID  string
}

type UpdateEmployeeEntitlementRow struct {
	ID           string
	EmployeeID   string
	LeaveTypeID  string
	EntitledDays *int32
	Active       bool
	Note         string
	AssignedBy   *string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

// Edit the base entitled_days / reactivate (PATCH). Targets the active-or-inactive
// live row for (employee, type); reactivates if it was removed (ELE-4/ELE-6).
func (q *Queries) UpdateEmployeeEntitlement(ctx context.Context, arg UpdateEmployeeEntitlementParams) (UpdateEmployeeEntitlementRow, error) {
	row := q.db.QueryRow(ctx, updateEmployeeEntitlement,
		arg.EntitledDays,
		arg.Note,
		arg.AssignedBy,
		arg.EmployeeID,
		arg.LeaveTypeID,
	)
	var i UpdateEmployeeEntitlementRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.LeaveTypeID,
		&i.EntitledDays,
		&i.Active,
		&i.Note,
		&i.AssignedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertEmployeeEntitlement = `-- name: UpsertEmployeeEntitlement :one
INSERT INTO employee_leave_entitlements
    (id, employee_id, leave_type_id, entitled_days, active, note, assigned_by)
VALUES (
    'SWP-ELE-' || swp_next_id('ELE'),
    $1,
    $2,
    $3,
    true,
    $4,
    $5
)
ON CONFLICT (employee_id, leave_type_id) WHERE deleted_at IS NULL
DO UPDATE SET
    entitled_days = EXCLUDED.entitled_days,
    active        = true,
    note          = EXCLUDED.note,
    assigned_by   = EXCLUDED.assigned_by,
    updated_at    = now()
RETURNING id, employee_id, leave_type_id, entitled_days, active, note, assigned_by,
          created_at, updated_at
`

type UpsertEmployeeEntitlementParams struct {
	EmployeeID   string
	LeaveTypeID  string
	EntitledDays *int32
	Note         string
	AssignedBy   *string
}

type UpsertEmployeeEntitlementRow struct {
	ID           string
	EmployeeID   string
	LeaveTypeID  string
	EntitledDays *int32
	Active       bool
	Note         string
	AssignedBy   *string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

// Assign a type to an employee (POST). Inserts a fresh SWP-ELE row, or reactivates
// + re-quotas an existing (employee, type) assignment (ELE-6 add/reactivate).
func (q *Queries) UpsertEmployeeEntitlement(ctx context.Context, arg UpsertEmployeeEntitlementParams) (UpsertEmployeeEntitlementRow, error) {
	row := q.db.QueryRow(ctx, upsertEmployeeEntitlement,
		arg.EmployeeID,
		arg.LeaveTypeID,
		arg.EntitledDays,
		arg.Note,
		arg.AssignedBy,
	)
	var i UpsertEmployeeEntitlementRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.LeaveTypeID,
		&i.EntitledDays,
		&i.Active,
		&i.Note,
		&i.AssignedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
