// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leave_requests.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkOverlappingLeave = `-- name: CheckOverlappingLeave :one
SELECT EXISTS (
    SELECT 1
    FROM leave_requests lr
    WHERE lr.employee_id = $1
      AND lr.deleted_at IS NULL
      AND lr.status NOT IN ('REJECTED','CANCELLED')
      AND lr.start_date <= $2::date
      AND lr.end_date   >= $3::date
) AS overlaps
`

type CheckOverlappingLeaveParams struct {
	EmployeeID string
	EndDate    pgtype.Date
	StartDate  pgtype.Date
}

// LR-5 OVERLAPPING_LEAVE pre-check: does this employee already hold a live
// (non-REJECTED / non-CANCELLED, non-deleted) leave_request whose [start_date,
// end_date] overlaps the requested range? Two ranges overlap iff
// start <= other.end AND end >= other.start. Returns true when at least one such
// row exists. (F6.2 agent file-a-request — the create-time conflict guard.)
func (q *Queries) CheckOverlappingLeave(ctx context.Context, arg CheckOverlappingLeaveParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkOverlappingLeave, arg.EmployeeID, arg.EndDate, arg.StartDate)
	var overlaps bool
	err := row.Scan(&overlaps)
	return overlaps, err
}

const countPendingLeaveDaysForQuota = `-- name: CountPendingLeaveDaysForQuota :one
SELECT COALESCE(SUM(lr.duration_days), 0)::bigint AS pending_days
FROM leave_requests lr
WHERE lr.employee_id   = $1
  AND lr.leave_type_id = $2
  AND lr.status IN ('PENDING_L1','PENDING_HR')
  AND lr.start_date >= $3::date
  AND lr.start_date <= $4::date
  AND lr.deleted_at IS NULL
`

type CountPendingLeaveDaysForQuotaParams struct {
	EmployeeID  string
	LeaveTypeID string
	PeriodStart pgtype.Date
	PeriodEnd   pgtype.Date
}

// Soft-reservation recompute: sum duration_days of this employee+leave_type's open
// PENDING_L1/PENDING_HR requests in the period (drives quota.pending on read).
func (q *Queries) CountPendingLeaveDaysForQuota(ctx context.Context, arg CountPendingLeaveDaysForQuotaParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingLeaveDaysForQuota,
		arg.EmployeeID,
		arg.LeaveTypeID,
		arg.PeriodStart,
		arg.PeriodEnd,
	)
	var pending_days int64
	err := row.Scan(&pending_days)
	return pending_days, err
}

const createLeaveRequest = `-- name: CreateLeaveRequest :one
INSERT INTO leave_requests (
    employee_id, placement_id, company_id, service_line_id, leave_type_id,
    start_date, end_date, duration_days, reason, notes, status,
    delegate_id, document_file_id, backdated, clock_in_conflict,
    no_leader, assigned_leader_id,
    balance_quota_id, balance_requested_days, balance_remaining_at_check, balance_requires_override,
    created_by
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    $22
)
RETURNING id, employee_id, placement_id, company_id, service_line_id, leave_type_id,
          start_date, end_date, duration_days, reason, notes, status,
          delegate_id, document_file_id, backdated, clock_in_conflict,
          no_leader, assigned_leader_id, balance_quota_id, balance_requested_days,
          balance_remaining_at_check, balance_requires_override, balance_earmark,
          balance_allocation, created_by, created_at, updated_at
`

type CreateLeaveRequestParams struct {
	EmployeeID              string
	PlacementID             *string
	CompanyID               *string
	ServiceLineID           *string
	LeaveTypeID             string
	StartDate               pgtype.Date
	EndDate                 pgtype.Date
	DurationDays            int32
	Reason                  *string
	Notes                   *string
	Status                  string
	DelegateID              *string
	DocumentFileID          *string
	Backdated               bool
	ClockInConflict         bool
	NoLeader                bool
	AssignedLeaderID        *string
	BalanceQuotaID          *string
	BalanceRequestedDays    *int32
	BalanceRemainingAtCheck *int32
	BalanceRequiresOverride *bool
	CreatedBy               *string
}

type CreateLeaveRequestRow struct {
	ID                      string
	EmployeeID              string
	PlacementID             *string
	CompanyID               *string
	ServiceLineID           *string
	LeaveTypeID             string
	StartDate               pgtype.Date
	EndDate                 pgtype.Date
	DurationDays            int32
	Reason                  *string
	Notes                   *string
	Status                  string
	DelegateID              *string
	DocumentFileID          *string
	Backdated               bool
	ClockInConflict         bool
	NoLeader                bool
	AssignedLeaderID        *string
	BalanceQuotaID          *string
	BalanceRequestedDays    *int32
	BalanceRemainingAtCheck *int32
	BalanceRequiresOverride *bool
	BalanceEarmark          *string
	BalanceAllocation       []byte
	CreatedBy               *string
	CreatedAt               time.Time
	UpdatedAt               time.Time
}

// Seed / HR-on-behalf path (FE/web does not create — mobile/agent does). id
// allocated by the column DEFAULT ('SWP-LR-' || swp_next_id('LR')) when omitted.
func (q *Queries) CreateLeaveRequest(ctx context.Context, arg CreateLeaveRequestParams) (CreateLeaveRequestRow, error) {
	row := q.db.QueryRow(ctx, createLeaveRequest,
		arg.EmployeeID,
		arg.PlacementID,
		arg.CompanyID,
		arg.ServiceLineID,
		arg.LeaveTypeID,
		arg.StartDate,
		arg.EndDate,
		arg.DurationDays,
		arg.Reason,
		arg.Notes,
		arg.Status,
		arg.DelegateID,
		arg.DocumentFileID,
		arg.Backdated,
		arg.ClockInConflict,
		arg.NoLeader,
		arg.AssignedLeaderID,
		arg.BalanceQuotaID,
		arg.BalanceRequestedDays,
		arg.BalanceRemainingAtCheck,
		arg.BalanceRequiresOverride,
		arg.CreatedBy,
	)
	var i CreateLeaveRequestRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.PlacementID,
		&i.CompanyID,
		&i.ServiceLineID,
		&i.LeaveTypeID,
		&i.StartDate,
		&i.EndDate,
		&i.DurationDays,
		&i.Reason,
		&i.Notes,
		&i.Status,
		&i.DelegateID,
		&i.DocumentFileID,
		&i.Backdated,
		&i.ClockInConflict,
		&i.NoLeader,
		&i.AssignedLeaderID,
		&i.BalanceQuotaID,
		&i.BalanceRequestedDays,
		&i.BalanceRemainingAtCheck,
		&i.BalanceRequiresOverride,
		&i.BalanceEarmark,
		&i.BalanceAllocation,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLeaveRequestWithID = `-- name: CreateLeaveRequestWithID :one
INSERT INTO leave_requests (
    id, employee_id, placement_id, company_id, service_line_id, leave_type_id,
    start_date, end_date, duration_days, reason, notes, status,
    delegate_id, document_file_id, backdated, clock_in_conflict,
    no_leader, assigned_leader_id,
    balance_quota_id, balance_requested_days, balance_remaining_at_check, balance_requires_override,
    created_by
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    $22,
    $23
)
ON CONFLICT (id) DO NOTHING
RETURNING id, employee_id, placement_id, company_id, service_line_id, leave_type_id,
          start_date, end_date, duration_days, reason, notes, status,
          delegate_id, document_file_id, backdated, clock_in_conflict,
          no_leader, assigned_leader_id, balance_quota_id, balance_requested_days,
          balance_remaining_at_check, balance_requires_override, balance_earmark,
          balance_allocation, created_by, created_at, updated_at
`

type CreateLeaveRequestWithIDParams struct {
	ID                      string
	EmployeeID              string
	PlacementID             *string
	CompanyID               *string
	ServiceLineID           *string
	LeaveTypeID             string
	StartDate               pgtype.Date
	EndDate                 pgtype.Date
	DurationDays            int32
	Reason                  *string
	Notes                   *string
	Status                  string
	DelegateID              *string
	DocumentFileID          *string
	Backdated               bool
	ClockInConflict         bool
	NoLeader                bool
	AssignedLeaderID        *string
	BalanceQuotaID          *string
	BalanceRequestedDays    *int32
	BalanceRemainingAtCheck *int32
	BalanceRequiresOverride *bool
	CreatedBy               *string
}

type CreateLeaveRequestWithIDRow struct {
	ID                      string
	EmployeeID              string
	PlacementID             *string
	CompanyID               *string
	ServiceLineID           *string
	LeaveTypeID             string
	StartDate               pgtype.Date
	EndDate                 pgtype.Date
	DurationDays            int32
	Reason                  *string
	Notes                   *string
	Status                  string
	DelegateID              *string
	DocumentFileID          *string
	Backdated               bool
	ClockInConflict         bool
	NoLeader                bool
	AssignedLeaderID        *string
	BalanceQuotaID          *string
	BalanceRequestedDays    *int32
	BalanceRemainingAtCheck *int32
	BalanceRequiresOverride *bool
	BalanceEarmark          *string
	BalanceAllocation       []byte
	CreatedBy               *string
	CreatedAt               time.Time
	UpdatedAt               time.Time
}

// Seed / test variant that supplies an explicit id (deterministic E2E targets).
func (q *Queries) CreateLeaveRequestWithID(ctx context.Context, arg CreateLeaveRequestWithIDParams) (CreateLeaveRequestWithIDRow, error) {
	row := q.db.QueryRow(ctx, createLeaveRequestWithID,
		arg.ID,
		arg.EmployeeID,
		arg.PlacementID,
		arg.CompanyID,
		arg.ServiceLineID,
		arg.LeaveTypeID,
		arg.StartDate,
		arg.EndDate,
		arg.DurationDays,
		arg.Reason,
		arg.Notes,
		arg.Status,
		arg.DelegateID,
		arg.DocumentFileID,
		arg.Backdated,
		arg.ClockInConflict,
		arg.NoLeader,
		arg.AssignedLeaderID,
		arg.BalanceQuotaID,
		arg.BalanceRequestedDays,
		arg.BalanceRemainingAtCheck,
		arg.BalanceRequiresOverride,
		arg.CreatedBy,
	)
	var i CreateLeaveRequestWithIDRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.PlacementID,
		&i.CompanyID,
		&i.ServiceLineID,
		&i.LeaveTypeID,
		&i.StartDate,
		&i.EndDate,
		&i.DurationDays,
		&i.Reason,
		&i.Notes,
		&i.Status,
		&i.DelegateID,
		&i.DocumentFileID,
		&i.Backdated,
		&i.ClockInConflict,
		&i.NoLeader,
		&i.AssignedLeaderID,
		&i.BalanceQuotaID,
		&i.BalanceRequestedDays,
		&i.BalanceRemainingAtCheck,
		&i.BalanceRequiresOverride,
		&i.BalanceEarmark,
		&i.BalanceAllocation,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLeaveRequest = `-- name: GetLeaveRequest :one
SELECT lr.id, lr.employee_id, lr.placement_id, lr.company_id, lr.service_line_id,
       lr.leave_type_id, lr.start_date, lr.end_date, lr.duration_days,
       lr.reason, lr.notes, lr.status, lr.delegate_id, lr.document_file_id,
       lr.backdated, lr.clock_in_conflict, lr.no_leader, lr.assigned_leader_id,
       lr.balance_quota_id, lr.balance_requested_days, lr.balance_remaining_at_check,
       lr.balance_requires_override, lr.balance_earmark, lr.balance_allocation,
       lr.created_by, lr.created_at, lr.updated_at,
       e.full_name AS employee_name,
       c.name      AS company_name,
       lt.name     AS leave_type_name,
       lt.code     AS leave_type_code
FROM leave_requests lr
LEFT JOIN employees e         ON e.id  = lr.employee_id
LEFT JOIN client_companies c  ON c.id  = lr.company_id
LEFT JOIN leave_types lt      ON lt.id = lr.leave_type_id
WHERE lr.id = $1
  AND lr.deleted_at IS NULL
`

type GetLeaveRequestRow struct {
	ID                      string
	EmployeeID              string
	PlacementID             *string
	CompanyID               *string
	ServiceLineID           *string
	LeaveTypeID             string
	StartDate               pgtype.Date
	EndDate                 pgtype.Date
	DurationDays            int32
	Reason                  *string
	Notes                   *string
	Status                  string
	DelegateID              *string
	DocumentFileID          *string
	Backdated               bool
	ClockInConflict         bool
	NoLeader                bool
	AssignedLeaderID        *string
	BalanceQuotaID          *string
	BalanceRequestedDays    *int32
	BalanceRemainingAtCheck *int32
	BalanceRequiresOverride *bool
	BalanceEarmark          *string
	BalanceAllocation       []byte
	CreatedBy               *string
	CreatedAt               time.Time
	UpdatedAt               time.Time
	EmployeeName            *string
	CompanyName             *string
	LeaveTypeName           *string
	LeaveTypeCode           *string
}

// Single request with denormalized names.
func (q *Queries) GetLeaveRequest(ctx context.Context, id string) (GetLeaveRequestRow, error) {
	row := q.db.QueryRow(ctx, getLeaveRequest, id)
	var i GetLeaveRequestRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.PlacementID,
		&i.CompanyID,
		&i.ServiceLineID,
		&i.LeaveTypeID,
		&i.StartDate,
		&i.EndDate,
		&i.DurationDays,
		&i.Reason,
		&i.Notes,
		&i.Status,
		&i.DelegateID,
		&i.DocumentFileID,
		&i.Backdated,
		&i.ClockInConflict,
		&i.NoLeader,
		&i.AssignedLeaderID,
		&i.BalanceQuotaID,
		&i.BalanceRequestedDays,
		&i.BalanceRemainingAtCheck,
		&i.BalanceRequiresOverride,
		&i.BalanceEarmark,
		&i.BalanceAllocation,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmployeeName,
		&i.CompanyName,
		&i.LeaveTypeName,
		&i.LeaveTypeCode,
	)
	return i, err
}

const getLeaveRequestForUpdate = `-- name: GetLeaveRequestForUpdate :one
SELECT lr.id, lr.employee_id, lr.placement_id, lr.company_id, lr.service_line_id,
       lr.leave_type_id, lr.start_date, lr.end_date, lr.duration_days,
       lr.reason, lr.notes, lr.status, lr.delegate_id, lr.document_file_id,
       lr.backdated, lr.clock_in_conflict, lr.no_leader, lr.assigned_leader_id,
       lr.balance_quota_id, lr.balance_requested_days, lr.balance_remaining_at_check,
       lr.balance_requires_override, lr.balance_earmark, lr.balance_allocation,
       lr.created_by, lr.created_at, lr.updated_at
FROM leave_requests lr
WHERE lr.id = $1
  AND lr.deleted_at IS NULL
FOR UPDATE
`

type GetLeaveRequestForUpdateRow struct {
	ID                      string
	EmployeeID              string
	PlacementID             *string
	CompanyID               *string
	ServiceLineID           *string
	LeaveTypeID             string
	StartDate               pgtype.Date
	EndDate                 pgtype.Date
	DurationDays            int32
	Reason                  *string
	Notes                   *string
	Status                  string
	DelegateID              *string
	DocumentFileID          *string
	Backdated               bool
	ClockInConflict         bool
	NoLeader                bool
	AssignedLeaderID        *string
	BalanceQuotaID          *string
	BalanceRequestedDays    *int32
	BalanceRemainingAtCheck *int32
	BalanceRequiresOverride *bool
	BalanceEarmark          *string
	BalanceAllocation       []byte
	CreatedBy               *string
	CreatedAt               time.Time
	UpdatedAt               time.Time
}

// Row-lock for the state-machine transitions (approve-l1/final/override/reject).
// Omits joins; the service re-reads via GetLeaveRequest for the DTO.
func (q *Queries) GetLeaveRequestForUpdate(ctx context.Context, id string) (GetLeaveRequestForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getLeaveRequestForUpdate, id)
	var i GetLeaveRequestForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.PlacementID,
		&i.CompanyID,
		&i.ServiceLineID,
		&i.LeaveTypeID,
		&i.StartDate,
		&i.EndDate,
		&i.DurationDays,
		&i.Reason,
		&i.Notes,
		&i.Status,
		&i.DelegateID,
		&i.DocumentFileID,
		&i.Backdated,
		&i.ClockInConflict,
		&i.NoLeader,
		&i.AssignedLeaderID,
		&i.BalanceQuotaID,
		&i.BalanceRequestedDays,
		&i.BalanceRemainingAtCheck,
		&i.BalanceRequiresOverride,
		&i.BalanceEarmark,
		&i.BalanceAllocation,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLeaveRequests = `-- name: ListLeaveRequests :many

SELECT lr.id, lr.employee_id, lr.placement_id, lr.company_id, lr.service_line_id,
       lr.leave_type_id, lr.start_date, lr.end_date, lr.duration_days,
       lr.reason, lr.notes, lr.status, lr.delegate_id, lr.document_file_id,
       lr.backdated, lr.clock_in_conflict, lr.no_leader, lr.assigned_leader_id,
       lr.balance_quota_id, lr.balance_requested_days, lr.balance_remaining_at_check,
       lr.balance_requires_override, lr.balance_earmark, lr.balance_allocation,
       lr.created_by, lr.created_at, lr.updated_at,
       e.full_name AS employee_name,
       c.name      AS company_name,
       lt.name     AS leave_type_name,
       lt.code     AS leave_type_code
FROM leave_requests lr
LEFT JOIN employees e         ON e.id  = lr.employee_id
LEFT JOIN client_companies c  ON c.id  = lr.company_id
LEFT JOIN leave_types lt      ON lt.id = lr.leave_type_id
WHERE lr.deleted_at IS NULL
  AND ($1::text   IS NULL OR lr.company_id   = $1::text)
  AND ($2::text       IS NULL OR lr.status       = $2::text)
  AND ($3::text[]  IS NULL OR lr.status       = ANY($3::text[]))
  AND ($4::text  IS NULL OR lr.employee_id  = $4::text)
  AND ($5::text IS NULL OR lr.leave_type_id = $5::text)
  AND ($6::date   IS NULL OR lr.start_date >= $6::date)
  AND ($7::date     IS NULL OR lr.start_date <= $7::date)
  AND ($8::text IS NULL OR (
        e.full_name ILIKE '%' || $8::text || '%'
        OR lr.id     ILIKE '%' || $8::text || '%'
        OR lr.reason ILIKE '%' || $8::text || '%'))
  -- keyset: rows strictly before the cursor (created_at,id) when provided.
  AND ($9::timestamptz IS NULL OR
       (lr.created_at, lr.id) < ($9::timestamptz, $10::text))
ORDER BY lr.created_at DESC, lr.id DESC
LIMIT $11
`

type ListLeaveRequestsParams struct {
	CompanyID       *string
	Status          *string
	StatusIn        []string
	EmployeeID      *string
	LeaveTypeID     *string
	StartFrom       pgtype.Date
	StartTo         pgtype.Date
	Q               *string
	CursorCreatedAt *time.Time
	CursorID        *string
	Lim             int32
}

type ListLeaveRequestsRow struct {
	ID                      string
	EmployeeID              string
	PlacementID             *string
	CompanyID               *string
	ServiceLineID           *string
	LeaveTypeID             string
	StartDate               pgtype.Date
	EndDate                 pgtype.Date
	DurationDays            int32
	Reason                  *string
	Notes                   *string
	Status                  string
	DelegateID              *string
	DocumentFileID          *string
	Backdated               bool
	ClockInConflict         bool
	NoLeader                bool
	AssignedLeaderID        *string
	BalanceQuotaID          *string
	BalanceRequestedDays    *int32
	BalanceRemainingAtCheck *int32
	BalanceRequiresOverride *bool
	BalanceEarmark          *string
	BalanceAllocation       []byte
	CreatedBy               *string
	CreatedAt               time.Time
	UpdatedAt               time.Time
	EmployeeName            *string
	CompanyName             *string
	LeaveTypeName           *string
	LeaveTypeCode           *string
}

// E6 leave-request queries (F6.1/F6.2 / SWP-LR-*). Reads LEFT JOIN employees for
// employee_name, client_companies for company_name, leave_types for
// leave_type_name. Dates come back as pgtype.Date (08-02 repo converts <-> time.Time
// like Phase-5/6). Keyset cursor on (created_at DESC, id) per CONVENTIONS §11.
// Queue / list load. Keyset cursor (created_at,id) DESC. Filters (all optional via
// narg): company_id, status, status__in (text[] → status = ANY), employee_id,
// leave_type_id, start_date >= / <=, q free-text (ILIKE employee name + id + reason).
func (q *Queries) ListLeaveRequests(ctx context.Context, arg ListLeaveRequestsParams) ([]ListLeaveRequestsRow, error) {
	rows, err := q.db.Query(ctx, listLeaveRequests,
		arg.CompanyID,
		arg.Status,
		arg.StatusIn,
		arg.EmployeeID,
		arg.LeaveTypeID,
		arg.StartFrom,
		arg.StartTo,
		arg.Q,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLeaveRequestsRow{}
	for rows.Next() {
		var i ListLeaveRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.PlacementID,
			&i.CompanyID,
			&i.ServiceLineID,
			&i.LeaveTypeID,
			&i.StartDate,
			&i.EndDate,
			&i.DurationDays,
			&i.Reason,
			&i.Notes,
			&i.Status,
			&i.DelegateID,
			&i.DocumentFileID,
			&i.Backdated,
			&i.ClockInConflict,
			&i.NoLeader,
			&i.AssignedLeaderID,
			&i.BalanceQuotaID,
			&i.BalanceRequestedDays,
			&i.BalanceRemainingAtCheck,
			&i.BalanceRequiresOverride,
			&i.BalanceEarmark,
			&i.BalanceAllocation,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmployeeName,
			&i.CompanyName,
			&i.LeaveTypeName,
			&i.LeaveTypeCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLeaveBalanceSnapshot = `-- name: SetLeaveBalanceSnapshot :exec
UPDATE leave_requests
SET balance_requested_days     = $1,
    balance_remaining_at_check = $2,
    balance_requires_override  = $3,
    balance_earmark            = $4,
    balance_allocation         = $5,
    updated_at                 = now()
WHERE id = $6
  AND deleted_at IS NULL
`

type SetLeaveBalanceSnapshotParams struct {
	RequestedDays    *int32
	RemainingAtCheck *int32
	RequiresOverride *bool
	Earmark          *string
	Allocation       []byte
	ID               string
}

// Writes the FIFO reservation snapshot (openapi BalanceCheck) at SUBMIT-reserve /
// APPROVE-commit. balance_allocation is the per-lot split (jsonb array). Clearing
// (release/reverse) passes nulls.
func (q *Queries) SetLeaveBalanceSnapshot(ctx context.Context, arg SetLeaveBalanceSnapshotParams) error {
	_, err := q.db.Exec(ctx, setLeaveBalanceSnapshot,
		arg.RequestedDays,
		arg.RemainingAtCheck,
		arg.RequiresOverride,
		arg.Earmark,
		arg.Allocation,
		arg.ID,
	)
	return err
}

const updateLeaveRequestDates = `-- name: UpdateLeaveRequestDates :one
UPDATE leave_requests
SET start_date    = $1,
    end_date      = $2,
    duration_days = $3,
    updated_at    = now()
WHERE id = $4
  AND deleted_at IS NULL
RETURNING id, employee_id, placement_id, company_id, service_line_id, leave_type_id,
          start_date, end_date, duration_days, reason, notes, status,
          delegate_id, document_file_id, backdated, clock_in_conflict,
          no_leader, assigned_leader_id, balance_quota_id, balance_requested_days,
          balance_remaining_at_check, balance_requires_override, balance_earmark,
          balance_allocation, created_by, created_at, updated_at
`

type UpdateLeaveRequestDatesParams struct {
	StartDate    pgtype.Date
	EndDate      pgtype.Date
	DurationDays int32
	ID           string
}

type UpdateLeaveRequestDatesRow struct {
	ID                      string
	EmployeeID              string
	PlacementID             *string
	CompanyID               *string
	ServiceLineID           *string
	LeaveTypeID             string
	StartDate               pgtype.Date
	EndDate                 pgtype.Date
	DurationDays            int32
	Reason                  *string
	Notes                   *string
	Status                  string
	DelegateID              *string
	DocumentFileID          *string
	Backdated               bool
	ClockInConflict         bool
	NoLeader                bool
	AssignedLeaderID        *string
	BalanceQuotaID          *string
	BalanceRequestedDays    *int32
	BalanceRemainingAtCheck *int32
	BalanceRequiresOverride *bool
	BalanceEarmark          *string
	BalanceAllocation       []byte
	CreatedBy               *string
	CreatedAt               time.Time
	UpdatedAt               time.Time
}

// HR :shorten — sets a new (earlier) end_date + recomputed duration on an APPROVED
// request. Status unchanged (stays APPROVED).
func (q *Queries) UpdateLeaveRequestDates(ctx context.Context, arg UpdateLeaveRequestDatesParams) (UpdateLeaveRequestDatesRow, error) {
	row := q.db.QueryRow(ctx, updateLeaveRequestDates,
		arg.StartDate,
		arg.EndDate,
		arg.DurationDays,
		arg.ID,
	)
	var i UpdateLeaveRequestDatesRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.PlacementID,
		&i.CompanyID,
		&i.ServiceLineID,
		&i.LeaveTypeID,
		&i.StartDate,
		&i.EndDate,
		&i.DurationDays,
		&i.Reason,
		&i.Notes,
		&i.Status,
		&i.DelegateID,
		&i.DocumentFileID,
		&i.Backdated,
		&i.ClockInConflict,
		&i.NoLeader,
		&i.AssignedLeaderID,
		&i.BalanceQuotaID,
		&i.BalanceRequestedDays,
		&i.BalanceRemainingAtCheck,
		&i.BalanceRequiresOverride,
		&i.BalanceEarmark,
		&i.BalanceAllocation,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLeaveRequestStatus = `-- name: UpdateLeaveRequestStatus :one
UPDATE leave_requests
SET status                     = $1,
    no_leader                  = $2,
    assigned_leader_id         = $3,
    clock_in_conflict          = $4,
    balance_quota_id           = $5,
    balance_requested_days     = $6,
    balance_remaining_at_check = $7,
    balance_requires_override  = $8,
    updated_at                 = now()
WHERE id = $9
  AND deleted_at IS NULL
RETURNING id, employee_id, placement_id, company_id, service_line_id, leave_type_id,
          start_date, end_date, duration_days, reason, notes, status,
          delegate_id, document_file_id, backdated, clock_in_conflict,
          no_leader, assigned_leader_id, balance_quota_id, balance_requested_days,
          balance_remaining_at_check, balance_requires_override, balance_earmark,
          balance_allocation, created_by, created_at, updated_at
`

type UpdateLeaveRequestStatusParams struct {
	Status                  string
	NoLeader                bool
	AssignedLeaderID        *string
	ClockInConflict         bool
	BalanceQuotaID          *string
	BalanceRequestedDays    *int32
	BalanceRemainingAtCheck *int32
	BalanceRequiresOverride *bool
	ID                      string
}

type UpdateLeaveRequestStatusRow struct {
	ID                      string
	EmployeeID              string
	PlacementID             *string
	CompanyID               *string
	ServiceLineID           *string
	LeaveTypeID             string
	StartDate               pgtype.Date
	EndDate                 pgtype.Date
	DurationDays            int32
	Reason                  *string
	Notes                   *string
	Status                  string
	DelegateID              *string
	DocumentFileID          *string
	Backdated               bool
	ClockInConflict         bool
	NoLeader                bool
	AssignedLeaderID        *string
	BalanceQuotaID          *string
	BalanceRequestedDays    *int32
	BalanceRemainingAtCheck *int32
	BalanceRequiresOverride *bool
	BalanceEarmark          *string
	BalanceAllocation       []byte
	CreatedBy               *string
	CreatedAt               time.Time
	UpdatedAt               time.Time
}

// The approval state transitions (PENDING_L1→PENDING_HR→APPROVED, →REJECTED,
// →CANCELLED). Also refreshes the routing + balance_check snapshot columns.
func (q *Queries) UpdateLeaveRequestStatus(ctx context.Context, arg UpdateLeaveRequestStatusParams) (UpdateLeaveRequestStatusRow, error) {
	row := q.db.QueryRow(ctx, updateLeaveRequestStatus,
		arg.Status,
		arg.NoLeader,
		arg.AssignedLeaderID,
		arg.ClockInConflict,
		arg.BalanceQuotaID,
		arg.BalanceRequestedDays,
		arg.BalanceRemainingAtCheck,
		arg.BalanceRequiresOverride,
		arg.ID,
	)
	var i UpdateLeaveRequestStatusRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.PlacementID,
		&i.CompanyID,
		&i.ServiceLineID,
		&i.LeaveTypeID,
		&i.StartDate,
		&i.EndDate,
		&i.DurationDays,
		&i.Reason,
		&i.Notes,
		&i.Status,
		&i.DelegateID,
		&i.DocumentFileID,
		&i.Backdated,
		&i.ClockInConflict,
		&i.NoLeader,
		&i.AssignedLeaderID,
		&i.BalanceQuotaID,
		&i.BalanceRequestedDays,
		&i.BalanceRemainingAtCheck,
		&i.BalanceRequiresOverride,
		&i.BalanceEarmark,
		&i.BalanceAllocation,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
