// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leave_approvals.sql

package sqlcgen

import (
	"context"
)

const insertLeaveApproval = `-- name: InsertLeaveApproval :one

INSERT INTO leave_approvals (
    leave_request_id, stage, decision, actor_id, actor_role,
    decision_note, reject_reason, is_override, override_reason
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, leave_request_id, stage, decision, actor_id, actor_role,
          decision_note, reject_reason, is_override, override_reason, occurred_at
`

type InsertLeaveApprovalParams struct {
	LeaveRequestID string
	Stage          string
	Decision       string
	ActorID        *string
	ActorRole      *string
	DecisionNote   *string
	RejectReason   *string
	IsOverride     bool
	OverrideReason *string
}

// E6 leave-approval decision-trail queries. Append-only; drives the
// LeaveRequest.timeline[] the FE renders (ordered by occurred_at).
// One immutable decision row per approval action (L1/HR approve, override, reject).
func (q *Queries) InsertLeaveApproval(ctx context.Context, arg InsertLeaveApprovalParams) (LeaveApproval, error) {
	row := q.db.QueryRow(ctx, insertLeaveApproval,
		arg.LeaveRequestID,
		arg.Stage,
		arg.Decision,
		arg.ActorID,
		arg.ActorRole,
		arg.DecisionNote,
		arg.RejectReason,
		arg.IsOverride,
		arg.OverrideReason,
	)
	var i LeaveApproval
	err := row.Scan(
		&i.ID,
		&i.LeaveRequestID,
		&i.Stage,
		&i.Decision,
		&i.ActorID,
		&i.ActorRole,
		&i.DecisionNote,
		&i.RejectReason,
		&i.IsOverride,
		&i.OverrideReason,
		&i.OccurredAt,
	)
	return i, err
}

const listLeaveApprovalsForRequest = `-- name: ListLeaveApprovalsForRequest :many
SELECT la.id, la.leave_request_id, la.stage, la.decision, la.actor_id, la.actor_role,
       la.decision_note, la.reject_reason, la.is_override, la.override_reason, la.occurred_at
FROM leave_approvals la
WHERE la.leave_request_id = $1
ORDER BY la.occurred_at ASC, la.id ASC
`

// Timeline source: all decisions for a request, chronological.
func (q *Queries) ListLeaveApprovalsForRequest(ctx context.Context, leaveRequestID string) ([]LeaveApproval, error) {
	rows, err := q.db.Query(ctx, listLeaveApprovalsForRequest, leaveRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeaveApproval{}
	for rows.Next() {
		var i LeaveApproval
		if err := rows.Scan(
			&i.ID,
			&i.LeaveRequestID,
			&i.Stage,
			&i.Decision,
			&i.ActorID,
			&i.ActorRole,
			&i.DecisionNote,
			&i.RejectReason,
			&i.IsOverride,
			&i.OverrideReason,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
