// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"
)

type AttendanceCode struct {
	ID                string
	Code              string
	Label             string
	Description       string
	Color             string
	IsWorkday         bool
	IsPaid            bool
	IsBillable        bool
	NeedsVerification bool
	Status            string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	DeletedAt         *time.Time
}

type AuditLog struct {
	ID          string
	ActorUserID *string
	ActorRole   *string
	Action      string
	EntityType  string
	EntityID    string
	BeforeState []byte
	AfterState  []byte
	RequestID   *string
	CreatedAt   time.Time
}

type ClientCompany struct {
	ID          string
	Name        string
	Address     string
	LeaderScope string
	Npwp        *string
	PicName     *string
	Phone       *string
	Email       *string
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   *time.Time
}

type ClientSite struct {
	ID              string
	ClientCompanyID string
	Name            string
	Code            *string
	Address         string
	GeoLat          *float64
	GeoLng          *float64
	GeofenceRadiusM int32
	IsPrimary       bool
	PicName         *string
	Phone           *string
	Status          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       *time.Time
}

type IDCounter struct {
	Prefix  string
	NextVal int64
}

type IdempotencyKey struct {
	Key            string
	RequestHash    string
	ResponseStatus int32
	ResponseBody   []byte
	CreatedAt      time.Time
	ExpiresAt      time.Time
}

type LeaveType struct {
	ID                 string
	Name               string
	Code               string
	Description        string
	DefaultAnnualQuota int32
	IsAnnual           bool
	RequiresDocument   bool
	Color              string
	Status             string
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DeletedAt          *time.Time
}

type OvertimeRule struct {
	ID                  string
	Name                string
	ServiceLineID       *string
	WeekdayRate         float32
	RestdayRate         float32
	HolidayRate         float32
	MinMinutes          int32
	MaxMinutesPerDay    int32
	PreApprovalRequired bool
	Status              string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	DeletedAt           *time.Time
}

type PasswordResetToken struct {
	ID        int64
	UserID    string
	TokenHash string
	ExpiresAt time.Time
	UsedAt    *time.Time
	CreatedAt time.Time
}

type PlatformSetting struct {
	Key    string
	Value  string
	Label  string
	Locked bool
	Sort   int32
}

type Position struct {
	ID            string
	ServiceLineID string
	Name          string
	Alias         string
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     *time.Time
}

type RefreshToken struct {
	ID          int64
	UserID      string
	TokenHash   string
	FamilyID    string
	RotatedFrom *int64
	UserAgent   *string
	Ip          *string
	ExpiresAt   time.Time
	RevokedAt   *time.Time
	CreatedAt   time.Time
}

type ServiceLine struct {
	ID        string
	Name      string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}

type User struct {
	ID           string
	Email        string
	PasswordHash string
	Role         string
	EmployeeID   *string
	CompanyID    *string
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    *time.Time
	FullName     string
	LastLoginAt  *time.Time
}
