// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AgreementAttachment struct {
	ID          string
	AgreementID string
	Category    string
	Caption     string
	FileName    string
	Mime        string
	SizeBytes   int64
	Blob        []byte
	UploadedBy  *string
	CreatedAt   time.Time
}

type ApprovedLeaveDay struct {
	ID             int64
	EmployeeID     string
	LeaveDate      pgtype.Date
	LeaveRequestID *string
	LeaveType      *string
	CreatedAt      time.Time
}

type Attendance struct {
	ID                 string
	EmployeeID         string
	PlacementID        string
	ScheduleID         *string
	CompanyID          string
	ServiceLine        string
	AttendanceCodeID   *string
	ShiftStartAt       *time.Time
	ShiftEndAt         *time.Time
	CheckInAt          time.Time
	CheckOutAt         *time.Time
	LatIn              float64
	LngIn              float64
	LatOut             *float64
	LngOut             *float64
	PhotoInID          *string
	PhotoOutID         *string
	Wfo                bool
	IsLate             bool
	LateMinutes        int32
	WorkedMinutes      *int32
	AutoClosed         bool
	InGeofence         *bool
	InDistanceM        *int32
	OutGeofence        *bool
	OutDistanceM       *int32
	GeofenceRadiusM    int32
	Status             string
	VerificationStatus string
	Flags              []string
	VerifiedBy         *string
	VerifiedAt         *time.Time
	RejectedBy         *string
	RejectedAt         *time.Time
	RejectReason       *string
	LastCorrectionID   *string
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DeletedAt          *time.Time
}

type AttendanceCode struct {
	ID                string
	Code              string
	Label             string
	Description       string
	Color             string
	IsWorkday         bool
	IsPaid            bool
	IsBillable        bool
	NeedsVerification bool
	Status            string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	DeletedAt         *time.Time
}

type AttendanceCorrection struct {
	ID                       string
	AttendanceID             string
	RequesterID              string
	CompanyID                string
	Type                     string
	ProposedCheckInAt        *time.Time
	ProposedCheckOutAt       *time.Time
	ProposedAttendanceCodeID *string
	Reason                   string
	EvidenceFileID           *string
	Status                   string
	DecidedBy                *string
	DecidedAt                *time.Time
	RejectReason             *string
	OriginalSnapshot         []byte
	AttendanceShiftDate      pgtype.Date
	CreatedAt                time.Time
	UpdatedAt                time.Time
	DeletedAt                *time.Time
}

type AuditLog struct {
	ID          string
	ActorUserID *string
	ActorRole   *string
	Action      string
	EntityType  string
	EntityID    string
	BeforeState []byte
	AfterState  []byte
	RequestID   *string
	CreatedAt   time.Time
}

type ChangeRequest struct {
	ID              string
	EmployeeID      string
	Status          string
	Changes         []byte
	RequestType     string
	Note            *string
	SubmittedAt     time.Time
	ResolvedAt      *time.Time
	ResolvedBy      *string
	RejectionReason *string
}

type ClientCompany struct {
	ID          string
	Name        string
	Address     string
	LeaderScope string
	Npwp        *string
	PicName     *string
	Phone       *string
	Email       *string
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   *time.Time
}

type ClientSite struct {
	ID              string
	ClientCompanyID string
	Name            string
	Code            *string
	Address         string
	GeoLat          *float64
	GeoLng          *float64
	GeofenceRadiusM int32
	IsPrimary       bool
	PicName         *string
	Phone           *string
	Status          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       *time.Time
}

type Employee struct {
	ID                    string
	UserID                *string
	FullName              string
	Nik                   string
	Nip                   string
	JoinAt                pgtype.Date
	Gender                *string
	BirthDate             pgtype.Date
	BirthPlace            *string
	Phone                 *string
	EmailPersonal         *string
	Address               *string
	Npwp                  *string
	BpjsKesehatan         *string
	BpjsKetenagakerjaan   *string
	BankName              *string
	BankAccountNumber     *string
	BankAccountHolderName *string
	Status                string
	CreatedBy             *string
	CreatedAt             time.Time
	UpdatedAt             time.Time
	DeletedAt             *time.Time
}

type EmploymentAgreement struct {
	ID                string
	EmployeeID        string
	Type              string
	AgreementNo       string
	StartDate         pgtype.Date
	EndDate           pgtype.Date
	Status            string
	PredecessorID     *string
	SuccessorID       *string
	ClosedReason      *string
	ClosedAt          *time.Time
	BaseSalaryIdr     pgtype.Numeric
	BpjsTerms         []byte
	TaxProfile        *string
	CompEffectiveDate pgtype.Date
	CreatedBy         *string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	DeletedAt         *time.Time
}

type IDCounter struct {
	Prefix  string
	NextVal int64
}

type IdempotencyKey struct {
	Key            string
	RequestHash    string
	ResponseStatus int32
	ResponseBody   []byte
	CreatedAt      time.Time
	ExpiresAt      time.Time
}

type LeaveApproval struct {
	ID             int64
	LeaveRequestID string
	Stage          string
	Decision       string
	ActorID        *string
	ActorRole      *string
	DecisionNote   *string
	RejectReason   *string
	IsOverride     bool
	OverrideReason *string
	OccurredAt     time.Time
}

type LeaveQuota struct {
	ID             string
	EmployeeID     string
	LeaveTypeID    string
	Period         int32
	PeriodStart    pgtype.Date
	PeriodEnd      pgtype.Date
	Total          int32
	Used           int32
	Pending        int32
	IsProrated     bool
	ProrateMonths  int32
	Closed         bool
	LastAdjustment []byte
	LastOverride   []byte
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type LeaveRequest struct {
	ID                      string
	EmployeeID              string
	PlacementID             *string
	CompanyID               *string
	ServiceLineID           *string
	LeaveTypeID             string
	StartDate               pgtype.Date
	EndDate                 pgtype.Date
	DurationDays            int32
	Reason                  *string
	Notes                   *string
	Status                  string
	DelegateID              *string
	DocumentFileID          *string
	Backdated               bool
	ClockInConflict         bool
	NoLeader                bool
	AssignedLeaderID        *string
	BalanceQuotaID          *string
	BalanceRequestedDays    *int32
	BalanceRemainingAtCheck *int32
	BalanceRequiresOverride *bool
	CreatedBy               *string
	CreatedAt               time.Time
	UpdatedAt               time.Time
	DeletedAt               *time.Time
}

type LeaveType struct {
	ID                 string
	Name               string
	Code               string
	Description        string
	DefaultAnnualQuota int32
	IsAnnual           bool
	RequiresDocument   bool
	Color              string
	Status             string
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DeletedAt          *time.Time
}

type OvertimeRule struct {
	ID                  string
	Name                string
	ServiceLineID       *string
	WeekdayRate         float32
	RestdayRate         float32
	HolidayRate         float32
	MinMinutes          int32
	MaxMinutesPerDay    int32
	PreApprovalRequired bool
	Status              string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	DeletedAt           *time.Time
}

type PasswordResetToken struct {
	ID        int64
	UserID    string
	TokenHash string
	ExpiresAt time.Time
	UsedAt    *time.Time
	CreatedAt time.Time
}

type Placement struct {
	ID                         string
	EmployeeID                 string
	AgreementID                string
	ClientCompanyID            string
	SiteID                     string
	ServiceLineID              string
	PositionID                 string
	StartDate                  pgtype.Date
	EndDate                    pgtype.Date
	AnnualLeaveEntitlementDays *int32
	BaseSalaryRefIdr           *int64
	Notes                      *string
	LifecycleStatus            string
	StatusChangedAt            time.Time
	EndedReason                *string
	EndedAt                    pgtype.Date
	TerminationReason          *string
	ResignAt                   pgtype.Date
	PredecessorID              *string
	SuccessorID                *string
	BackdateReason             *string
	CreatedBy                  *string
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	DeletedAt                  *time.Time
}

type PlacementHistory struct {
	ID            int64
	PlacementID   string
	Action        string
	ActorUserID   *string
	Reason        *string
	EffectiveDate pgtype.Date
	StatusBefore  *string
	StatusAfter   *string
	Notes         *string
	CreatedAt     time.Time
}

type PlatformSetting struct {
	Key    string
	Value  string
	Label  string
	Locked bool
	Sort   int32
}

type Position struct {
	ID            string
	ServiceLineID string
	Name          string
	Alias         string
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     *time.Time
}

type RefreshToken struct {
	ID          int64
	UserID      string
	TokenHash   string
	FamilyID    string
	RotatedFrom *int64
	UserAgent   *string
	Ip          *string
	ExpiresAt   time.Time
	RevokedAt   *time.Time
	CreatedAt   time.Time
}

type ScheduleEntry struct {
	ID              string
	EmployeeID      string
	PlacementID     string
	ServiceLineID   *string
	ShiftMasterID   *string
	StartTime       *string
	EndTime         *string
	CrossMidnight   bool
	WorkDate        pgtype.Date
	Status          string
	IsDayOff        bool
	ReplacedEntryID *string
	CreatedBy       *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       *time.Time
}

type ServiceLine struct {
	ID        string
	Name      string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}

type ShiftLeaderAssignment struct {
	ID              string
	ClientCompanyID string
	SiteID          *string
	EmployeeID      string
	AssignedAt      time.Time
	UnassignedAt    *time.Time
	AssignedBy      *string
	VacatedReason   *string
	Notes           *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type ShiftMaster struct {
	ID            string
	Name          string
	StartTime     string
	EndTime       string
	BreakStart    *string
	BreakEnd      *string
	ServiceLineID *string
	CrossMidnight bool
	IsActive      bool
	CreatedBy     *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     *time.Time
}

type User struct {
	ID           string
	Email        string
	PasswordHash string
	Role         string
	EmployeeID   *string
	CompanyID    *string
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    *time.Time
	FullName     string
	LastLoginAt  *time.Time
}
