// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlcgen

import (
	"context"
	"time"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*) AS unread
FROM notifications
WHERE recipient_id = $1 AND read_at IS NULL
`

// Unread badge + AgentDashboard.recent_notifications_unread.
func (q *Queries) CountUnreadNotifications(ctx context.Context, recipientID string) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, recipientID)
	var unread int64
	err := row.Scan(&unread)
	return unread, err
}

const getNotification = `-- name: GetNotification :one
SELECT id, recipient_id, kind, title, body,
       deep_link_epic, deep_link_entity_id, deep_link_path,
       actor_id, actor_label, is_critical, read_at, created_at
FROM notifications
WHERE id = $1 AND recipient_id = $2
`

type GetNotificationParams struct {
	ID          string
	RecipientID string
}

// Single notification scoped to its recipient (scope=self).
func (q *Queries) GetNotification(ctx context.Context, arg GetNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotification, arg.ID, arg.RecipientID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.Kind,
		&i.Title,
		&i.Body,
		&i.DeepLinkEpic,
		&i.DeepLinkEntityID,
		&i.DeepLinkPath,
		&i.ActorID,
		&i.ActorLabel,
		&i.IsCritical,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertNotification = `-- name: InsertNotification :one
INSERT INTO notifications (
    recipient_id, kind, title, body,
    deep_link_epic, deep_link_entity_id, deep_link_path,
    actor_id, actor_label, is_critical
) VALUES (
    $1, $2, $3, $4,
    $5, $6, COALESCE($7::text, ''),
    $8, COALESCE($9::text, 'system'), $10
)
RETURNING id, recipient_id, kind, title, body,
          deep_link_epic, deep_link_entity_id, deep_link_path,
          actor_id, actor_label, is_critical, read_at, created_at
`

type InsertNotificationParams struct {
	RecipientID      string
	Kind             string
	Title            string
	Body             string
	DeepLinkEpic     *string
	DeepLinkEntityID *string
	DeepLinkPath     *string
	ActorID          *string
	ActorLabel       *string
	IsCritical       bool
}

// The worker / dispatch-helper write path. id via the column DEFAULT.
func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, insertNotification,
		arg.RecipientID,
		arg.Kind,
		arg.Title,
		arg.Body,
		arg.DeepLinkEpic,
		arg.DeepLinkEntityID,
		arg.DeepLinkPath,
		arg.ActorID,
		arg.ActorLabel,
		arg.IsCritical,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.Kind,
		&i.Title,
		&i.Body,
		&i.DeepLinkEpic,
		&i.DeepLinkEntityID,
		&i.DeepLinkPath,
		&i.ActorID,
		&i.ActorLabel,
		&i.IsCritical,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many

SELECT id, recipient_id, kind, title, body,
       deep_link_epic, deep_link_entity_id, deep_link_path,
       actor_id, actor_label, is_critical, read_at, created_at
FROM notifications
WHERE recipient_id = $1
  AND (
        $2::text IS NULL
        OR $2::text = 'ALL'
        OR ($2::text = 'UNREAD' AND read_at IS NULL)
        OR ($2::text = 'READ'   AND read_at IS NOT NULL)
      )
  AND ($3::text IS NULL OR kind = $3)
  AND (
        $4::timestamptz IS NULL
        OR (created_at, id) < ($4::timestamptz, $5::text)
      )
ORDER BY created_at DESC, id DESC
LIMIT $6
`

type ListNotificationsParams struct {
	RecipientID     string
	ReadState       *string
	Kind            *string
	CursorCreatedAt *time.Time
	CursorID        *string
	RowLimit        int32
}

// E10 F10.1 notifications queries (SWP-NTF-*). The in-app notification surface:
// cursor list (read-state + kind filters), single + bulk mark-read, unread count,
// and the worker INSERT (called by the un-stubbed NotificationWorker / notify.Dispatch
// in 11-02). id is allocated by the column DEFAULT 'SWP-NTF-' || swp_next_id('NTF')
// (the INSERT omits id). Keyset cursor mirrors ListAuditLog: (created_at, id) DESC.
// Cursor page for one recipient, newest-first. read_state: 'ALL' (no-op),
// 'UNREAD' (read_at IS NULL), 'READ' (read_at IS NOT NULL). kind optional.
func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.RecipientID,
		arg.ReadState,
		arg.Kind,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.RecipientID,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.DeepLinkEpic,
			&i.DeepLinkEntityID,
			&i.DeepLinkPath,
			&i.ActorID,
			&i.ActorLabel,
			&i.IsCritical,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :execrows
UPDATE notifications
SET read_at = now()
WHERE recipient_id = $1
  AND read_at IS NULL
  AND ($2::timestamptz IS NULL OR created_at < $2::timestamptz)
`

type MarkAllNotificationsReadParams struct {
	RecipientID string
	Before      *time.Time
}

// Bulk mark-read for a recipient. Optional @before cutoff (created_at < before).
// Returns the affected row count.
func (q *Queries) MarkAllNotificationsRead(ctx context.Context, arg MarkAllNotificationsReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markAllNotificationsRead, arg.RecipientID, arg.Before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notifications
SET read_at = COALESCE(read_at, now())
WHERE id = $1 AND recipient_id = $2
RETURNING id, recipient_id, kind, title, body,
          deep_link_epic, deep_link_entity_id, deep_link_path,
          actor_id, actor_label, is_critical, read_at, created_at
`

type MarkNotificationReadParams struct {
	ID          string
	RecipientID string
}

// Mark one notification read (no-op if already read — COALESCE keeps the first
// read_at). Scoped to recipient.
func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationRead, arg.ID, arg.RecipientID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.Kind,
		&i.Title,
		&i.Body,
		&i.DeepLinkEpic,
		&i.DeepLinkEntityID,
		&i.DeepLinkPath,
		&i.ActorID,
		&i.ActorLabel,
		&i.IsCritical,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}
