// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: overtime.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOvertime = `-- name: GetOvertime :one
SELECT ot.id, ot.employee_id, ot.company_id, ot.placement_id, ot.attendance_id,
       ot.work_date, ot.planned_start_time, ot.planned_end_time,
       ot.actual_start_time, ot.actual_end_time, ot.cross_midnight, ot.source,
       ot.status, ot.day_type, ot.worked_minutes, ot.counted_minutes,
       ot.min_minutes_threshold, ot.skipped_too_short, ot.reference_multiplier,
       ot.overtime_rule_id, ot.holiday_id, ot.flagged_no_preapproval, ot.reason,
       ot.approval_instance_id,
       ot.created_by, ot.created_at, ot.updated_at,
       e.full_name AS employee_name,
       c.name      AS company_name
FROM overtime ot
LEFT JOIN employees e        ON e.id = ot.employee_id
LEFT JOIN client_companies c ON c.id = ot.company_id
WHERE ot.id = $1
  AND ot.deleted_at IS NULL
`

type GetOvertimeRow struct {
	ID                   string
	EmployeeID           string
	CompanyID            *string
	PlacementID          string
	AttendanceID         *string
	WorkDate             pgtype.Date
	PlannedStartTime     *string
	PlannedEndTime       *string
	ActualStartTime      *string
	ActualEndTime        *string
	CrossMidnight        bool
	Source               string
	Status               string
	DayType              string
	WorkedMinutes        int32
	CountedMinutes       int32
	MinMinutesThreshold  int32
	SkippedTooShort      bool
	ReferenceMultiplier  pgtype.Numeric
	OvertimeRuleID       *string
	HolidayID            *string
	FlaggedNoPreapproval bool
	Reason               *string
	ApprovalInstanceID   *string
	CreatedBy            *string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	EmployeeName         *string
	CompanyName          *string
}

// Single OT record with denormalized employee + company names (for GET /overtime/{id}).
func (q *Queries) GetOvertime(ctx context.Context, id string) (GetOvertimeRow, error) {
	row := q.db.QueryRow(ctx, getOvertime, id)
	var i GetOvertimeRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.CompanyID,
		&i.PlacementID,
		&i.AttendanceID,
		&i.WorkDate,
		&i.PlannedStartTime,
		&i.PlannedEndTime,
		&i.ActualStartTime,
		&i.ActualEndTime,
		&i.CrossMidnight,
		&i.Source,
		&i.Status,
		&i.DayType,
		&i.WorkedMinutes,
		&i.CountedMinutes,
		&i.MinMinutesThreshold,
		&i.SkippedTooShort,
		&i.ReferenceMultiplier,
		&i.OvertimeRuleID,
		&i.HolidayID,
		&i.FlaggedNoPreapproval,
		&i.Reason,
		&i.ApprovalInstanceID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmployeeName,
		&i.CompanyName,
	)
	return i, err
}

const getOvertimeForUpdate = `-- name: GetOvertimeForUpdate :one
SELECT ot.id, ot.employee_id, ot.company_id, ot.placement_id, ot.attendance_id,
       ot.work_date, ot.planned_start_time, ot.planned_end_time,
       ot.actual_start_time, ot.actual_end_time, ot.cross_midnight, ot.source,
       ot.status, ot.day_type, ot.worked_minutes, ot.counted_minutes,
       ot.min_minutes_threshold, ot.skipped_too_short, ot.reference_multiplier,
       ot.overtime_rule_id, ot.holiday_id, ot.flagged_no_preapproval, ot.reason,
       ot.created_by, ot.created_at, ot.updated_at
FROM overtime ot
WHERE ot.id = $1
  AND ot.deleted_at IS NULL
FOR UPDATE
`

type GetOvertimeForUpdateRow struct {
	ID                   string
	EmployeeID           string
	CompanyID            *string
	PlacementID          string
	AttendanceID         *string
	WorkDate             pgtype.Date
	PlannedStartTime     *string
	PlannedEndTime       *string
	ActualStartTime      *string
	ActualEndTime        *string
	CrossMidnight        bool
	Source               string
	Status               string
	DayType              string
	WorkedMinutes        int32
	CountedMinutes       int32
	MinMinutesThreshold  int32
	SkippedTooShort      bool
	ReferenceMultiplier  pgtype.Numeric
	OvertimeRuleID       *string
	HolidayID            *string
	FlaggedNoPreapproval bool
	Reason               *string
	CreatedBy            *string
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

// Row-lock for the state-machine transitions (confirm/approve-l1/approve-final/
// reject/withdraw). Omits joins; the service re-reads via GetOvertime for the DTO.
func (q *Queries) GetOvertimeForUpdate(ctx context.Context, id string) (GetOvertimeForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getOvertimeForUpdate, id)
	var i GetOvertimeForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.CompanyID,
		&i.PlacementID,
		&i.AttendanceID,
		&i.WorkDate,
		&i.PlannedStartTime,
		&i.PlannedEndTime,
		&i.ActualStartTime,
		&i.ActualEndTime,
		&i.CrossMidnight,
		&i.Source,
		&i.Status,
		&i.DayType,
		&i.WorkedMinutes,
		&i.CountedMinutes,
		&i.MinMinutesThreshold,
		&i.SkippedTooShort,
		&i.ReferenceMultiplier,
		&i.OvertimeRuleID,
		&i.HolidayID,
		&i.FlaggedNoPreapproval,
		&i.Reason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOvertime = `-- name: InsertOvertime :one
INSERT INTO overtime (
    id, employee_id, company_id, placement_id, attendance_id,
    work_date, planned_start_time, planned_end_time, actual_start_time,
    actual_end_time, cross_midnight, source, status, day_type, worked_minutes,
    counted_minutes, min_minutes_threshold, skipped_too_short, reference_multiplier,
    overtime_rule_id, holiday_id, flagged_no_preapproval, reason, created_by
) VALUES (
    COALESCE($1::text, 'SWP-OT-' || swp_next_id('OT')),
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    $22,
    $23,
    $24
)
ON CONFLICT (id) DO NOTHING
RETURNING id, employee_id, company_id, placement_id, attendance_id,
          work_date, planned_start_time, planned_end_time, actual_start_time,
          actual_end_time, cross_midnight, source, status, day_type, worked_minutes,
          counted_minutes, min_minutes_threshold, skipped_too_short,
          reference_multiplier, overtime_rule_id, holiday_id, flagged_no_preapproval,
          reason, created_by, created_at, updated_at
`

type InsertOvertimeParams struct {
	ID                   *string
	EmployeeID           string
	CompanyID            *string
	PlacementID          string
	AttendanceID         *string
	WorkDate             pgtype.Date
	PlannedStartTime     *string
	PlannedEndTime       *string
	ActualStartTime      *string
	ActualEndTime        *string
	CrossMidnight        bool
	Source               string
	Status               string
	DayType              string
	WorkedMinutes        int32
	CountedMinutes       int32
	MinMinutesThreshold  int32
	SkippedTooShort      bool
	ReferenceMultiplier  pgtype.Numeric
	OvertimeRuleID       *string
	HolidayID            *string
	FlaggedNoPreapproval bool
	Reason               *string
	CreatedBy            *string
}

type InsertOvertimeRow struct {
	ID                   string
	EmployeeID           string
	CompanyID            *string
	PlacementID          string
	AttendanceID         *string
	WorkDate             pgtype.Date
	PlannedStartTime     *string
	PlannedEndTime       *string
	ActualStartTime      *string
	ActualEndTime        *string
	CrossMidnight        bool
	Source               string
	Status               string
	DayType              string
	WorkedMinutes        int32
	CountedMinutes       int32
	MinMinutesThreshold  int32
	SkippedTooShort      bool
	ReferenceMultiplier  pgtype.Numeric
	OvertimeRuleID       *string
	HolidayID            *string
	FlaggedNoPreapproval bool
	Reason               *string
	CreatedBy            *string
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

// Seed / HR-on-behalf path (FE/web does not create OT — mobile/agent does). id
// allocated by the column DEFAULT ('SWP-OT-' || swp_next_id('OT')) when omitted,
// OR supplied explicitly (deterministic E2E targets) via ON CONFLICT (id) DO NOTHING.
func (q *Queries) InsertOvertime(ctx context.Context, arg InsertOvertimeParams) (InsertOvertimeRow, error) {
	row := q.db.QueryRow(ctx, insertOvertime,
		arg.ID,
		arg.EmployeeID,
		arg.CompanyID,
		arg.PlacementID,
		arg.AttendanceID,
		arg.WorkDate,
		arg.PlannedStartTime,
		arg.PlannedEndTime,
		arg.ActualStartTime,
		arg.ActualEndTime,
		arg.CrossMidnight,
		arg.Source,
		arg.Status,
		arg.DayType,
		arg.WorkedMinutes,
		arg.CountedMinutes,
		arg.MinMinutesThreshold,
		arg.SkippedTooShort,
		arg.ReferenceMultiplier,
		arg.OvertimeRuleID,
		arg.HolidayID,
		arg.FlaggedNoPreapproval,
		arg.Reason,
		arg.CreatedBy,
	)
	var i InsertOvertimeRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.CompanyID,
		&i.PlacementID,
		&i.AttendanceID,
		&i.WorkDate,
		&i.PlannedStartTime,
		&i.PlannedEndTime,
		&i.ActualStartTime,
		&i.ActualEndTime,
		&i.CrossMidnight,
		&i.Source,
		&i.Status,
		&i.DayType,
		&i.WorkedMinutes,
		&i.CountedMinutes,
		&i.MinMinutesThreshold,
		&i.SkippedTooShort,
		&i.ReferenceMultiplier,
		&i.OvertimeRuleID,
		&i.HolidayID,
		&i.FlaggedNoPreapproval,
		&i.Reason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOvertime = `-- name: ListOvertime :many

SELECT ot.id, ot.employee_id, ot.company_id, ot.placement_id, ot.attendance_id,
       ot.work_date, ot.planned_start_time, ot.planned_end_time,
       ot.actual_start_time, ot.actual_end_time, ot.cross_midnight, ot.source,
       ot.status, ot.day_type, ot.worked_minutes, ot.counted_minutes,
       ot.min_minutes_threshold, ot.skipped_too_short, ot.reference_multiplier,
       ot.overtime_rule_id, ot.holiday_id, ot.flagged_no_preapproval, ot.reason,
       ot.approval_instance_id,
       ot.created_by, ot.created_at, ot.updated_at,
       e.full_name AS employee_name,
       c.name      AS company_name
FROM overtime ot
LEFT JOIN employees e        ON e.id = ot.employee_id
LEFT JOIN client_companies c ON c.id = ot.company_id
WHERE ot.deleted_at IS NULL
  AND ($1::text  IS NULL OR ot.employee_id = $1::text)
  AND ($2::text   IS NULL OR ot.company_id  = $2::text)
  AND ($3::text       IS NULL OR ot.status      = $3::text)
  AND ($4::text[]  IS NULL OR ot.status      = ANY($4::text[]))
  AND ($5::date    IS NULL OR ot.work_date  >= $5::date)
  AND ($6::date      IS NULL OR ot.work_date  <= $6::date)
  AND ($7::text     IS NULL OR ot.day_type    = $7::text)
  AND ($8::text       IS NULL OR ot.source      = $8::text)
  AND ($9::boolean IS NULL
       OR ot.flagged_no_preapproval = $9::boolean)
  -- keyset: rows strictly before the cursor (created_at,id) when provided.
  AND ($10::timestamptz IS NULL OR
       (ot.created_at, ot.id) < ($10::timestamptz, $11::text))
ORDER BY ot.created_at DESC, ot.id DESC
LIMIT $12
`

type ListOvertimeParams struct {
	EmployeeID           *string
	CompanyID            *string
	Status               *string
	StatusIn             []string
	WorkFrom             pgtype.Date
	WorkTo               pgtype.Date
	DayType              *string
	Source               *string
	FlaggedNoPreapproval *bool
	CursorCreatedAt      *time.Time
	CursorID             *string
	Lim                  int32
}

type ListOvertimeRow struct {
	ID                   string
	EmployeeID           string
	CompanyID            *string
	PlacementID          string
	AttendanceID         *string
	WorkDate             pgtype.Date
	PlannedStartTime     *string
	PlannedEndTime       *string
	ActualStartTime      *string
	ActualEndTime        *string
	CrossMidnight        bool
	Source               string
	Status               string
	DayType              string
	WorkedMinutes        int32
	CountedMinutes       int32
	MinMinutesThreshold  int32
	SkippedTooShort      bool
	ReferenceMultiplier  pgtype.Numeric
	OvertimeRuleID       *string
	HolidayID            *string
	FlaggedNoPreapproval bool
	Reason               *string
	ApprovalInstanceID   *string
	CreatedBy            *string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	EmployeeName         *string
	CompanyName          *string
}

// E7 overtime queries (F7.1/F7.4 / SWP-OT-*). Reads LEFT JOIN employees for
// employee_name, client_companies for company_name (the EmployeeRef/CompanyRef
// DTOs). work_date comes back as pgtype.Date (09-02 repo converts <-> time.Time
// like Phase-5/6/8). Keyset cursor on (created_at DESC, id) per CONVENTIONS §11.
// overtime_rules CRUD is NOT here — reused from E2/Phase-3 (db/queries/org).
// Queue / list load. Keyset cursor (created_at,id) DESC. Filters (all optional via
// narg): employee_id, company_id, status (single), status__in (text[] → status =
// ANY), work_date >= / <=, day_type (tier), source, flagged_no_preapproval.
func (q *Queries) ListOvertime(ctx context.Context, arg ListOvertimeParams) ([]ListOvertimeRow, error) {
	rows, err := q.db.Query(ctx, listOvertime,
		arg.EmployeeID,
		arg.CompanyID,
		arg.Status,
		arg.StatusIn,
		arg.WorkFrom,
		arg.WorkTo,
		arg.DayType,
		arg.Source,
		arg.FlaggedNoPreapproval,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOvertimeRow{}
	for rows.Next() {
		var i ListOvertimeRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.CompanyID,
			&i.PlacementID,
			&i.AttendanceID,
			&i.WorkDate,
			&i.PlannedStartTime,
			&i.PlannedEndTime,
			&i.ActualStartTime,
			&i.ActualEndTime,
			&i.CrossMidnight,
			&i.Source,
			&i.Status,
			&i.DayType,
			&i.WorkedMinutes,
			&i.CountedMinutes,
			&i.MinMinutesThreshold,
			&i.SkippedTooShort,
			&i.ReferenceMultiplier,
			&i.OvertimeRuleID,
			&i.HolidayID,
			&i.FlaggedNoPreapproval,
			&i.Reason,
			&i.ApprovalInstanceID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmployeeName,
			&i.CompanyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOvertimeApprovalInstanceID = `-- name: SetOvertimeApprovalInstanceID :exec
UPDATE overtime
SET approval_instance_id = $1,
    updated_at           = now()
WHERE id = $2
  AND deleted_at IS NULL
`

type SetOvertimeApprovalInstanceIDParams struct {
	ApprovalInstanceID *string
	ID                 string
}

// E11 linkage: bind an OT record to its governing approval instance.
func (q *Queries) SetOvertimeApprovalInstanceID(ctx context.Context, arg SetOvertimeApprovalInstanceIDParams) error {
	_, err := q.db.Exec(ctx, setOvertimeApprovalInstanceID, arg.ApprovalInstanceID, arg.ID)
	return err
}

const updateOvertimeStatus = `-- name: UpdateOvertimeStatus :one
UPDATE overtime
SET status     = $1,
    updated_at = now()
WHERE id = $2
  AND deleted_at IS NULL
RETURNING id, employee_id, company_id, placement_id, attendance_id,
          work_date, planned_start_time, planned_end_time, actual_start_time,
          actual_end_time, cross_midnight, source, status, day_type, worked_minutes,
          counted_minutes, min_minutes_threshold, skipped_too_short,
          reference_multiplier, overtime_rule_id, holiday_id, flagged_no_preapproval,
          reason, created_by, created_at, updated_at
`

type UpdateOvertimeStatusParams struct {
	Status string
	ID     string
}

type UpdateOvertimeStatusRow struct {
	ID                   string
	EmployeeID           string
	CompanyID            *string
	PlacementID          string
	AttendanceID         *string
	WorkDate             pgtype.Date
	PlannedStartTime     *string
	PlannedEndTime       *string
	ActualStartTime      *string
	ActualEndTime        *string
	CrossMidnight        bool
	Source               string
	Status               string
	DayType              string
	WorkedMinutes        int32
	CountedMinutes       int32
	MinMinutesThreshold  int32
	SkippedTooShort      bool
	ReferenceMultiplier  pgtype.Numeric
	OvertimeRuleID       *string
	HolidayID            *string
	FlaggedNoPreapproval bool
	Reason               *string
	CreatedBy            *string
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

// The transition writer (RETURNING-or-409 pattern). 09-02 guards the legal
// from→to transition before calling this.
func (q *Queries) UpdateOvertimeStatus(ctx context.Context, arg UpdateOvertimeStatusParams) (UpdateOvertimeStatusRow, error) {
	row := q.db.QueryRow(ctx, updateOvertimeStatus, arg.Status, arg.ID)
	var i UpdateOvertimeStatusRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.CompanyID,
		&i.PlacementID,
		&i.AttendanceID,
		&i.WorkDate,
		&i.PlannedStartTime,
		&i.PlannedEndTime,
		&i.ActualStartTime,
		&i.ActualEndTime,
		&i.CrossMidnight,
		&i.Source,
		&i.Status,
		&i.DayType,
		&i.WorkedMinutes,
		&i.CountedMinutes,
		&i.MinMinutesThreshold,
		&i.SkippedTooShort,
		&i.ReferenceMultiplier,
		&i.OvertimeRuleID,
		&i.HolidayID,
		&i.FlaggedNoPreapproval,
		&i.Reason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

// --- Duplicate detection + Aggregation (2026-06-19) ---

const existsActiveOvertimeForAgentDate = `-- name: ExistsActiveOvertimeForAgentDate :one
SELECT EXISTS(
    SELECT 1 FROM overtime
    WHERE employee_id = $1
      AND work_date   = $2::date
      AND status NOT IN ('REJECTED', 'CANCELLED')
      AND deleted_at IS NULL
) AS exists
`

func (q *Queries) ExistsActiveOvertimeForAgentDate(ctx context.Context, employeeID string, workDate pgtype.Date) (bool, error) {
	row := q.db.QueryRow(ctx, existsActiveOvertimeForAgentDate, employeeID, workDate)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const aggregateOvertime = `-- name: AggregateOvertime :many
SELECT
    CASE WHEN $1 = 'agent' THEN o.employee_id ELSE o.day_type END AS group_key,
    o.employee_id,
    COALESCE(e.full_name, '') AS employee_name,
    o.day_type,
    COALESCE(SUM(o.counted_minutes), 0)::int AS total_minutes,
    CAST(COUNT(*) AS int) AS total_approved_count,
    CAST(COUNT(*) FILTER (WHERE o.day_type = 'WORKDAY') AS int) AS workday_count,
    CAST(COUNT(*) FILTER (WHERE o.day_type = 'RESTDAY') AS int) AS restday_count,
    CAST(COUNT(*) FILTER (WHERE o.day_type = 'HOLIDAY') AS int) AS holiday_count,
    COALESCE(SUM(o.counted_minutes) FILTER (WHERE o.day_type = 'WORKDAY'), 0)::int AS workday_minutes,
    COALESCE(SUM(o.counted_minutes) FILTER (WHERE o.day_type = 'RESTDAY'), 0)::int AS restday_minutes,
    COALESCE(SUM(o.counted_minutes) FILTER (WHERE o.day_type = 'HOLIDAY'), 0)::int AS holiday_minutes
FROM overtime o
LEFT JOIN employees e ON e.id = o.employee_id
WHERE ($2::text IS NULL OR o.company_id = $2::text)
  AND ($3::date IS NULL OR o.work_date >= $3::date)
  AND ($4::date IS NULL OR o.work_date <= $4::date)
  AND o.status = 'APPROVED'
  AND o.deleted_at IS NULL
GROUP BY CASE WHEN $1 = 'agent' THEN o.employee_id ELSE o.day_type END,
         o.employee_id, e.full_name, o.day_type
ORDER BY total_minutes DESC
`

type AggregateOvertimeParams struct {
	GroupBy   string
	CompanyID *string
	DateFrom  pgtype.Date
	DateTo    pgtype.Date
}

type AggregateOvertimeRow struct {
	GroupKey           string
	EmployeeID         string
	EmployeeName       string
	DayType            string
	TotalMinutes       int32
	TotalApprovedCount int32
	WorkdayCount       int32
	RestdayCount       int32
	HolidayCount       int32
	WorkdayMinutes     int32
	RestdayMinutes     int32
	HolidayMinutes     int32
}

func (q *Queries) AggregateOvertime(ctx context.Context, arg AggregateOvertimeParams) ([]AggregateOvertimeRow, error) {
	rows, err := q.db.Query(ctx, aggregateOvertime,
		arg.GroupBy,
		arg.CompanyID,
		arg.DateFrom,
		arg.DateTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AggregateOvertimeRow{}
	for rows.Next() {
		var i AggregateOvertimeRow
		if err := rows.Scan(
			&i.GroupKey,
			&i.EmployeeID,
			&i.EmployeeName,
			&i.DayType,
			&i.TotalMinutes,
			&i.TotalApprovedCount,
			&i.WorkdayCount,
			&i.RestdayCount,
			&i.HolidayCount,
			&i.WorkdayMinutes,
			&i.RestdayMinutes,
			&i.HolidayMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
