// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: overtime_rules.sql

package sqlcgen

import (
	"context"
	"time"
)

const createOvertimeRule = `-- name: CreateOvertimeRule :one
INSERT INTO overtime_rules (id, name, service_line_id, weekday_rate, restday_rate, holiday_rate,
                            min_minutes, max_minutes_per_day, pre_approval_required)
VALUES (
    'SWP-OTR-' || swp_next_id('OTR'),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, name, service_line_id, weekday_rate, restday_rate, holiday_rate,
          min_minutes, max_minutes_per_day, pre_approval_required, status, created_at, updated_at
`

type CreateOvertimeRuleParams struct {
	Name                string
	ServiceLineID       *string
	WeekdayRate         float32
	RestdayRate         float32
	HolidayRate         float32
	MinMinutes          int32
	MaxMinutesPerDay    int32
	PreApprovalRequired bool
}

type CreateOvertimeRuleRow struct {
	ID                  string
	Name                string
	ServiceLineID       *string
	WeekdayRate         float32
	RestdayRate         float32
	HolidayRate         float32
	MinMinutes          int32
	MaxMinutesPerDay    int32
	PreApprovalRequired bool
	Status              string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

// Allocates the SWP-OTR id inline from the per-prefix sequence.
func (q *Queries) CreateOvertimeRule(ctx context.Context, arg CreateOvertimeRuleParams) (CreateOvertimeRuleRow, error) {
	row := q.db.QueryRow(ctx, createOvertimeRule,
		arg.Name,
		arg.ServiceLineID,
		arg.WeekdayRate,
		arg.RestdayRate,
		arg.HolidayRate,
		arg.MinMinutes,
		arg.MaxMinutesPerDay,
		arg.PreApprovalRequired,
	)
	var i CreateOvertimeRuleRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ServiceLineID,
		&i.WeekdayRate,
		&i.RestdayRate,
		&i.HolidayRate,
		&i.MinMinutes,
		&i.MaxMinutesPerDay,
		&i.PreApprovalRequired,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOvertimeRuleByID = `-- name: GetOvertimeRuleByID :one
SELECT id, name, service_line_id, weekday_rate, restday_rate, holiday_rate,
       min_minutes, max_minutes_per_day, pre_approval_required, status, created_at, updated_at
FROM overtime_rules
WHERE id = $1
  AND deleted_at IS NULL
`

type GetOvertimeRuleByIDRow struct {
	ID                  string
	Name                string
	ServiceLineID       *string
	WeekdayRate         float32
	RestdayRate         float32
	HolidayRate         float32
	MinMinutes          int32
	MaxMinutesPerDay    int32
	PreApprovalRequired bool
	Status              string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) GetOvertimeRuleByID(ctx context.Context, id string) (GetOvertimeRuleByIDRow, error) {
	row := q.db.QueryRow(ctx, getOvertimeRuleByID, id)
	var i GetOvertimeRuleByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ServiceLineID,
		&i.WeekdayRate,
		&i.RestdayRate,
		&i.HolidayRate,
		&i.MinMinutes,
		&i.MaxMinutesPerDay,
		&i.PreApprovalRequired,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOvertimeRules = `-- name: ListOvertimeRules :many
SELECT id, name, service_line_id, weekday_rate, restday_rate, holiday_rate,
       min_minutes, max_minutes_per_day, pre_approval_required, status, created_at, updated_at
FROM overtime_rules
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR status = $1::text)
  AND ($2::text IS NULL OR service_line_id = $2::text)
  AND (
        $3::timestamptz IS NULL
        OR (created_at, id) < ($3::timestamptz, $4::text)
      )
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListOvertimeRulesParams struct {
	Status          *string
	ServiceLineID   *string
	CursorCreatedAt *time.Time
	CursorID        *string
	RowLimit        int32
}

type ListOvertimeRulesRow struct {
	ID                  string
	Name                string
	ServiceLineID       *string
	WeekdayRate         float32
	RestdayRate         float32
	HolidayRate         float32
	MinMinutes          int32
	MaxMinutesPerDay    int32
	PreApprovalRequired bool
	Status              string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

// Cursor page ordered by (created_at desc, id desc). Fetch limit+1 for has_more.
// Filters: status, service_line (scopes to a specific line or global).
func (q *Queries) ListOvertimeRules(ctx context.Context, arg ListOvertimeRulesParams) ([]ListOvertimeRulesRow, error) {
	rows, err := q.db.Query(ctx, listOvertimeRules,
		arg.Status,
		arg.ServiceLineID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOvertimeRulesRow{}
	for rows.Next() {
		var i ListOvertimeRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ServiceLineID,
			&i.WeekdayRate,
			&i.RestdayRate,
			&i.HolidayRate,
			&i.MinMinutes,
			&i.MaxMinutesPerDay,
			&i.PreApprovalRequired,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOvertimeRuleStatus = `-- name: SetOvertimeRuleStatus :one
UPDATE overtime_rules
SET status     = $1,
    updated_at = now()
WHERE id = $2
  AND deleted_at IS NULL
RETURNING id, name, service_line_id, weekday_rate, restday_rate, holiday_rate,
          min_minutes, max_minutes_per_day, pre_approval_required, status, created_at, updated_at
`

type SetOvertimeRuleStatusParams struct {
	Status string
	ID     string
}

type SetOvertimeRuleStatusRow struct {
	ID                  string
	Name                string
	ServiceLineID       *string
	WeekdayRate         float32
	RestdayRate         float32
	HolidayRate         float32
	MinMinutes          int32
	MaxMinutesPerDay    int32
	PreApprovalRequired bool
	Status              string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

// Drives :deactivate (status='inactive') and :reactivate (status='active').
func (q *Queries) SetOvertimeRuleStatus(ctx context.Context, arg SetOvertimeRuleStatusParams) (SetOvertimeRuleStatusRow, error) {
	row := q.db.QueryRow(ctx, setOvertimeRuleStatus, arg.Status, arg.ID)
	var i SetOvertimeRuleStatusRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ServiceLineID,
		&i.WeekdayRate,
		&i.RestdayRate,
		&i.HolidayRate,
		&i.MinMinutes,
		&i.MaxMinutesPerDay,
		&i.PreApprovalRequired,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteOvertimeRule = `-- name: SoftDeleteOvertimeRule :exec
UPDATE overtime_rules
SET deleted_at = now(),
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteOvertimeRule(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, softDeleteOvertimeRule, id)
	return err
}

const updateOvertimeRule = `-- name: UpdateOvertimeRule :one
UPDATE overtime_rules
SET name                  = $1,
    service_line_id       = $2,
    weekday_rate          = $3,
    restday_rate          = $4,
    holiday_rate          = $5,
    min_minutes           = $6,
    max_minutes_per_day   = $7,
    pre_approval_required = $8,
    updated_at            = now()
WHERE id = $9
  AND deleted_at IS NULL
RETURNING id, name, service_line_id, weekday_rate, restday_rate, holiday_rate,
          min_minutes, max_minutes_per_day, pre_approval_required, status, created_at, updated_at
`

type UpdateOvertimeRuleParams struct {
	Name                string
	ServiceLineID       *string
	WeekdayRate         float32
	RestdayRate         float32
	HolidayRate         float32
	MinMinutes          int32
	MaxMinutesPerDay    int32
	PreApprovalRequired bool
	ID                  string
}

type UpdateOvertimeRuleRow struct {
	ID                  string
	Name                string
	ServiceLineID       *string
	WeekdayRate         float32
	RestdayRate         float32
	HolidayRate         float32
	MinMinutes          int32
	MaxMinutesPerDay    int32
	PreApprovalRequired bool
	Status              string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) UpdateOvertimeRule(ctx context.Context, arg UpdateOvertimeRuleParams) (UpdateOvertimeRuleRow, error) {
	row := q.db.QueryRow(ctx, updateOvertimeRule,
		arg.Name,
		arg.ServiceLineID,
		arg.WeekdayRate,
		arg.RestdayRate,
		arg.HolidayRate,
		arg.MinMinutes,
		arg.MaxMinutesPerDay,
		arg.PreApprovalRequired,
		arg.ID,
	)
	var i UpdateOvertimeRuleRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ServiceLineID,
		&i.WeekdayRate,
		&i.RestdayRate,
		&i.HolidayRate,
		&i.MinMinutes,
		&i.MaxMinutesPerDay,
		&i.PreApprovalRequired,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
