// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payslips.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPayslip = `-- name: GetPayslip :one
SELECT p.id, p.employee_id, p.employee_name, p.placement_id, p.year, p.month,
       p.paid_on, p.working_days, p.gross_earnings_enc, p.gross_deductions_enc,
       p.take_home_pay_enc, p.status, p.source_system, p.source_id,
       p.created_at, p.updated_at
FROM payslips p
WHERE p.id = $1
  AND p.deleted_at IS NULL
`

type GetPayslipRow struct {
	ID                 string
	EmployeeID         string
	EmployeeName       *string
	PlacementID        *string
	Year               int32
	Month              int32
	PaidOn             pgtype.Date
	WorkingDays        *int32
	GrossEarningsEnc   []byte
	GrossDeductionsEnc []byte
	TakeHomePayEnc     []byte
	Status             string
	SourceSystem       string
	SourceID           string
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

// Single payslip with all columns incl. ENCRYPTED money (for GET /payslips/{id}).
func (q *Queries) GetPayslip(ctx context.Context, id string) (GetPayslipRow, error) {
	row := q.db.QueryRow(ctx, getPayslip, id)
	var i GetPayslipRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.EmployeeName,
		&i.PlacementID,
		&i.Year,
		&i.Month,
		&i.PaidOn,
		&i.WorkingDays,
		&i.GrossEarningsEnc,
		&i.GrossDeductionsEnc,
		&i.TakeHomePayEnc,
		&i.Status,
		&i.SourceSystem,
		&i.SourceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPayslip = `-- name: InsertPayslip :one
INSERT INTO payslips (
    id, employee_id, employee_name, placement_id, year, month, paid_on,
    working_days, gross_earnings_enc, gross_deductions_enc, take_home_pay_enc,
    status, source_system, source_id
) VALUES (
    COALESCE($1::text, 'SWP-PS-' || swp_next_id('PS')),
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14
)
ON CONFLICT (id) DO NOTHING
RETURNING id, employee_id, employee_name, placement_id, year, month, paid_on,
          working_days, gross_earnings_enc, gross_deductions_enc, take_home_pay_enc,
          status, source_system, source_id, created_at, updated_at
`

type InsertPayslipParams struct {
	ID                 *string
	EmployeeID         string
	EmployeeName       *string
	PlacementID        *string
	Year               int32
	Month              int32
	PaidOn             pgtype.Date
	WorkingDays        *int32
	GrossEarningsEnc   []byte
	GrossDeductionsEnc []byte
	TakeHomePayEnc     []byte
	Status             string
	SourceSystem       string
	SourceID           string
}

type InsertPayslipRow struct {
	ID                 string
	EmployeeID         string
	EmployeeName       *string
	PlacementID        *string
	Year               int32
	Month              int32
	PaidOn             pgtype.Date
	WorkingDays        *int32
	GrossEarningsEnc   []byte
	GrossDeductionsEnc []byte
	TakeHomePayEnc     []byte
	Status             string
	SourceSystem       string
	SourceID           string
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

// Seed path (10-02 inserts ciphertext produced by the crypto helper). id
// allocated by the column DEFAULT ('SWP-PS-' || swp_next_id('PS')) when omitted,
// OR supplied explicitly (deterministic E2E targets) via ON CONFLICT (id) DO NOTHING.
func (q *Queries) InsertPayslip(ctx context.Context, arg InsertPayslipParams) (InsertPayslipRow, error) {
	row := q.db.QueryRow(ctx, insertPayslip,
		arg.ID,
		arg.EmployeeID,
		arg.EmployeeName,
		arg.PlacementID,
		arg.Year,
		arg.Month,
		arg.PaidOn,
		arg.WorkingDays,
		arg.GrossEarningsEnc,
		arg.GrossDeductionsEnc,
		arg.TakeHomePayEnc,
		arg.Status,
		arg.SourceSystem,
		arg.SourceID,
	)
	var i InsertPayslipRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.EmployeeName,
		&i.PlacementID,
		&i.Year,
		&i.Month,
		&i.PaidOn,
		&i.WorkingDays,
		&i.GrossEarningsEnc,
		&i.GrossDeductionsEnc,
		&i.TakeHomePayEnc,
		&i.Status,
		&i.SourceSystem,
		&i.SourceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPayslipBenefit = `-- name: InsertPayslipBenefit :one
INSERT INTO payslip_benefits (payslip_id, name, value_enc, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING id, payslip_id, name, value_enc, sort_order
`

type InsertPayslipBenefitParams struct {
	PayslipID string
	Name      string
	ValueEnc  []byte
	SortOrder int32
}

// Seed: one employer-borne benefit line.
func (q *Queries) InsertPayslipBenefit(ctx context.Context, arg InsertPayslipBenefitParams) (PayslipBenefit, error) {
	row := q.db.QueryRow(ctx, insertPayslipBenefit,
		arg.PayslipID,
		arg.Name,
		arg.ValueEnc,
		arg.SortOrder,
	)
	var i PayslipBenefit
	err := row.Scan(
		&i.ID,
		&i.PayslipID,
		&i.Name,
		&i.ValueEnc,
		&i.SortOrder,
	)
	return i, err
}

const insertPayslipComponent = `-- name: InsertPayslipComponent :one
INSERT INTO payslip_components (payslip_id, kind, name, value_enc, for_bpjs, sort_order)
VALUES ($1, $2, $3,
        $4, $5, $6)
RETURNING id, payslip_id, kind, name, value_enc, for_bpjs, sort_order
`

type InsertPayslipComponentParams struct {
	PayslipID string
	Kind      string
	Name      string
	ValueEnc  []byte
	ForBpjs   bool
	SortOrder int32
}

// Seed: one earning/deduction line (value_enc = crypto.Encrypt of the Money string).
func (q *Queries) InsertPayslipComponent(ctx context.Context, arg InsertPayslipComponentParams) (PayslipComponent, error) {
	row := q.db.QueryRow(ctx, insertPayslipComponent,
		arg.PayslipID,
		arg.Kind,
		arg.Name,
		arg.ValueEnc,
		arg.ForBpjs,
		arg.SortOrder,
	)
	var i PayslipComponent
	err := row.Scan(
		&i.ID,
		&i.PayslipID,
		&i.Kind,
		&i.Name,
		&i.ValueEnc,
		&i.ForBpjs,
		&i.SortOrder,
	)
	return i, err
}

const listPayslipBenefits = `-- name: ListPayslipBenefits :many
SELECT id, payslip_id, name, value_enc, sort_order
FROM payslip_benefits
WHERE payslip_id = $1
ORDER BY sort_order, id
`

// Employer-borne benefits (HR-only). value_enc ENCRYPTED.
func (q *Queries) ListPayslipBenefits(ctx context.Context, payslipID string) ([]PayslipBenefit, error) {
	rows, err := q.db.Query(ctx, listPayslipBenefits, payslipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PayslipBenefit{}
	for rows.Next() {
		var i PayslipBenefit
		if err := rows.Scan(
			&i.ID,
			&i.PayslipID,
			&i.Name,
			&i.ValueEnc,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayslipComponents = `-- name: ListPayslipComponents :many
SELECT id, payslip_id, kind, name, value_enc, for_bpjs, sort_order
FROM payslip_components
WHERE payslip_id = $1
ORDER BY kind, sort_order, id
`

// Earnings + deductions breakdown for the detail view. value_enc is ENCRYPTED
// (decrypted at the boundary). Ordered kind then sort_order.
func (q *Queries) ListPayslipComponents(ctx context.Context, payslipID string) ([]PayslipComponent, error) {
	rows, err := q.db.Query(ctx, listPayslipComponents, payslipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PayslipComponent{}
	for rows.Next() {
		var i PayslipComponent
		if err := rows.Scan(
			&i.ID,
			&i.PayslipID,
			&i.Kind,
			&i.Name,
			&i.ValueEnc,
			&i.ForBpjs,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayslips = `-- name: ListPayslips :many

SELECT p.id, p.employee_id, p.employee_name, p.placement_id, p.year, p.month,
       p.paid_on, p.working_days, p.gross_earnings_enc, p.gross_deductions_enc,
       p.take_home_pay_enc, p.status, p.source_system, p.source_id,
       p.created_at, p.updated_at
FROM payslips p
WHERE p.deleted_at IS NULL
  AND ($1::text IS NULL OR p.employee_id = $1::text)
  AND ($2::int        IS NULL OR p.year         = $2::int)
  AND ($3::int       IS NULL OR p.month        = $3::int)
  AND ($4::text     IS NULL OR p.status       = $4::text)
  -- Keyset cursor under the ORDER BY below. We sort by a COALESCE sentinel
  -- (NULL paid_on -> '0001-01-01', so it sorts last under DESC) tupled with id,
  -- and page strictly past the cursor tuple. 10-02 encodes (paid_on, id) into
  -- the opaque cursor; a NULL paid_on row encodes the sentinel date.
  AND (
    $5::text IS NULL
    OR (COALESCE(p.paid_on, DATE '0001-01-01'), p.id)
       < (COALESCE($6::date, DATE '0001-01-01'), $5::text)
  )
ORDER BY COALESCE(p.paid_on, DATE '0001-01-01') DESC, p.id DESC
LIMIT $7
`

type ListPayslipsParams struct {
	EmployeeID   *string
	Year         *int32
	Month        *int32
	Status       *string
	CursorID     *string
	CursorPaidOn pgtype.Date
	Lim          int32
}

type ListPayslipsRow struct {
	ID                 string
	EmployeeID         string
	EmployeeName       *string
	PlacementID        *string
	Year               int32
	Month              int32
	PaidOn             pgtype.Date
	WorkingDays        *int32
	GrossEarningsEnc   []byte
	GrossDeductionsEnc []byte
	TakeHomePayEnc     []byte
	Status             string
	SourceSystem       string
	SourceID           string
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

// E8 payroll queries (F8.1/F8.2 / SWP-PS-*). Historical, read-only archive.
// Monetary columns come back as ENCRYPTED ciphertext (gross_*_enc /
// take_home_pay_enc / value_enc bytea) — the 10-02 repo/service decrypts at the
// boundary via internal/platform/crypto, NOT in SQL. paid_on comes back as
// pgtype.Date (10-02 repo converts <-> time.Time like Phase-5/6/8/9). Keyset
// cursor on (paid_on DESC NULLS LAST, id DESC) per CONVENTIONS §11 (default sort
// paid_on:desc).
// Archive / list load. Keyset cursor on (paid_on, id) DESC, NULL paid_on sorts
// last. Filters (all optional via narg): employee_id, year, month (from the
// period YYYY-MM), status. Summary only — NO components/benefits join. Returns
// the *_enc ciphertext (repo decrypts in 10-02).
func (q *Queries) ListPayslips(ctx context.Context, arg ListPayslipsParams) ([]ListPayslipsRow, error) {
	rows, err := q.db.Query(ctx, listPayslips,
		arg.EmployeeID,
		arg.Year,
		arg.Month,
		arg.Status,
		arg.CursorID,
		arg.CursorPaidOn,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPayslipsRow{}
	for rows.Next() {
		var i ListPayslipsRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.EmployeeName,
			&i.PlacementID,
			&i.Year,
			&i.Month,
			&i.PaidOn,
			&i.WorkingDays,
			&i.GrossEarningsEnc,
			&i.GrossDeductionsEnc,
			&i.TakeHomePayEnc,
			&i.Status,
			&i.SourceSystem,
			&i.SourceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
