// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: photos.sql

package sqlcgen

import (
	"context"
	"time"
)

const createAttendancePhoto = `-- name: CreateAttendancePhoto :one
INSERT INTO attendance_photos (
    id, employee_id, caption, file_name, mime, size_bytes, blob
) VALUES (
    'SWP-FILE-' || swp_next_id('FILE'),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, file_name, mime, size_bytes, created_at
`

type CreateAttendancePhotoParams struct {
	EmployeeID string
	Caption    string
	FileName   string
	Mime       string
	SizeBytes  int64
	Blob       []byte
}

type CreateAttendancePhotoRow struct {
	ID        string
	FileName  string
	Mime      string
	SizeBytes int64
	CreatedAt time.Time
}

// Stores one clock-in/out selfie (E5 F5.1 / CI-10). Allocates the SWP-FILE id inline
// from the shared per-prefix sequence. Returns metadata only (not the blob).
func (q *Queries) CreateAttendancePhoto(ctx context.Context, arg CreateAttendancePhotoParams) (CreateAttendancePhotoRow, error) {
	row := q.db.QueryRow(ctx, createAttendancePhoto,
		arg.EmployeeID,
		arg.Caption,
		arg.FileName,
		arg.Mime,
		arg.SizeBytes,
		arg.Blob,
	)
	var i CreateAttendancePhotoRow
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.Mime,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const getAttendancePhotoByID = `-- name: GetAttendancePhotoByID :one
SELECT id, file_name, mime, size_bytes, blob, created_at
FROM attendance_photos
WHERE id = $1
`

type GetAttendancePhotoByIDRow struct {
	ID        string
	FileName  string
	Mime      string
	SizeBytes int64
	Blob      []byte
	CreatedAt time.Time
}

// Returns selfie metadata + blob for the authenticated file-download handler.
func (q *Queries) GetAttendancePhotoByID(ctx context.Context, id string) (GetAttendancePhotoByIDRow, error) {
	row := q.db.QueryRow(ctx, getAttendancePhotoByID, id)
	var i GetAttendancePhotoByIDRow
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.Mime,
		&i.SizeBytes,
		&i.Blob,
		&i.CreatedAt,
	)
	return i, err
}
