// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: placements.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlacement = `-- name: CreatePlacement :one
INSERT INTO placements (
    employee_id, agreement_id, client_company_id, site_id, position,
    start_date, end_date, notes, lifecycle_status, predecessor_id,
    backdate_reason, created_by
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
RETURNING id, employee_id, agreement_id, client_company_id, site_id,
          position, start_date, end_date,
          notes,
          lifecycle_status, status_changed_at, ended_reason, ended_at,
          termination_reason, resign_at, predecessor_id, successor_id,
          backdate_reason, created_by, created_at, updated_at,
          (agreement_id IS NULL)::boolean AS awaiting_agreement
`

type CreatePlacementParams struct {
	EmployeeID      string
	AgreementID     *string
	ClientCompanyID string
	SiteID          string
	Position        string
	StartDate       pgtype.Date
	EndDate         pgtype.Date
	Notes           *string
	LifecycleStatus string
	PredecessorID   *string
	BackdateReason  *string
	CreatedBy       *string
}

type CreatePlacementRow struct {
	ID                string
	EmployeeID        string
	AgreementID       *string
	ClientCompanyID   string
	SiteID            string
	Position          string
	StartDate         pgtype.Date
	EndDate           pgtype.Date
	Notes             *string
	LifecycleStatus   string
	StatusChangedAt   time.Time
	EndedReason       *string
	EndedAt           pgtype.Date
	TerminationReason *string
	ResignAt          pgtype.Date
	PredecessorID     *string
	SuccessorID       *string
	BackdateReason    *string
	CreatedBy         *string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	AwaitingAgreement bool
}

// id allocated by the column DEFAULT ('SWP-PL-' || swp_next_id('PL')).
func (q *Queries) CreatePlacement(ctx context.Context, arg CreatePlacementParams) (CreatePlacementRow, error) {
	row := q.db.QueryRow(ctx, createPlacement,
		arg.EmployeeID,
		arg.AgreementID,
		arg.ClientCompanyID,
		arg.SiteID,
		arg.Position,
		arg.StartDate,
		arg.EndDate,
		arg.Notes,
		arg.LifecycleStatus,
		arg.PredecessorID,
		arg.BackdateReason,
		arg.CreatedBy,
	)
	var i CreatePlacementRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.AgreementID,
		&i.ClientCompanyID,
		&i.SiteID,
		&i.Position,
		&i.StartDate,
		&i.EndDate,
		&i.Notes,
		&i.LifecycleStatus,
		&i.StatusChangedAt,
		&i.EndedReason,
		&i.EndedAt,
		&i.TerminationReason,
		&i.ResignAt,
		&i.PredecessorID,
		&i.SuccessorID,
		&i.BackdateReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AwaitingAgreement,
	)
	return i, err
}

const endPlacementsForEmployee = `-- name: EndPlacementsForEmployee :many
UPDATE placements
SET lifecycle_status  = $1::text,
    ended_reason      = $2::text,
    ended_at          = $3::date,
    status_changed_at = now(),
    updated_at        = now()
WHERE employee_id = $4
  AND deleted_at IS NULL
  AND lifecycle_status NOT IN ('ENDED','TRANSFERRED','SUPERSEDED','TERMINATED','RESIGNED')
RETURNING id, client_company_id, lifecycle_status, ended_reason
`

type EndPlacementsForEmployeeParams struct {
	LifecycleStatus string
	EndedReason     string
	EndedAt         pgtype.Date
	EmployeeID      string
}

type EndPlacementsForEmployeeRow struct {
	ID              string
	ClientCompanyID string
	LifecycleStatus string
	EndedReason     *string
}

// Offboard cascade (OB-1): end every non-terminal placement of an employee.
func (q *Queries) EndPlacementsForEmployee(ctx context.Context, arg EndPlacementsForEmployeeParams) ([]EndPlacementsForEmployeeRow, error) {
	rows, err := q.db.Query(ctx, endPlacementsForEmployee,
		arg.LifecycleStatus,
		arg.EndedReason,
		arg.EndedAt,
		arg.EmployeeID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EndPlacementsForEmployeeRow{}
	for rows.Next() {
		var i EndPlacementsForEmployeeRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientCompanyID,
			&i.LifecycleStatus,
			&i.EndedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActivePlacementForEmployee = `-- name: GetActivePlacementForEmployee :one
SELECT p.id, p.employee_id, p.agreement_id, p.client_company_id, p.site_id,
       p.position, p.start_date, p.end_date,
       p.notes,
       p.lifecycle_status, p.status_changed_at, p.ended_reason, p.ended_at,
       p.termination_reason, p.resign_at, p.predecessor_id, p.successor_id,
       p.backdate_reason, p.created_by, p.created_at, p.updated_at,
       e.full_name      AS employee_name,
       c.name           AS client_company_name,
       s.name           AS site_name,
       a.type           AS agreement_type,
       (p.agreement_id IS NULL)::boolean AS awaiting_agreement
FROM placements p
LEFT JOIN employees e             ON e.id   = p.employee_id
LEFT JOIN client_companies c      ON c.id   = p.client_company_id
LEFT JOIN client_sites s          ON s.id   = p.site_id
LEFT JOIN employment_agreements a ON a.id   = p.agreement_id
WHERE p.employee_id = $1
  AND p.lifecycle_status IN ('ACTIVE','EXPIRING','PENDING_START')
  AND p.deleted_at IS NULL
`

type GetActivePlacementForEmployeeRow struct {
	ID                string
	EmployeeID        string
	AgreementID       *string
	ClientCompanyID   string
	SiteID            string
	Position          string
	StartDate         pgtype.Date
	EndDate           pgtype.Date
	Notes             *string
	LifecycleStatus   string
	StatusChangedAt   time.Time
	EndedReason       *string
	EndedAt           pgtype.Date
	TerminationReason *string
	ResignAt          pgtype.Date
	PredecessorID     *string
	SuccessorID       *string
	BackdateReason    *string
	CreatedBy         *string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	EmployeeName      *string
	ClientCompanyName *string
	SiteName          *string
	AgreementType     *string
	AwaitingAgreement bool
}

// INV-1 service pre-check (friendly 409 before hitting the partial unique index).
func (q *Queries) GetActivePlacementForEmployee(ctx context.Context, employeeID string) (GetActivePlacementForEmployeeRow, error) {
	row := q.db.QueryRow(ctx, getActivePlacementForEmployee, employeeID)
	var i GetActivePlacementForEmployeeRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.AgreementID,
		&i.ClientCompanyID,
		&i.SiteID,
		&i.Position,
		&i.StartDate,
		&i.EndDate,
		&i.Notes,
		&i.LifecycleStatus,
		&i.StatusChangedAt,
		&i.EndedReason,
		&i.EndedAt,
		&i.TerminationReason,
		&i.ResignAt,
		&i.PredecessorID,
		&i.SuccessorID,
		&i.BackdateReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmployeeName,
		&i.ClientCompanyName,
		&i.SiteName,
		&i.AgreementType,
		&i.AwaitingAgreement,
	)
	return i, err
}

const getActivePlacementForEmployeeAtCompanyForUpdate = `-- name: GetActivePlacementForEmployeeAtCompanyForUpdate :one
SELECT p.id, p.employee_id, p.agreement_id, p.client_company_id, p.site_id,
       p.position, p.start_date, p.end_date,
       p.notes,
       p.lifecycle_status, p.status_changed_at, p.ended_reason, p.ended_at,
       p.termination_reason, p.resign_at, p.predecessor_id, p.successor_id,
       p.backdate_reason, p.created_by, p.created_at, p.updated_at,
       (p.agreement_id IS NULL)::boolean AS awaiting_agreement
FROM placements p
WHERE p.employee_id = $1
  AND p.client_company_id = $2
  AND p.lifecycle_status IN ('ACTIVE','EXPIRING','PENDING_START')
  AND p.deleted_at IS NULL
FOR UPDATE
`

type GetActivePlacementForEmployeeAtCompanyForUpdateParams struct {
	EmployeeID      string
	ClientCompanyID string
}

type GetActivePlacementForEmployeeAtCompanyForUpdateRow struct {
	ID                string
	EmployeeID        string
	AgreementID       *string
	ClientCompanyID   string
	SiteID            string
	Position          string
	StartDate         pgtype.Date
	EndDate           pgtype.Date
	Notes             *string
	LifecycleStatus   string
	StatusChangedAt   time.Time
	EndedReason       *string
	EndedAt           pgtype.Date
	TerminationReason *string
	ResignAt          pgtype.Date
	PredecessorID     *string
	SuccessorID       *string
	BackdateReason    *string
	CreatedBy         *string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	AwaitingAgreement bool
}

// INV-4 lock: the agent's active placement at a specific company, row-locked.
func (q *Queries) GetActivePlacementForEmployeeAtCompanyForUpdate(ctx context.Context, arg GetActivePlacementForEmployeeAtCompanyForUpdateParams) (GetActivePlacementForEmployeeAtCompanyForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getActivePlacementForEmployeeAtCompanyForUpdate, arg.EmployeeID, arg.ClientCompanyID)
	var i GetActivePlacementForEmployeeAtCompanyForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.AgreementID,
		&i.ClientCompanyID,
		&i.SiteID,
		&i.Position,
		&i.StartDate,
		&i.EndDate,
		&i.Notes,
		&i.LifecycleStatus,
		&i.StatusChangedAt,
		&i.EndedReason,
		&i.EndedAt,
		&i.TerminationReason,
		&i.ResignAt,
		&i.PredecessorID,
		&i.SuccessorID,
		&i.BackdateReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AwaitingAgreement,
	)
	return i, err
}

const getPlacementByID = `-- name: GetPlacementByID :one
SELECT p.id, p.employee_id, p.agreement_id, p.client_company_id, p.site_id,
       p.position, p.start_date, p.end_date,
       p.notes,
       p.lifecycle_status, p.status_changed_at, p.ended_reason, p.ended_at,
       p.termination_reason, p.resign_at, p.predecessor_id, p.successor_id,
       p.backdate_reason, p.created_by, p.created_at, p.updated_at,
       e.full_name      AS employee_name,
       c.name           AS client_company_name,
       s.name           AS site_name,
       a.type           AS agreement_type,
       (p.agreement_id IS NULL)::boolean AS awaiting_agreement
FROM placements p
LEFT JOIN employees e             ON e.id   = p.employee_id
LEFT JOIN client_companies c      ON c.id   = p.client_company_id
LEFT JOIN client_sites s          ON s.id   = p.site_id
LEFT JOIN employment_agreements a ON a.id   = p.agreement_id
WHERE p.id = $1
  AND p.deleted_at IS NULL
`

type GetPlacementByIDRow struct {
	ID                string
	EmployeeID        string
	AgreementID       *string
	ClientCompanyID   string
	SiteID            string
	Position          string
	StartDate         pgtype.Date
	EndDate           pgtype.Date
	Notes             *string
	LifecycleStatus   string
	StatusChangedAt   time.Time
	EndedReason       *string
	EndedAt           pgtype.Date
	TerminationReason *string
	ResignAt          pgtype.Date
	PredecessorID     *string
	SuccessorID       *string
	BackdateReason    *string
	CreatedBy         *string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	EmployeeName      *string
	ClientCompanyName *string
	SiteName          *string
	AgreementType     *string
	AwaitingAgreement bool
}

func (q *Queries) GetPlacementByID(ctx context.Context, id string) (GetPlacementByIDRow, error) {
	row := q.db.QueryRow(ctx, getPlacementByID, id)
	var i GetPlacementByIDRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.AgreementID,
		&i.ClientCompanyID,
		&i.SiteID,
		&i.Position,
		&i.StartDate,
		&i.EndDate,
		&i.Notes,
		&i.LifecycleStatus,
		&i.StatusChangedAt,
		&i.EndedReason,
		&i.EndedAt,
		&i.TerminationReason,
		&i.ResignAt,
		&i.PredecessorID,
		&i.SuccessorID,
		&i.BackdateReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmployeeName,
		&i.ClientCompanyName,
		&i.SiteName,
		&i.AgreementType,
		&i.AwaitingAgreement,
	)
	return i, err
}

const getPlacementChain = `-- name: GetPlacementChain :many
WITH RECURSIVE chain AS (
    SELECT p0.id, p0.predecessor_id, p0.successor_id
    FROM placements p0
    WHERE p0.id = $1
  UNION
    SELECT p1.id, p1.predecessor_id, p1.successor_id
    FROM placements p1
    JOIN chain ch ON p1.id = ch.predecessor_id OR p1.id = ch.successor_id
)
SELECT p.id, p.employee_id, p.agreement_id, p.client_company_id, p.site_id,
       p.position, p.start_date, p.end_date,
       p.notes,
       p.lifecycle_status, p.status_changed_at, p.ended_reason, p.ended_at,
       p.termination_reason, p.resign_at, p.predecessor_id, p.successor_id,
       p.backdate_reason, p.created_by, p.created_at, p.updated_at,
       e.full_name      AS employee_name,
       c.name           AS client_company_name,
       s.name           AS site_name,
       a.type           AS agreement_type,
       (p.agreement_id IS NULL)::boolean AS awaiting_agreement
FROM placements p
JOIN chain ch                     ON ch.id  = p.id
LEFT JOIN employees e             ON e.id   = p.employee_id
LEFT JOIN client_companies c      ON c.id   = p.client_company_id
LEFT JOIN client_sites s          ON s.id   = p.site_id
LEFT JOIN employment_agreements a ON a.id   = p.agreement_id
ORDER BY p.start_date ASC, p.id ASC
`

type GetPlacementChainRow struct {
	ID                string
	EmployeeID        string
	AgreementID       *string
	ClientCompanyID   string
	SiteID            string
	Position          string
	StartDate         pgtype.Date
	EndDate           pgtype.Date
	Notes             *string
	LifecycleStatus   string
	StatusChangedAt   time.Time
	EndedReason       *string
	EndedAt           pgtype.Date
	TerminationReason *string
	ResignAt          pgtype.Date
	PredecessorID     *string
	SuccessorID       *string
	BackdateReason    *string
	CreatedBy         *string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	EmployeeName      *string
	ClientCompanyName *string
	SiteName          *string
	AgreementType     *string
	AwaitingAgreement bool
}

// All placements sharing a predecessor/successor chain with the given placement
// (for history_chain). Walks both directions from the seed via a recursive CTE.
func (q *Queries) GetPlacementChain(ctx context.Context, id string) ([]GetPlacementChainRow, error) {
	rows, err := q.db.Query(ctx, getPlacementChain, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlacementChainRow{}
	for rows.Next() {
		var i GetPlacementChainRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.AgreementID,
			&i.ClientCompanyID,
			&i.SiteID,
			&i.Position,
			&i.StartDate,
			&i.EndDate,
			&i.Notes,
			&i.LifecycleStatus,
			&i.StatusChangedAt,
			&i.EndedReason,
			&i.EndedAt,
			&i.TerminationReason,
			&i.ResignAt,
			&i.PredecessorID,
			&i.SuccessorID,
			&i.BackdateReason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmployeeName,
			&i.ClientCompanyName,
			&i.SiteName,
			&i.AgreementType,
			&i.AwaitingAgreement,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiringPlacements = `-- name: ListExpiringPlacements :many
SELECT p.id, p.employee_id, p.agreement_id, p.client_company_id, p.site_id,
       p.position, p.start_date, p.end_date,
       p.notes,
       p.lifecycle_status, p.status_changed_at, p.ended_reason, p.ended_at,
       p.termination_reason, p.resign_at, p.predecessor_id, p.successor_id,
       p.backdate_reason, p.created_by, p.created_at, p.updated_at,
       e.full_name      AS employee_name,
       c.name           AS client_company_name,
       s.name           AS site_name,
       a.type           AS agreement_type,
       (p.agreement_id IS NULL)::boolean AS awaiting_agreement
FROM placements p
LEFT JOIN employees e             ON e.id   = p.employee_id
LEFT JOIN client_companies c      ON c.id   = p.client_company_id
LEFT JOIN client_sites s          ON s.id   = p.site_id
LEFT JOIN employment_agreements a ON a.id   = p.agreement_id
WHERE p.deleted_at IS NULL
  AND p.lifecycle_status IN ('ACTIVE','EXPIRING')
  AND p.end_date IS NOT NULL
  AND p.end_date <= $1::date
  AND ($2::text IS NULL OR p.client_company_id = $2::text)
  AND (
        $3::date IS NULL
        OR (p.end_date, p.id) > ($3::date, $4::text)
      )
ORDER BY p.end_date ASC, p.id ASC
LIMIT $5
`

type ListExpiringPlacementsParams struct {
	Cutoff        pgtype.Date
	CompanyID     *string
	CursorEndDate pgtype.Date
	CursorID      *string
	RowLimit      int32
}

type ListExpiringPlacementsRow struct {
	ID                string
	EmployeeID        string
	AgreementID       *string
	ClientCompanyID   string
	SiteID            string
	Position          string
	StartDate         pgtype.Date
	EndDate           pgtype.Date
	Notes             *string
	LifecycleStatus   string
	StatusChangedAt   time.Time
	EndedReason       *string
	EndedAt           pgtype.Date
	TerminationReason *string
	ResignAt          pgtype.Date
	PredecessorID     *string
	SuccessorID       *string
	BackdateReason    *string
	CreatedBy         *string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	EmployeeName      *string
	ClientCompanyName *string
	SiteName          *string
	AgreementType     *string
	AwaitingAgreement bool
}

// Backs GET /placements/expiring. Keyset on (end_date asc, id asc).
// @cutoff = today(Asia/Jakarta) + within_days (computed in the service).
func (q *Queries) ListExpiringPlacements(ctx context.Context, arg ListExpiringPlacementsParams) ([]ListExpiringPlacementsRow, error) {
	rows, err := q.db.Query(ctx, listExpiringPlacements,
		arg.Cutoff,
		arg.CompanyID,
		arg.CursorEndDate,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiringPlacementsRow{}
	for rows.Next() {
		var i ListExpiringPlacementsRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.AgreementID,
			&i.ClientCompanyID,
			&i.SiteID,
			&i.Position,
			&i.StartDate,
			&i.EndDate,
			&i.Notes,
			&i.LifecycleStatus,
			&i.StatusChangedAt,
			&i.EndedReason,
			&i.EndedAt,
			&i.TerminationReason,
			&i.ResignAt,
			&i.PredecessorID,
			&i.SuccessorID,
			&i.BackdateReason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmployeeName,
			&i.ClientCompanyName,
			&i.SiteName,
			&i.AgreementType,
			&i.AwaitingAgreement,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlacements = `-- name: ListPlacements :many

SELECT p.id, p.employee_id, p.agreement_id, p.client_company_id, p.site_id,
       p.position, p.start_date, p.end_date,
       p.notes,
       p.lifecycle_status, p.status_changed_at, p.ended_reason, p.ended_at,
       p.termination_reason, p.resign_at, p.predecessor_id, p.successor_id,
       p.backdate_reason, p.created_by, p.created_at, p.updated_at,
       e.full_name      AS employee_name,
       c.name           AS client_company_name,
       s.name           AS site_name,
       a.type           AS agreement_type,
       (p.agreement_id IS NULL)::boolean AS awaiting_agreement
FROM placements p
LEFT JOIN employees e             ON e.id   = p.employee_id
LEFT JOIN client_companies c      ON c.id   = p.client_company_id
LEFT JOIN client_sites s          ON s.id   = p.site_id
LEFT JOIN employment_agreements a ON a.id   = p.agreement_id
WHERE p.deleted_at IS NULL
  AND ($1::text      IS NULL OR p.client_company_id = $1::text)
  AND ($2::text        IS NULL OR p.position          = $2::text)
  AND ($3::text     IS NULL OR p.employee_id       = $3::text)
  AND ($4::text    IS NULL OR p.agreement_id      = $4::text)
  AND ($5::text          IS NULL OR p.lifecycle_status  = $5::text)
  AND ($6::text[]     IS NULL OR p.lifecycle_status  = ANY($6::text[]))
  AND ($7::date   IS NULL OR (p.end_date IS NOT NULL AND p.end_date <= $7::date))
  AND ($8::boolean IS NULL OR (p.agreement_id IS NULL) = $8::boolean)
  AND (
        $9::boolean
        OR p.lifecycle_status NOT IN ('ENDED','TRANSFERRED','TERMINATED','RESIGNED','SUPERSEDED')
      )
  AND (
        $10::text IS NULL
        OR e.full_name   ILIKE '%' || $10::text || '%'
        OR p.employee_id ILIKE '%' || $10::text || '%'
        OR c.name        ILIKE '%' || $10::text || '%'
        OR p.position    ILIKE '%' || $10::text || '%'
      )
  AND (
        $11::timestamptz IS NULL
        OR (p.status_changed_at, p.id) < ($11::timestamptz, $12::text)
      )
ORDER BY p.status_changed_at DESC, p.id DESC
LIMIT $13
`

type ListPlacementsParams struct {
	CompanyID             *string
	Position              *string
	EmployeeID            *string
	AgreementID           *string
	Status                *string
	StatusIn              []string
	EndDateLte            pgtype.Date
	AwaitingAgreement     *bool
	IncludeHistory        bool
	Q                     *string
	CursorStatusChangedAt *time.Time
	CursorID              *string
	RowLimit              int32
}

type ListPlacementsRow struct {
	ID                string
	EmployeeID        string
	AgreementID       *string
	ClientCompanyID   string
	SiteID            string
	Position          string
	StartDate         pgtype.Date
	EndDate           pgtype.Date
	Notes             *string
	LifecycleStatus   string
	StatusChangedAt   time.Time
	EndedReason       *string
	EndedAt           pgtype.Date
	TerminationReason *string
	ResignAt          pgtype.Date
	PredecessorID     *string
	SuccessorID       *string
	BackdateReason    *string
	CreatedBy         *string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	EmployeeName      *string
	ClientCompanyName *string
	SiteName          *string
	AgreementType     *string
	AwaitingAgreement bool
}

// E3 placement queries (F3.1/F3.2 / PLC-*). All reads LEFT JOIN the Phase-3/4
// master tables to fill the denormalized *_name fields the spec returns.
// Position is FREE-TEXT (no master, no FK, no ID) — selected directly from the
// placements.position text column (service_line dropped entirely 2026-06-12).
// Param→column note: the FE/spec params are `status` / `status__in`; both filter
// the `lifecycle_status` column. No param is literally named `lifecycle_status`.
// Cursor page ordered by (status_changed_at desc, id desc). Fetch limit+1 for has_more.
// Filters: company_id, position (exact free-text), employee_id, agreement_id,
//
//	status (single → lifecycle_status =), status__in (CSV → lifecycle_status = ANY),
//	q (ILIKE over agent name / employee_id / company name / position),
//	end_date__lte (expiring cutoff), include_history (exclude terminal states unless true).
func (q *Queries) ListPlacements(ctx context.Context, arg ListPlacementsParams) ([]ListPlacementsRow, error) {
	rows, err := q.db.Query(ctx, listPlacements,
		arg.CompanyID,
		arg.Position,
		arg.EmployeeID,
		arg.AgreementID,
		arg.Status,
		arg.StatusIn,
		arg.EndDateLte,
		arg.AwaitingAgreement,
		arg.IncludeHistory,
		arg.Q,
		arg.CursorStatusChangedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlacementsRow{}
	for rows.Next() {
		var i ListPlacementsRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.AgreementID,
			&i.ClientCompanyID,
			&i.SiteID,
			&i.Position,
			&i.StartDate,
			&i.EndDate,
			&i.Notes,
			&i.LifecycleStatus,
			&i.StatusChangedAt,
			&i.EndedReason,
			&i.EndedAt,
			&i.TerminationReason,
			&i.ResignAt,
			&i.PredecessorID,
			&i.SuccessorID,
			&i.BackdateReason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmployeeName,
			&i.ClientCompanyName,
			&i.SiteName,
			&i.AgreementType,
			&i.AwaitingAgreement,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEmployeePlacements = `-- name: LockEmployeePlacements :many
SELECT p.id, p.employee_id, p.agreement_id, p.client_company_id, p.site_id,
       p.position, p.start_date, p.end_date,
       p.notes,
       p.lifecycle_status, p.status_changed_at, p.ended_reason, p.ended_at,
       p.termination_reason, p.resign_at, p.predecessor_id, p.successor_id,
       p.backdate_reason, p.created_by, p.created_at, p.updated_at,
       (p.agreement_id IS NULL)::boolean AS awaiting_agreement
FROM placements p
WHERE p.employee_id = $1
  AND p.deleted_at IS NULL
FOR UPDATE
`

type LockEmployeePlacementsRow struct {
	ID                string
	EmployeeID        string
	AgreementID       *string
	ClientCompanyID   string
	SiteID            string
	Position          string
	StartDate         pgtype.Date
	EndDate           pgtype.Date
	Notes             *string
	LifecycleStatus   string
	StatusChangedAt   time.Time
	EndedReason       *string
	EndedAt           pgtype.Date
	TerminationReason *string
	ResignAt          pgtype.Date
	PredecessorID     *string
	SuccessorID       *string
	BackdateReason    *string
	CreatedBy         *string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	AwaitingAgreement bool
}

// INV-1 / period-overlap lock: all of the agent's placements, row-locked.
func (q *Queries) LockEmployeePlacements(ctx context.Context, employeeID string) ([]LockEmployeePlacementsRow, error) {
	rows, err := q.db.Query(ctx, lockEmployeePlacements, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockEmployeePlacementsRow{}
	for rows.Next() {
		var i LockEmployeePlacementsRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.AgreementID,
			&i.ClientCompanyID,
			&i.SiteID,
			&i.Position,
			&i.StartDate,
			&i.EndDate,
			&i.Notes,
			&i.LifecycleStatus,
			&i.StatusChangedAt,
			&i.EndedReason,
			&i.EndedAt,
			&i.TerminationReason,
			&i.ResignAt,
			&i.PredecessorID,
			&i.SuccessorID,
			&i.BackdateReason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AwaitingAgreement,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const placementGlobalStats = `-- name: PlacementGlobalStats :one
SELECT
  COUNT(DISTINCT p.client_company_id) FILTER (
    WHERE p.lifecycle_status NOT IN ('ENDED','TRANSFERRED','SUPERSEDED','TERMINATED','RESIGNED')
  )::bigint AS client_company_count,
  COUNT(*) FILTER (WHERE p.lifecycle_status IN ('ACTIVE','EXTENDED'))::bigint AS active_count,
  COUNT(*) FILTER (WHERE p.lifecycle_status = 'EXPIRING')::bigint AS expiring_count,
  COUNT(*) FILTER (WHERE p.lifecycle_status = 'PENDING_START')::bigint AS pending_count
FROM placements p
WHERE p.deleted_at IS NULL
  AND ($1::text IS NULL OR p.client_company_id = $1::text)
`

type PlacementGlobalStatsRow struct {
	ClientCompanyCount int64
	ActiveCount        int64
	ExpiringCount      int64
	PendingCount       int64
}

// Dashboard stat cards (C2SSLA): global placement aggregates over non-deleted
// placements. Optional company_id scopes the counts (shift-leader RBAC).
func (q *Queries) PlacementGlobalStats(ctx context.Context, companyID *string) (PlacementGlobalStatsRow, error) {
	row := q.db.QueryRow(ctx, placementGlobalStats, companyID)
	var i PlacementGlobalStatsRow
	err := row.Scan(
		&i.ClientCompanyCount,
		&i.ActiveCount,
		&i.ExpiringCount,
		&i.PendingCount,
	)
	return i, err
}

const rosterForCompany = `-- name: RosterForCompany :many
SELECT p.id, p.employee_id, p.agreement_id, p.client_company_id, p.site_id,
       p.position, p.start_date, p.end_date,
       p.notes,
       p.lifecycle_status, p.status_changed_at, p.ended_reason, p.ended_at,
       p.termination_reason, p.resign_at, p.predecessor_id, p.successor_id,
       p.backdate_reason, p.created_by, p.created_at, p.updated_at,
       e.full_name      AS employee_name,
       c.name           AS client_company_name,
       s.name           AS site_name,
       a.type           AS agreement_type,
       (p.agreement_id IS NULL)::boolean AS awaiting_agreement
FROM placements p
LEFT JOIN employees e             ON e.id   = p.employee_id
LEFT JOIN client_companies c      ON c.id   = p.client_company_id
LEFT JOIN client_sites s          ON s.id   = p.site_id
LEFT JOIN employment_agreements a ON a.id   = p.agreement_id
WHERE p.client_company_id = $1
  AND p.deleted_at IS NULL
  AND ($2::text         IS NULL OR p.position         = $2::text)
  AND ($3::text          IS NULL OR p.lifecycle_status = $3::text)
  AND ($4::text[]     IS NULL OR p.lifecycle_status = ANY($4::text[]))
  AND ($5::boolean IS NULL OR (p.agreement_id IS NULL) = $5::boolean)
  AND (
        $6::boolean
        OR p.lifecycle_status NOT IN ('ENDED','TRANSFERRED','TERMINATED','RESIGNED','SUPERSEDED')
      )
  AND (
        $7::timestamptz IS NULL
        OR (p.status_changed_at, p.id) < ($7::timestamptz, $8::text)
      )
ORDER BY p.status_changed_at DESC, p.id DESC
LIMIT $9
`

type RosterForCompanyParams struct {
	ClientCompanyID       string
	Position              *string
	Status                *string
	StatusIn              []string
	AwaitingAgreement     *bool
	IncludeHistory        bool
	CursorStatusChangedAt *time.Time
	CursorID              *string
	RowLimit              int32
}

type RosterForCompanyRow struct {
	ID                string
	EmployeeID        string
	AgreementID       *string
	ClientCompanyID   string
	SiteID            string
	Position          string
	StartDate         pgtype.Date
	EndDate           pgtype.Date
	Notes             *string
	LifecycleStatus   string
	StatusChangedAt   time.Time
	EndedReason       *string
	EndedAt           pgtype.Date
	TerminationReason *string
	ResignAt          pgtype.Date
	PredecessorID     *string
	SuccessorID       *string
	BackdateReason    *string
	CreatedBy         *string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	EmployeeName      *string
	ClientCompanyName *string
	SiteName          *string
	AgreementType     *string
	AwaitingAgreement bool
}

// Company roster (RO-*). Filters: status (single), status__in (CSV),
// position (exact free-text), include_history. Keyset on (status_changed_at desc, id desc).
func (q *Queries) RosterForCompany(ctx context.Context, arg RosterForCompanyParams) ([]RosterForCompanyRow, error) {
	rows, err := q.db.Query(ctx, rosterForCompany,
		arg.ClientCompanyID,
		arg.Position,
		arg.Status,
		arg.StatusIn,
		arg.AwaitingAgreement,
		arg.IncludeHistory,
		arg.CursorStatusChangedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RosterForCompanyRow{}
	for rows.Next() {
		var i RosterForCompanyRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.AgreementID,
			&i.ClientCompanyID,
			&i.SiteID,
			&i.Position,
			&i.StartDate,
			&i.EndDate,
			&i.Notes,
			&i.LifecycleStatus,
			&i.StatusChangedAt,
			&i.EndedReason,
			&i.EndedAt,
			&i.TerminationReason,
			&i.ResignAt,
			&i.PredecessorID,
			&i.SuccessorID,
			&i.BackdateReason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmployeeName,
			&i.ClientCompanyName,
			&i.SiteName,
			&i.AgreementType,
			&i.AwaitingAgreement,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rosterSummaryByPosition = `-- name: RosterSummaryByPosition :many
SELECT p.position AS position,
       COUNT(*)   AS count
FROM placements p
WHERE p.client_company_id = $1
  AND p.deleted_at IS NULL
  AND p.lifecycle_status IN ('ACTIVE','EXPIRING','PENDING_START')
GROUP BY p.position
`

type RosterSummaryByPositionRow struct {
	Position string
	Count    int64
}

// CompanyRosterSummary by_position counts (active placements only), grouped by the
// free-text position label (service_line rollup dropped 2026-06-12).
func (q *Queries) RosterSummaryByPosition(ctx context.Context, clientCompanyID string) ([]RosterSummaryByPositionRow, error) {
	rows, err := q.db.Query(ctx, rosterSummaryByPosition, clientCompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RosterSummaryByPositionRow{}
	for rows.Next() {
		var i RosterSummaryByPositionRow
		if err := rows.Scan(&i.Position, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rosterSummaryByStatus = `-- name: RosterSummaryByStatus :many
SELECT p.lifecycle_status AS status, COUNT(*) AS count
FROM placements p
WHERE p.client_company_id = $1
  AND p.deleted_at IS NULL
GROUP BY p.lifecycle_status
`

type RosterSummaryByStatusRow struct {
	Status string
	Count  int64
}

// CompanyRosterSummary by_status counts (non-deleted; non-terminal unless caller filters).
func (q *Queries) RosterSummaryByStatus(ctx context.Context, clientCompanyID string) ([]RosterSummaryByStatusRow, error) {
	rows, err := q.db.Query(ctx, rosterSummaryByStatus, clientCompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RosterSummaryByStatusRow{}
	for rows.Next() {
		var i RosterSummaryByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPlacementAgreement = `-- name: SetPlacementAgreement :one
UPDATE placements
SET agreement_id = $1,
    end_date     = $2,
    updated_at   = now()
WHERE id = $3
  AND deleted_at IS NULL
RETURNING id, employee_id, agreement_id, client_company_id, site_id,
          position, start_date, end_date,
          notes,
          lifecycle_status, status_changed_at, ended_reason, ended_at,
          termination_reason, resign_at, predecessor_id, successor_id,
          backdate_reason, created_by, created_at, updated_at,
          (agreement_id IS NULL)::boolean AS awaiting_agreement
`

type SetPlacementAgreementParams struct {
	AgreementID *string
	EndDate     pgtype.Date
	ID          string
}

type SetPlacementAgreementRow struct {
	ID                string
	EmployeeID        string
	AgreementID       *string
	ClientCompanyID   string
	SiteID            string
	Position          string
	StartDate         pgtype.Date
	EndDate           pgtype.Date
	Notes             *string
	LifecycleStatus   string
	StatusChangedAt   time.Time
	EndedReason       *string
	EndedAt           pgtype.Date
	TerminationReason *string
	ResignAt          pgtype.Date
	PredecessorID     *string
	SuccessorID       *string
	BackdateReason    *string
	CreatedBy         *string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	AwaitingAgreement bool
}

// Backfill: attach an agreement to a previously pending placement (awaiting_agreement).
// end_date is updated too so the service can persist the BR-1b PKWT auto-cap in the
// same write. awaiting_agreement flips to false once agreement_id is non-null.
func (q *Queries) SetPlacementAgreement(ctx context.Context, arg SetPlacementAgreementParams) (SetPlacementAgreementRow, error) {
	row := q.db.QueryRow(ctx, setPlacementAgreement, arg.AgreementID, arg.EndDate, arg.ID)
	var i SetPlacementAgreementRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.AgreementID,
		&i.ClientCompanyID,
		&i.SiteID,
		&i.Position,
		&i.StartDate,
		&i.EndDate,
		&i.Notes,
		&i.LifecycleStatus,
		&i.StatusChangedAt,
		&i.EndedReason,
		&i.EndedAt,
		&i.TerminationReason,
		&i.ResignAt,
		&i.PredecessorID,
		&i.SuccessorID,
		&i.BackdateReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AwaitingAgreement,
	)
	return i, err
}

const setPlacementLifecycle = `-- name: SetPlacementLifecycle :one
UPDATE placements
SET lifecycle_status   = $1,
    status_changed_at  = now(),
    ended_reason       = $2,
    ended_at           = $3,
    termination_reason = $4,
    resign_at          = $5,
    successor_id       = $6,
    updated_at         = now()
WHERE id = $7
RETURNING id, employee_id, agreement_id, client_company_id, site_id,
          position, start_date, end_date,
          notes,
          lifecycle_status, status_changed_at, ended_reason, ended_at,
          termination_reason, resign_at, predecessor_id, successor_id,
          backdate_reason, created_by, created_at, updated_at,
          (agreement_id IS NULL)::boolean AS awaiting_agreement
`

type SetPlacementLifecycleParams struct {
	LifecycleStatus   string
	EndedReason       *string
	EndedAt           pgtype.Date
	TerminationReason *string
	ResignAt          pgtype.Date
	SuccessorID       *string
	ID                string
}

type SetPlacementLifecycleRow struct {
	ID                string
	EmployeeID        string
	AgreementID       *string
	ClientCompanyID   string
	SiteID            string
	Position          string
	StartDate         pgtype.Date
	EndDate           pgtype.Date
	Notes             *string
	LifecycleStatus   string
	StatusChangedAt   time.Time
	EndedReason       *string
	EndedAt           pgtype.Date
	TerminationReason *string
	ResignAt          pgtype.Date
	PredecessorID     *string
	SuccessorID       *string
	BackdateReason    *string
	CreatedBy         *string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	AwaitingAgreement bool
}

// Drives end/terminate/resign/transfer/supersede. status_changed_at=now().
func (q *Queries) SetPlacementLifecycle(ctx context.Context, arg SetPlacementLifecycleParams) (SetPlacementLifecycleRow, error) {
	row := q.db.QueryRow(ctx, setPlacementLifecycle,
		arg.LifecycleStatus,
		arg.EndedReason,
		arg.EndedAt,
		arg.TerminationReason,
		arg.ResignAt,
		arg.SuccessorID,
		arg.ID,
	)
	var i SetPlacementLifecycleRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.AgreementID,
		&i.ClientCompanyID,
		&i.SiteID,
		&i.Position,
		&i.StartDate,
		&i.EndDate,
		&i.Notes,
		&i.LifecycleStatus,
		&i.StatusChangedAt,
		&i.EndedReason,
		&i.EndedAt,
		&i.TerminationReason,
		&i.ResignAt,
		&i.PredecessorID,
		&i.SuccessorID,
		&i.BackdateReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AwaitingAgreement,
	)
	return i, err
}

const setPlacementPredecessor = `-- name: SetPlacementPredecessor :exec
UPDATE placements SET predecessor_id = $1, updated_at = now()
WHERE id = $2
`

type SetPlacementPredecessorParams struct {
	PredecessorID *string
	ID            string
}

func (q *Queries) SetPlacementPredecessor(ctx context.Context, arg SetPlacementPredecessorParams) error {
	_, err := q.db.Exec(ctx, setPlacementPredecessor, arg.PredecessorID, arg.ID)
	return err
}

const setPlacementSuccessor = `-- name: SetPlacementSuccessor :exec
UPDATE placements SET successor_id = $1, updated_at = now()
WHERE id = $2
`

type SetPlacementSuccessorParams struct {
	SuccessorID *string
	ID          string
}

func (q *Queries) SetPlacementSuccessor(ctx context.Context, arg SetPlacementSuccessorParams) error {
	_, err := q.db.Exec(ctx, setPlacementSuccessor, arg.SuccessorID, arg.ID)
	return err
}

const updatePlacementFields = `-- name: UpdatePlacementFields :one
UPDATE placements
SET position                      = $1,
    end_date                      = $2,
    notes                         = $3,
    updated_at                    = now()
WHERE id = $4
RETURNING id, employee_id, agreement_id, client_company_id, site_id,
          position, start_date, end_date,
          notes,
          lifecycle_status, status_changed_at, ended_reason, ended_at,
          termination_reason, resign_at, predecessor_id, successor_id,
          backdate_reason, created_by, created_at, updated_at,
          (agreement_id IS NULL)::boolean AS awaiting_agreement
`

type UpdatePlacementFieldsParams struct {
	Position string
	EndDate  pgtype.Date
	Notes    *string
	ID       string
}

type UpdatePlacementFieldsRow struct {
	ID                string
	EmployeeID        string
	AgreementID       *string
	ClientCompanyID   string
	SiteID            string
	Position          string
	StartDate         pgtype.Date
	EndDate           pgtype.Date
	Notes             *string
	LifecycleStatus   string
	StatusChangedAt   time.Time
	EndedReason       *string
	EndedAt           pgtype.Date
	TerminationReason *string
	ResignAt          pgtype.Date
	PredecessorID     *string
	SuccessorID       *string
	BackdateReason    *string
	CreatedBy         *string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	AwaitingAgreement bool
}

// Limited-field PATCH (position, end_date, notes).
func (q *Queries) UpdatePlacementFields(ctx context.Context, arg UpdatePlacementFieldsParams) (UpdatePlacementFieldsRow, error) {
	row := q.db.QueryRow(ctx, updatePlacementFields,
		arg.Position,
		arg.EndDate,
		arg.Notes,
		arg.ID,
	)
	var i UpdatePlacementFieldsRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.AgreementID,
		&i.ClientCompanyID,
		&i.SiteID,
		&i.Position,
		&i.StartDate,
		&i.EndDate,
		&i.Notes,
		&i.LifecycleStatus,
		&i.StatusChangedAt,
		&i.EndedReason,
		&i.EndedAt,
		&i.TerminationReason,
		&i.ResignAt,
		&i.PredecessorID,
		&i.SuccessorID,
		&i.BackdateReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AwaitingAgreement,
	)
	return i, err
}
