// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: placements.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlacement = `-- name: CreatePlacement :one
INSERT INTO placements (
    employee_id, agreement_id, client_company_id, site_id, service_line_id,
    position_id, start_date, end_date, annual_leave_entitlement_days,
    base_salary_ref_idr, notes, lifecycle_status, predecessor_id,
    backdate_reason, created_by
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15
)
RETURNING id, employee_id, agreement_id, client_company_id, site_id,
          service_line_id, position_id, start_date, end_date,
          annual_leave_entitlement_days, base_salary_ref_idr, notes,
          lifecycle_status, status_changed_at, ended_reason, ended_at,
          termination_reason, resign_at, predecessor_id, successor_id,
          backdate_reason, created_by, created_at, updated_at
`

type CreatePlacementParams struct {
	EmployeeID                 string
	AgreementID                string
	ClientCompanyID            string
	SiteID                     string
	ServiceLineID              string
	PositionID                 string
	StartDate                  pgtype.Date
	EndDate                    pgtype.Date
	AnnualLeaveEntitlementDays *int32
	BaseSalaryRefIdr           *int64
	Notes                      *string
	LifecycleStatus            string
	PredecessorID              *string
	BackdateReason             *string
	CreatedBy                  *string
}

type CreatePlacementRow struct {
	ID                         string
	EmployeeID                 string
	AgreementID                string
	ClientCompanyID            string
	SiteID                     string
	ServiceLineID              string
	PositionID                 string
	StartDate                  pgtype.Date
	EndDate                    pgtype.Date
	AnnualLeaveEntitlementDays *int32
	BaseSalaryRefIdr           *int64
	Notes                      *string
	LifecycleStatus            string
	StatusChangedAt            time.Time
	EndedReason                *string
	EndedAt                    pgtype.Date
	TerminationReason          *string
	ResignAt                   pgtype.Date
	PredecessorID              *string
	SuccessorID                *string
	BackdateReason             *string
	CreatedBy                  *string
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
}

// id allocated by the column DEFAULT ('SWP-PL-' || swp_next_id('PL')).
func (q *Queries) CreatePlacement(ctx context.Context, arg CreatePlacementParams) (CreatePlacementRow, error) {
	row := q.db.QueryRow(ctx, createPlacement,
		arg.EmployeeID,
		arg.AgreementID,
		arg.ClientCompanyID,
		arg.SiteID,
		arg.ServiceLineID,
		arg.PositionID,
		arg.StartDate,
		arg.EndDate,
		arg.AnnualLeaveEntitlementDays,
		arg.BaseSalaryRefIdr,
		arg.Notes,
		arg.LifecycleStatus,
		arg.PredecessorID,
		arg.BackdateReason,
		arg.CreatedBy,
	)
	var i CreatePlacementRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.AgreementID,
		&i.ClientCompanyID,
		&i.SiteID,
		&i.ServiceLineID,
		&i.PositionID,
		&i.StartDate,
		&i.EndDate,
		&i.AnnualLeaveEntitlementDays,
		&i.BaseSalaryRefIdr,
		&i.Notes,
		&i.LifecycleStatus,
		&i.StatusChangedAt,
		&i.EndedReason,
		&i.EndedAt,
		&i.TerminationReason,
		&i.ResignAt,
		&i.PredecessorID,
		&i.SuccessorID,
		&i.BackdateReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActivePlacementForEmployee = `-- name: GetActivePlacementForEmployee :one
SELECT p.id, p.employee_id, p.agreement_id, p.client_company_id, p.site_id,
       p.service_line_id, p.position_id, p.start_date, p.end_date,
       p.annual_leave_entitlement_days, p.base_salary_ref_idr, p.notes,
       p.lifecycle_status, p.status_changed_at, p.ended_reason, p.ended_at,
       p.termination_reason, p.resign_at, p.predecessor_id, p.successor_id,
       p.backdate_reason, p.created_by, p.created_at, p.updated_at,
       e.full_name      AS employee_name,
       c.name           AS client_company_name,
       s.name           AS site_name,
       sl.name          AS service_line_name,
       pos.name         AS position_name,
       a.type           AS agreement_type
FROM placements p
LEFT JOIN employees e             ON e.id   = p.employee_id
LEFT JOIN client_companies c      ON c.id   = p.client_company_id
LEFT JOIN client_sites s          ON s.id   = p.site_id
LEFT JOIN service_lines sl        ON sl.id  = p.service_line_id
LEFT JOIN positions pos           ON pos.id = p.position_id
LEFT JOIN employment_agreements a ON a.id   = p.agreement_id
WHERE p.employee_id = $1
  AND p.lifecycle_status IN ('ACTIVE','EXPIRING','PENDING_START')
  AND p.deleted_at IS NULL
`

type GetActivePlacementForEmployeeRow struct {
	ID                         string
	EmployeeID                 string
	AgreementID                string
	ClientCompanyID            string
	SiteID                     string
	ServiceLineID              string
	PositionID                 string
	StartDate                  pgtype.Date
	EndDate                    pgtype.Date
	AnnualLeaveEntitlementDays *int32
	BaseSalaryRefIdr           *int64
	Notes                      *string
	LifecycleStatus            string
	StatusChangedAt            time.Time
	EndedReason                *string
	EndedAt                    pgtype.Date
	TerminationReason          *string
	ResignAt                   pgtype.Date
	PredecessorID              *string
	SuccessorID                *string
	BackdateReason             *string
	CreatedBy                  *string
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	EmployeeName               *string
	ClientCompanyName          *string
	SiteName                   *string
	ServiceLineName            *string
	PositionName               *string
	AgreementType              *string
}

// INV-1 service pre-check (friendly 409 before hitting the partial unique index).
func (q *Queries) GetActivePlacementForEmployee(ctx context.Context, employeeID string) (GetActivePlacementForEmployeeRow, error) {
	row := q.db.QueryRow(ctx, getActivePlacementForEmployee, employeeID)
	var i GetActivePlacementForEmployeeRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.AgreementID,
		&i.ClientCompanyID,
		&i.SiteID,
		&i.ServiceLineID,
		&i.PositionID,
		&i.StartDate,
		&i.EndDate,
		&i.AnnualLeaveEntitlementDays,
		&i.BaseSalaryRefIdr,
		&i.Notes,
		&i.LifecycleStatus,
		&i.StatusChangedAt,
		&i.EndedReason,
		&i.EndedAt,
		&i.TerminationReason,
		&i.ResignAt,
		&i.PredecessorID,
		&i.SuccessorID,
		&i.BackdateReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmployeeName,
		&i.ClientCompanyName,
		&i.SiteName,
		&i.ServiceLineName,
		&i.PositionName,
		&i.AgreementType,
	)
	return i, err
}

const getActivePlacementForEmployeeAtCompanyForUpdate = `-- name: GetActivePlacementForEmployeeAtCompanyForUpdate :one
SELECT p.id, p.employee_id, p.agreement_id, p.client_company_id, p.site_id,
       p.service_line_id, p.position_id, p.start_date, p.end_date,
       p.annual_leave_entitlement_days, p.base_salary_ref_idr, p.notes,
       p.lifecycle_status, p.status_changed_at, p.ended_reason, p.ended_at,
       p.termination_reason, p.resign_at, p.predecessor_id, p.successor_id,
       p.backdate_reason, p.created_by, p.created_at, p.updated_at
FROM placements p
WHERE p.employee_id = $1
  AND p.client_company_id = $2
  AND p.lifecycle_status IN ('ACTIVE','EXPIRING','PENDING_START')
  AND p.deleted_at IS NULL
FOR UPDATE
`

type GetActivePlacementForEmployeeAtCompanyForUpdateParams struct {
	EmployeeID      string
	ClientCompanyID string
}

type GetActivePlacementForEmployeeAtCompanyForUpdateRow struct {
	ID                         string
	EmployeeID                 string
	AgreementID                string
	ClientCompanyID            string
	SiteID                     string
	ServiceLineID              string
	PositionID                 string
	StartDate                  pgtype.Date
	EndDate                    pgtype.Date
	AnnualLeaveEntitlementDays *int32
	BaseSalaryRefIdr           *int64
	Notes                      *string
	LifecycleStatus            string
	StatusChangedAt            time.Time
	EndedReason                *string
	EndedAt                    pgtype.Date
	TerminationReason          *string
	ResignAt                   pgtype.Date
	PredecessorID              *string
	SuccessorID                *string
	BackdateReason             *string
	CreatedBy                  *string
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
}

// INV-4 lock: the agent's active placement at a specific company, row-locked.
func (q *Queries) GetActivePlacementForEmployeeAtCompanyForUpdate(ctx context.Context, arg GetActivePlacementForEmployeeAtCompanyForUpdateParams) (GetActivePlacementForEmployeeAtCompanyForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getActivePlacementForEmployeeAtCompanyForUpdate, arg.EmployeeID, arg.ClientCompanyID)
	var i GetActivePlacementForEmployeeAtCompanyForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.AgreementID,
		&i.ClientCompanyID,
		&i.SiteID,
		&i.ServiceLineID,
		&i.PositionID,
		&i.StartDate,
		&i.EndDate,
		&i.AnnualLeaveEntitlementDays,
		&i.BaseSalaryRefIdr,
		&i.Notes,
		&i.LifecycleStatus,
		&i.StatusChangedAt,
		&i.EndedReason,
		&i.EndedAt,
		&i.TerminationReason,
		&i.ResignAt,
		&i.PredecessorID,
		&i.SuccessorID,
		&i.BackdateReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlacementByID = `-- name: GetPlacementByID :one
SELECT p.id, p.employee_id, p.agreement_id, p.client_company_id, p.site_id,
       p.service_line_id, p.position_id, p.start_date, p.end_date,
       p.annual_leave_entitlement_days, p.base_salary_ref_idr, p.notes,
       p.lifecycle_status, p.status_changed_at, p.ended_reason, p.ended_at,
       p.termination_reason, p.resign_at, p.predecessor_id, p.successor_id,
       p.backdate_reason, p.created_by, p.created_at, p.updated_at,
       e.full_name      AS employee_name,
       c.name           AS client_company_name,
       s.name           AS site_name,
       sl.name          AS service_line_name,
       pos.name         AS position_name,
       a.type           AS agreement_type
FROM placements p
LEFT JOIN employees e             ON e.id   = p.employee_id
LEFT JOIN client_companies c      ON c.id   = p.client_company_id
LEFT JOIN client_sites s          ON s.id   = p.site_id
LEFT JOIN service_lines sl        ON sl.id  = p.service_line_id
LEFT JOIN positions pos           ON pos.id = p.position_id
LEFT JOIN employment_agreements a ON a.id   = p.agreement_id
WHERE p.id = $1
  AND p.deleted_at IS NULL
`

type GetPlacementByIDRow struct {
	ID                         string
	EmployeeID                 string
	AgreementID                string
	ClientCompanyID            string
	SiteID                     string
	ServiceLineID              string
	PositionID                 string
	StartDate                  pgtype.Date
	EndDate                    pgtype.Date
	AnnualLeaveEntitlementDays *int32
	BaseSalaryRefIdr           *int64
	Notes                      *string
	LifecycleStatus            string
	StatusChangedAt            time.Time
	EndedReason                *string
	EndedAt                    pgtype.Date
	TerminationReason          *string
	ResignAt                   pgtype.Date
	PredecessorID              *string
	SuccessorID                *string
	BackdateReason             *string
	CreatedBy                  *string
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	EmployeeName               *string
	ClientCompanyName          *string
	SiteName                   *string
	ServiceLineName            *string
	PositionName               *string
	AgreementType              *string
}

func (q *Queries) GetPlacementByID(ctx context.Context, id string) (GetPlacementByIDRow, error) {
	row := q.db.QueryRow(ctx, getPlacementByID, id)
	var i GetPlacementByIDRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.AgreementID,
		&i.ClientCompanyID,
		&i.SiteID,
		&i.ServiceLineID,
		&i.PositionID,
		&i.StartDate,
		&i.EndDate,
		&i.AnnualLeaveEntitlementDays,
		&i.BaseSalaryRefIdr,
		&i.Notes,
		&i.LifecycleStatus,
		&i.StatusChangedAt,
		&i.EndedReason,
		&i.EndedAt,
		&i.TerminationReason,
		&i.ResignAt,
		&i.PredecessorID,
		&i.SuccessorID,
		&i.BackdateReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmployeeName,
		&i.ClientCompanyName,
		&i.SiteName,
		&i.ServiceLineName,
		&i.PositionName,
		&i.AgreementType,
	)
	return i, err
}

const getPlacementChain = `-- name: GetPlacementChain :many
WITH RECURSIVE chain AS (
    SELECT p0.id, p0.predecessor_id, p0.successor_id
    FROM placements p0
    WHERE p0.id = $1
  UNION
    SELECT p1.id, p1.predecessor_id, p1.successor_id
    FROM placements p1
    JOIN chain ch ON p1.id = ch.predecessor_id OR p1.id = ch.successor_id
)
SELECT p.id, p.employee_id, p.agreement_id, p.client_company_id, p.site_id,
       p.service_line_id, p.position_id, p.start_date, p.end_date,
       p.annual_leave_entitlement_days, p.base_salary_ref_idr, p.notes,
       p.lifecycle_status, p.status_changed_at, p.ended_reason, p.ended_at,
       p.termination_reason, p.resign_at, p.predecessor_id, p.successor_id,
       p.backdate_reason, p.created_by, p.created_at, p.updated_at,
       e.full_name      AS employee_name,
       c.name           AS client_company_name,
       s.name           AS site_name,
       sl.name          AS service_line_name,
       pos.name         AS position_name,
       a.type           AS agreement_type
FROM placements p
JOIN chain ch                     ON ch.id  = p.id
LEFT JOIN employees e             ON e.id   = p.employee_id
LEFT JOIN client_companies c      ON c.id   = p.client_company_id
LEFT JOIN client_sites s          ON s.id   = p.site_id
LEFT JOIN service_lines sl        ON sl.id  = p.service_line_id
LEFT JOIN positions pos           ON pos.id = p.position_id
LEFT JOIN employment_agreements a ON a.id   = p.agreement_id
ORDER BY p.start_date ASC, p.id ASC
`

type GetPlacementChainRow struct {
	ID                         string
	EmployeeID                 string
	AgreementID                string
	ClientCompanyID            string
	SiteID                     string
	ServiceLineID              string
	PositionID                 string
	StartDate                  pgtype.Date
	EndDate                    pgtype.Date
	AnnualLeaveEntitlementDays *int32
	BaseSalaryRefIdr           *int64
	Notes                      *string
	LifecycleStatus            string
	StatusChangedAt            time.Time
	EndedReason                *string
	EndedAt                    pgtype.Date
	TerminationReason          *string
	ResignAt                   pgtype.Date
	PredecessorID              *string
	SuccessorID                *string
	BackdateReason             *string
	CreatedBy                  *string
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	EmployeeName               *string
	ClientCompanyName          *string
	SiteName                   *string
	ServiceLineName            *string
	PositionName               *string
	AgreementType              *string
}

// All placements sharing a predecessor/successor chain with the given placement
// (for history_chain). Walks both directions from the seed via a recursive CTE.
func (q *Queries) GetPlacementChain(ctx context.Context, id string) ([]GetPlacementChainRow, error) {
	rows, err := q.db.Query(ctx, getPlacementChain, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlacementChainRow{}
	for rows.Next() {
		var i GetPlacementChainRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.AgreementID,
			&i.ClientCompanyID,
			&i.SiteID,
			&i.ServiceLineID,
			&i.PositionID,
			&i.StartDate,
			&i.EndDate,
			&i.AnnualLeaveEntitlementDays,
			&i.BaseSalaryRefIdr,
			&i.Notes,
			&i.LifecycleStatus,
			&i.StatusChangedAt,
			&i.EndedReason,
			&i.EndedAt,
			&i.TerminationReason,
			&i.ResignAt,
			&i.PredecessorID,
			&i.SuccessorID,
			&i.BackdateReason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmployeeName,
			&i.ClientCompanyName,
			&i.SiteName,
			&i.ServiceLineName,
			&i.PositionName,
			&i.AgreementType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiringPlacements = `-- name: ListExpiringPlacements :many
SELECT p.id, p.employee_id, p.agreement_id, p.client_company_id, p.site_id,
       p.service_line_id, p.position_id, p.start_date, p.end_date,
       p.annual_leave_entitlement_days, p.base_salary_ref_idr, p.notes,
       p.lifecycle_status, p.status_changed_at, p.ended_reason, p.ended_at,
       p.termination_reason, p.resign_at, p.predecessor_id, p.successor_id,
       p.backdate_reason, p.created_by, p.created_at, p.updated_at,
       e.full_name      AS employee_name,
       c.name           AS client_company_name,
       s.name           AS site_name,
       sl.name          AS service_line_name,
       pos.name         AS position_name,
       a.type           AS agreement_type
FROM placements p
LEFT JOIN employees e             ON e.id   = p.employee_id
LEFT JOIN client_companies c      ON c.id   = p.client_company_id
LEFT JOIN client_sites s          ON s.id   = p.site_id
LEFT JOIN service_lines sl        ON sl.id  = p.service_line_id
LEFT JOIN positions pos           ON pos.id = p.position_id
LEFT JOIN employment_agreements a ON a.id   = p.agreement_id
WHERE p.deleted_at IS NULL
  AND p.lifecycle_status IN ('ACTIVE','EXPIRING')
  AND p.end_date IS NOT NULL
  AND p.end_date <= $1::date
  AND ($2::text IS NULL OR p.client_company_id = $2::text)
  AND (
        $3::date IS NULL
        OR (p.end_date, p.id) > ($3::date, $4::text)
      )
ORDER BY p.end_date ASC, p.id ASC
LIMIT $5
`

type ListExpiringPlacementsParams struct {
	Cutoff        pgtype.Date
	CompanyID     *string
	CursorEndDate pgtype.Date
	CursorID      *string
	RowLimit      int32
}

type ListExpiringPlacementsRow struct {
	ID                         string
	EmployeeID                 string
	AgreementID                string
	ClientCompanyID            string
	SiteID                     string
	ServiceLineID              string
	PositionID                 string
	StartDate                  pgtype.Date
	EndDate                    pgtype.Date
	AnnualLeaveEntitlementDays *int32
	BaseSalaryRefIdr           *int64
	Notes                      *string
	LifecycleStatus            string
	StatusChangedAt            time.Time
	EndedReason                *string
	EndedAt                    pgtype.Date
	TerminationReason          *string
	ResignAt                   pgtype.Date
	PredecessorID              *string
	SuccessorID                *string
	BackdateReason             *string
	CreatedBy                  *string
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	EmployeeName               *string
	ClientCompanyName          *string
	SiteName                   *string
	ServiceLineName            *string
	PositionName               *string
	AgreementType              *string
}

// Backs GET /placements/expiring. Keyset on (end_date asc, id asc).
// @cutoff = today(Asia/Jakarta) + within_days (computed in the service).
func (q *Queries) ListExpiringPlacements(ctx context.Context, arg ListExpiringPlacementsParams) ([]ListExpiringPlacementsRow, error) {
	rows, err := q.db.Query(ctx, listExpiringPlacements,
		arg.Cutoff,
		arg.CompanyID,
		arg.CursorEndDate,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiringPlacementsRow{}
	for rows.Next() {
		var i ListExpiringPlacementsRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.AgreementID,
			&i.ClientCompanyID,
			&i.SiteID,
			&i.ServiceLineID,
			&i.PositionID,
			&i.StartDate,
			&i.EndDate,
			&i.AnnualLeaveEntitlementDays,
			&i.BaseSalaryRefIdr,
			&i.Notes,
			&i.LifecycleStatus,
			&i.StatusChangedAt,
			&i.EndedReason,
			&i.EndedAt,
			&i.TerminationReason,
			&i.ResignAt,
			&i.PredecessorID,
			&i.SuccessorID,
			&i.BackdateReason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmployeeName,
			&i.ClientCompanyName,
			&i.SiteName,
			&i.ServiceLineName,
			&i.PositionName,
			&i.AgreementType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlacements = `-- name: ListPlacements :many

SELECT p.id, p.employee_id, p.agreement_id, p.client_company_id, p.site_id,
       p.service_line_id, p.position_id, p.start_date, p.end_date,
       p.annual_leave_entitlement_days, p.base_salary_ref_idr, p.notes,
       p.lifecycle_status, p.status_changed_at, p.ended_reason, p.ended_at,
       p.termination_reason, p.resign_at, p.predecessor_id, p.successor_id,
       p.backdate_reason, p.created_by, p.created_at, p.updated_at,
       e.full_name      AS employee_name,
       c.name           AS client_company_name,
       s.name           AS site_name,
       sl.name          AS service_line_name,
       pos.name         AS position_name,
       a.type           AS agreement_type
FROM placements p
LEFT JOIN employees e             ON e.id   = p.employee_id
LEFT JOIN client_companies c      ON c.id   = p.client_company_id
LEFT JOIN client_sites s          ON s.id   = p.site_id
LEFT JOIN service_lines sl        ON sl.id  = p.service_line_id
LEFT JOIN positions pos           ON pos.id = p.position_id
LEFT JOIN employment_agreements a ON a.id   = p.agreement_id
WHERE p.deleted_at IS NULL
  AND ($1::text      IS NULL OR p.client_company_id = $1::text)
  AND ($2::text IS NULL OR p.service_line_id   = $2::text)
  AND ($3::text     IS NULL OR p.employee_id       = $3::text)
  AND ($4::text    IS NULL OR p.agreement_id      = $4::text)
  AND ($5::text          IS NULL OR p.lifecycle_status  = $5::text)
  AND ($6::text[]     IS NULL OR p.lifecycle_status  = ANY($6::text[]))
  AND ($7::date   IS NULL OR (p.end_date IS NOT NULL AND p.end_date <= $7::date))
  AND (
        $8::boolean
        OR p.lifecycle_status NOT IN ('ENDED','TRANSFERRED','TERMINATED','RESIGNED','SUPERSEDED')
      )
  AND (
        $9::text IS NULL
        OR e.full_name   ILIKE '%' || $9::text || '%'
        OR p.employee_id ILIKE '%' || $9::text || '%'
        OR c.name        ILIKE '%' || $9::text || '%'
      )
  AND (
        $10::timestamptz IS NULL
        OR (p.status_changed_at, p.id) < ($10::timestamptz, $11::text)
      )
ORDER BY p.status_changed_at DESC, p.id DESC
LIMIT $12
`

type ListPlacementsParams struct {
	CompanyID             *string
	ServiceLineID         *string
	EmployeeID            *string
	AgreementID           *string
	Status                *string
	StatusIn              []string
	EndDateLte            pgtype.Date
	IncludeHistory        bool
	Q                     *string
	CursorStatusChangedAt *time.Time
	CursorID              *string
	RowLimit              int32
}

type ListPlacementsRow struct {
	ID                         string
	EmployeeID                 string
	AgreementID                string
	ClientCompanyID            string
	SiteID                     string
	ServiceLineID              string
	PositionID                 string
	StartDate                  pgtype.Date
	EndDate                    pgtype.Date
	AnnualLeaveEntitlementDays *int32
	BaseSalaryRefIdr           *int64
	Notes                      *string
	LifecycleStatus            string
	StatusChangedAt            time.Time
	EndedReason                *string
	EndedAt                    pgtype.Date
	TerminationReason          *string
	ResignAt                   pgtype.Date
	PredecessorID              *string
	SuccessorID                *string
	BackdateReason             *string
	CreatedBy                  *string
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	EmployeeName               *string
	ClientCompanyName          *string
	SiteName                   *string
	ServiceLineName            *string
	PositionName               *string
	AgreementType              *string
}

// E3 placement queries (F3.1/F3.2 / PLC-*). All reads LEFT JOIN the Phase-3/4
// master tables to fill the denormalized *_name fields the spec returns.
// Param→column note: the FE/spec params are `status` / `status__in`; both filter
// the `lifecycle_status` column. No param is literally named `lifecycle_status`.
// Cursor page ordered by (status_changed_at desc, id desc). Fetch limit+1 for has_more.
// Filters: company_id, service_line_id, employee_id, agreement_id,
//
//	status (single → lifecycle_status =), status__in (CSV → lifecycle_status = ANY),
//	q (ILIKE over agent name / employee_id / company name),
//	end_date__lte (expiring cutoff), include_history (exclude terminal states unless true).
func (q *Queries) ListPlacements(ctx context.Context, arg ListPlacementsParams) ([]ListPlacementsRow, error) {
	rows, err := q.db.Query(ctx, listPlacements,
		arg.CompanyID,
		arg.ServiceLineID,
		arg.EmployeeID,
		arg.AgreementID,
		arg.Status,
		arg.StatusIn,
		arg.EndDateLte,
		arg.IncludeHistory,
		arg.Q,
		arg.CursorStatusChangedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlacementsRow{}
	for rows.Next() {
		var i ListPlacementsRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.AgreementID,
			&i.ClientCompanyID,
			&i.SiteID,
			&i.ServiceLineID,
			&i.PositionID,
			&i.StartDate,
			&i.EndDate,
			&i.AnnualLeaveEntitlementDays,
			&i.BaseSalaryRefIdr,
			&i.Notes,
			&i.LifecycleStatus,
			&i.StatusChangedAt,
			&i.EndedReason,
			&i.EndedAt,
			&i.TerminationReason,
			&i.ResignAt,
			&i.PredecessorID,
			&i.SuccessorID,
			&i.BackdateReason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmployeeName,
			&i.ClientCompanyName,
			&i.SiteName,
			&i.ServiceLineName,
			&i.PositionName,
			&i.AgreementType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEmployeePlacements = `-- name: LockEmployeePlacements :many
SELECT p.id, p.employee_id, p.agreement_id, p.client_company_id, p.site_id,
       p.service_line_id, p.position_id, p.start_date, p.end_date,
       p.annual_leave_entitlement_days, p.base_salary_ref_idr, p.notes,
       p.lifecycle_status, p.status_changed_at, p.ended_reason, p.ended_at,
       p.termination_reason, p.resign_at, p.predecessor_id, p.successor_id,
       p.backdate_reason, p.created_by, p.created_at, p.updated_at
FROM placements p
WHERE p.employee_id = $1
  AND p.deleted_at IS NULL
FOR UPDATE
`

type LockEmployeePlacementsRow struct {
	ID                         string
	EmployeeID                 string
	AgreementID                string
	ClientCompanyID            string
	SiteID                     string
	ServiceLineID              string
	PositionID                 string
	StartDate                  pgtype.Date
	EndDate                    pgtype.Date
	AnnualLeaveEntitlementDays *int32
	BaseSalaryRefIdr           *int64
	Notes                      *string
	LifecycleStatus            string
	StatusChangedAt            time.Time
	EndedReason                *string
	EndedAt                    pgtype.Date
	TerminationReason          *string
	ResignAt                   pgtype.Date
	PredecessorID              *string
	SuccessorID                *string
	BackdateReason             *string
	CreatedBy                  *string
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
}

// INV-1 / period-overlap lock: all of the agent's placements, row-locked.
func (q *Queries) LockEmployeePlacements(ctx context.Context, employeeID string) ([]LockEmployeePlacementsRow, error) {
	rows, err := q.db.Query(ctx, lockEmployeePlacements, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockEmployeePlacementsRow{}
	for rows.Next() {
		var i LockEmployeePlacementsRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.AgreementID,
			&i.ClientCompanyID,
			&i.SiteID,
			&i.ServiceLineID,
			&i.PositionID,
			&i.StartDate,
			&i.EndDate,
			&i.AnnualLeaveEntitlementDays,
			&i.BaseSalaryRefIdr,
			&i.Notes,
			&i.LifecycleStatus,
			&i.StatusChangedAt,
			&i.EndedReason,
			&i.EndedAt,
			&i.TerminationReason,
			&i.ResignAt,
			&i.PredecessorID,
			&i.SuccessorID,
			&i.BackdateReason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rosterForCompany = `-- name: RosterForCompany :many
SELECT p.id, p.employee_id, p.agreement_id, p.client_company_id, p.site_id,
       p.service_line_id, p.position_id, p.start_date, p.end_date,
       p.annual_leave_entitlement_days, p.base_salary_ref_idr, p.notes,
       p.lifecycle_status, p.status_changed_at, p.ended_reason, p.ended_at,
       p.termination_reason, p.resign_at, p.predecessor_id, p.successor_id,
       p.backdate_reason, p.created_by, p.created_at, p.updated_at,
       e.full_name      AS employee_name,
       c.name           AS client_company_name,
       s.name           AS site_name,
       sl.name          AS service_line_name,
       pos.name         AS position_name,
       a.type           AS agreement_type
FROM placements p
LEFT JOIN employees e             ON e.id   = p.employee_id
LEFT JOIN client_companies c      ON c.id   = p.client_company_id
LEFT JOIN client_sites s          ON s.id   = p.site_id
LEFT JOIN service_lines sl        ON sl.id  = p.service_line_id
LEFT JOIN positions pos           ON pos.id = p.position_id
LEFT JOIN employment_agreements a ON a.id   = p.agreement_id
WHERE p.client_company_id = $1
  AND p.deleted_at IS NULL
  AND ($2::text IS NULL OR p.service_line_id  = $2::text)
  AND ($3::text          IS NULL OR p.lifecycle_status = $3::text)
  AND ($4::text[]     IS NULL OR p.lifecycle_status = ANY($4::text[]))
  AND (
        $5::boolean
        OR p.lifecycle_status NOT IN ('ENDED','TRANSFERRED','TERMINATED','RESIGNED','SUPERSEDED')
      )
  AND (
        $6::timestamptz IS NULL
        OR (p.status_changed_at, p.id) < ($6::timestamptz, $7::text)
      )
ORDER BY p.status_changed_at DESC, p.id DESC
LIMIT $8
`

type RosterForCompanyParams struct {
	ClientCompanyID       string
	ServiceLineID         *string
	Status                *string
	StatusIn              []string
	IncludeHistory        bool
	CursorStatusChangedAt *time.Time
	CursorID              *string
	RowLimit              int32
}

type RosterForCompanyRow struct {
	ID                         string
	EmployeeID                 string
	AgreementID                string
	ClientCompanyID            string
	SiteID                     string
	ServiceLineID              string
	PositionID                 string
	StartDate                  pgtype.Date
	EndDate                    pgtype.Date
	AnnualLeaveEntitlementDays *int32
	BaseSalaryRefIdr           *int64
	Notes                      *string
	LifecycleStatus            string
	StatusChangedAt            time.Time
	EndedReason                *string
	EndedAt                    pgtype.Date
	TerminationReason          *string
	ResignAt                   pgtype.Date
	PredecessorID              *string
	SuccessorID                *string
	BackdateReason             *string
	CreatedBy                  *string
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	EmployeeName               *string
	ClientCompanyName          *string
	SiteName                   *string
	ServiceLineName            *string
	PositionName               *string
	AgreementType              *string
}

// Company roster (RO-*). Filters: status (single), status__in (CSV),
// service_line_id, include_history. Keyset on (status_changed_at desc, id desc).
func (q *Queries) RosterForCompany(ctx context.Context, arg RosterForCompanyParams) ([]RosterForCompanyRow, error) {
	rows, err := q.db.Query(ctx, rosterForCompany,
		arg.ClientCompanyID,
		arg.ServiceLineID,
		arg.Status,
		arg.StatusIn,
		arg.IncludeHistory,
		arg.CursorStatusChangedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RosterForCompanyRow{}
	for rows.Next() {
		var i RosterForCompanyRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.AgreementID,
			&i.ClientCompanyID,
			&i.SiteID,
			&i.ServiceLineID,
			&i.PositionID,
			&i.StartDate,
			&i.EndDate,
			&i.AnnualLeaveEntitlementDays,
			&i.BaseSalaryRefIdr,
			&i.Notes,
			&i.LifecycleStatus,
			&i.StatusChangedAt,
			&i.EndedReason,
			&i.EndedAt,
			&i.TerminationReason,
			&i.ResignAt,
			&i.PredecessorID,
			&i.SuccessorID,
			&i.BackdateReason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmployeeName,
			&i.ClientCompanyName,
			&i.SiteName,
			&i.ServiceLineName,
			&i.PositionName,
			&i.AgreementType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rosterSummaryByServiceLine = `-- name: RosterSummaryByServiceLine :many
SELECT p.service_line_id AS service_line_id,
       sl.name           AS service_line_name,
       COUNT(*)          AS count
FROM placements p
LEFT JOIN service_lines sl ON sl.id = p.service_line_id
WHERE p.client_company_id = $1
  AND p.deleted_at IS NULL
  AND p.lifecycle_status IN ('ACTIVE','EXPIRING','PENDING_START')
GROUP BY p.service_line_id, sl.name
`

type RosterSummaryByServiceLineRow struct {
	ServiceLineID   string
	ServiceLineName *string
	Count           int64
}

// CompanyRosterSummary by_service_line counts (active placements only).
func (q *Queries) RosterSummaryByServiceLine(ctx context.Context, clientCompanyID string) ([]RosterSummaryByServiceLineRow, error) {
	rows, err := q.db.Query(ctx, rosterSummaryByServiceLine, clientCompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RosterSummaryByServiceLineRow{}
	for rows.Next() {
		var i RosterSummaryByServiceLineRow
		if err := rows.Scan(&i.ServiceLineID, &i.ServiceLineName, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rosterSummaryByStatus = `-- name: RosterSummaryByStatus :many
SELECT p.lifecycle_status AS status, COUNT(*) AS count
FROM placements p
WHERE p.client_company_id = $1
  AND p.deleted_at IS NULL
GROUP BY p.lifecycle_status
`

type RosterSummaryByStatusRow struct {
	Status string
	Count  int64
}

// CompanyRosterSummary by_status counts (non-deleted; non-terminal unless caller filters).
func (q *Queries) RosterSummaryByStatus(ctx context.Context, clientCompanyID string) ([]RosterSummaryByStatusRow, error) {
	rows, err := q.db.Query(ctx, rosterSummaryByStatus, clientCompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RosterSummaryByStatusRow{}
	for rows.Next() {
		var i RosterSummaryByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPlacementLifecycle = `-- name: SetPlacementLifecycle :one
UPDATE placements
SET lifecycle_status   = $1,
    status_changed_at  = now(),
    ended_reason       = $2,
    ended_at           = $3,
    termination_reason = $4,
    resign_at          = $5,
    successor_id       = $6,
    updated_at         = now()
WHERE id = $7
RETURNING id, employee_id, agreement_id, client_company_id, site_id,
          service_line_id, position_id, start_date, end_date,
          annual_leave_entitlement_days, base_salary_ref_idr, notes,
          lifecycle_status, status_changed_at, ended_reason, ended_at,
          termination_reason, resign_at, predecessor_id, successor_id,
          backdate_reason, created_by, created_at, updated_at
`

type SetPlacementLifecycleParams struct {
	LifecycleStatus   string
	EndedReason       *string
	EndedAt           pgtype.Date
	TerminationReason *string
	ResignAt          pgtype.Date
	SuccessorID       *string
	ID                string
}

type SetPlacementLifecycleRow struct {
	ID                         string
	EmployeeID                 string
	AgreementID                string
	ClientCompanyID            string
	SiteID                     string
	ServiceLineID              string
	PositionID                 string
	StartDate                  pgtype.Date
	EndDate                    pgtype.Date
	AnnualLeaveEntitlementDays *int32
	BaseSalaryRefIdr           *int64
	Notes                      *string
	LifecycleStatus            string
	StatusChangedAt            time.Time
	EndedReason                *string
	EndedAt                    pgtype.Date
	TerminationReason          *string
	ResignAt                   pgtype.Date
	PredecessorID              *string
	SuccessorID                *string
	BackdateReason             *string
	CreatedBy                  *string
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
}

// Drives end/terminate/resign/transfer/supersede. status_changed_at=now().
func (q *Queries) SetPlacementLifecycle(ctx context.Context, arg SetPlacementLifecycleParams) (SetPlacementLifecycleRow, error) {
	row := q.db.QueryRow(ctx, setPlacementLifecycle,
		arg.LifecycleStatus,
		arg.EndedReason,
		arg.EndedAt,
		arg.TerminationReason,
		arg.ResignAt,
		arg.SuccessorID,
		arg.ID,
	)
	var i SetPlacementLifecycleRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.AgreementID,
		&i.ClientCompanyID,
		&i.SiteID,
		&i.ServiceLineID,
		&i.PositionID,
		&i.StartDate,
		&i.EndDate,
		&i.AnnualLeaveEntitlementDays,
		&i.BaseSalaryRefIdr,
		&i.Notes,
		&i.LifecycleStatus,
		&i.StatusChangedAt,
		&i.EndedReason,
		&i.EndedAt,
		&i.TerminationReason,
		&i.ResignAt,
		&i.PredecessorID,
		&i.SuccessorID,
		&i.BackdateReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setPlacementPredecessor = `-- name: SetPlacementPredecessor :exec
UPDATE placements SET predecessor_id = $1, updated_at = now()
WHERE id = $2
`

type SetPlacementPredecessorParams struct {
	PredecessorID *string
	ID            string
}

func (q *Queries) SetPlacementPredecessor(ctx context.Context, arg SetPlacementPredecessorParams) error {
	_, err := q.db.Exec(ctx, setPlacementPredecessor, arg.PredecessorID, arg.ID)
	return err
}

const setPlacementSuccessor = `-- name: SetPlacementSuccessor :exec
UPDATE placements SET successor_id = $1, updated_at = now()
WHERE id = $2
`

type SetPlacementSuccessorParams struct {
	SuccessorID *string
	ID          string
}

func (q *Queries) SetPlacementSuccessor(ctx context.Context, arg SetPlacementSuccessorParams) error {
	_, err := q.db.Exec(ctx, setPlacementSuccessor, arg.SuccessorID, arg.ID)
	return err
}

const updatePlacementFields = `-- name: UpdatePlacementFields :one
UPDATE placements
SET position_id                   = $1,
    end_date                      = $2,
    annual_leave_entitlement_days = $3,
    base_salary_ref_idr           = $4,
    notes                         = $5,
    updated_at                    = now()
WHERE id = $6
RETURNING id, employee_id, agreement_id, client_company_id, site_id,
          service_line_id, position_id, start_date, end_date,
          annual_leave_entitlement_days, base_salary_ref_idr, notes,
          lifecycle_status, status_changed_at, ended_reason, ended_at,
          termination_reason, resign_at, predecessor_id, successor_id,
          backdate_reason, created_by, created_at, updated_at
`

type UpdatePlacementFieldsParams struct {
	PositionID                 string
	EndDate                    pgtype.Date
	AnnualLeaveEntitlementDays *int32
	BaseSalaryRefIdr           *int64
	Notes                      *string
	ID                         string
}

type UpdatePlacementFieldsRow struct {
	ID                         string
	EmployeeID                 string
	AgreementID                string
	ClientCompanyID            string
	SiteID                     string
	ServiceLineID              string
	PositionID                 string
	StartDate                  pgtype.Date
	EndDate                    pgtype.Date
	AnnualLeaveEntitlementDays *int32
	BaseSalaryRefIdr           *int64
	Notes                      *string
	LifecycleStatus            string
	StatusChangedAt            time.Time
	EndedReason                *string
	EndedAt                    pgtype.Date
	TerminationReason          *string
	ResignAt                   pgtype.Date
	PredecessorID              *string
	SuccessorID                *string
	BackdateReason             *string
	CreatedBy                  *string
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
}

// Limited-field PATCH (position_id, end_date, entitlement, salary ref, notes).
func (q *Queries) UpdatePlacementFields(ctx context.Context, arg UpdatePlacementFieldsParams) (UpdatePlacementFieldsRow, error) {
	row := q.db.QueryRow(ctx, updatePlacementFields,
		arg.PositionID,
		arg.EndDate,
		arg.AnnualLeaveEntitlementDays,
		arg.BaseSalaryRefIdr,
		arg.Notes,
		arg.ID,
	)
	var i UpdatePlacementFieldsRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.AgreementID,
		&i.ClientCompanyID,
		&i.SiteID,
		&i.ServiceLineID,
		&i.PositionID,
		&i.StartDate,
		&i.EndDate,
		&i.AnnualLeaveEntitlementDays,
		&i.BaseSalaryRefIdr,
		&i.Notes,
		&i.LifecycleStatus,
		&i.StatusChangedAt,
		&i.EndedReason,
		&i.EndedAt,
		&i.TerminationReason,
		&i.ResignAt,
		&i.PredecessorID,
		&i.SuccessorID,
		&i.BackdateReason,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
