// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_settings.sql

package sqlcgen

import (
	"context"
)

const listPlatformSettings = `-- name: ListPlatformSettings :many
SELECT key, value, label, locked FROM platform_settings ORDER BY sort ASC
`

type ListPlatformSettingsRow struct {
	Key    string
	Value  string
	Label  string
	Locked bool
}

func (q *Queries) ListPlatformSettings(ctx context.Context) ([]ListPlatformSettingsRow, error) {
	rows, err := q.db.Query(ctx, listPlatformSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlatformSettingsRow{}
	for rows.Next() {
		var i ListPlatformSettingsRow
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.Label,
			&i.Locked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
