// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: positions.sql

package sqlcgen

import (
	"context"
	"time"
)

const createPosition = `-- name: CreatePosition :one
INSERT INTO positions (id, service_line_id, name, alias)
VALUES (
    'SWP-POS-' || swp_next_id('POS'),
    $1,
    $2,
    $3
)
RETURNING id, service_line_id, name, alias, status, created_at, updated_at
`

type CreatePositionParams struct {
	ServiceLineID string
	Name          string
	Alias         string
}

type CreatePositionRow struct {
	ID            string
	ServiceLineID string
	Name          string
	Alias         string
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// Allocates the SWP-POS id inline from the per-prefix sequence.
func (q *Queries) CreatePosition(ctx context.Context, arg CreatePositionParams) (CreatePositionRow, error) {
	row := q.db.QueryRow(ctx, createPosition, arg.ServiceLineID, arg.Name, arg.Alias)
	var i CreatePositionRow
	err := row.Scan(
		&i.ID,
		&i.ServiceLineID,
		&i.Name,
		&i.Alias,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPositionByID = `-- name: GetPositionByID :one
SELECT id, service_line_id, name, alias, status, created_at, updated_at
FROM positions
WHERE id = $1
  AND deleted_at IS NULL
`

type GetPositionByIDRow struct {
	ID            string
	ServiceLineID string
	Name          string
	Alias         string
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) GetPositionByID(ctx context.Context, id string) (GetPositionByIDRow, error) {
	row := q.db.QueryRow(ctx, getPositionByID, id)
	var i GetPositionByIDRow
	err := row.Scan(
		&i.ID,
		&i.ServiceLineID,
		&i.Name,
		&i.Alias,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPositionsForLine = `-- name: ListPositionsForLine :many
SELECT id, service_line_id, name, alias, status, created_at, updated_at
FROM positions
WHERE service_line_id = $1
  AND deleted_at IS NULL
  AND ($2::text IS NULL OR status = $2::text)
  AND (
        $3::timestamptz IS NULL
        OR (created_at, id) < ($3::timestamptz, $4::text)
      )
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListPositionsForLineParams struct {
	ServiceLineID   string
	Status          *string
	CursorCreatedAt *time.Time
	CursorID        *string
	RowLimit        int32
}

type ListPositionsForLineRow struct {
	ID            string
	ServiceLineID string
	Name          string
	Alias         string
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// Cursor page ordered by (created_at desc, id desc), scoped to one service line.
func (q *Queries) ListPositionsForLine(ctx context.Context, arg ListPositionsForLineParams) ([]ListPositionsForLineRow, error) {
	rows, err := q.db.Query(ctx, listPositionsForLine,
		arg.ServiceLineID,
		arg.Status,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPositionsForLineRow{}
	for rows.Next() {
		var i ListPositionsForLineRow
		if err := rows.Scan(
			&i.ID,
			&i.ServiceLineID,
			&i.Name,
			&i.Alias,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPositionStatus = `-- name: SetPositionStatus :one
UPDATE positions
SET status     = $1,
    updated_at = now()
WHERE id = $2
  AND deleted_at IS NULL
RETURNING id, service_line_id, name, alias, status, created_at, updated_at
`

type SetPositionStatusParams struct {
	Status string
	ID     string
}

type SetPositionStatusRow struct {
	ID            string
	ServiceLineID string
	Name          string
	Alias         string
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// Drives soft-delete-like deactivation (status='inactive') or reactivation.
func (q *Queries) SetPositionStatus(ctx context.Context, arg SetPositionStatusParams) (SetPositionStatusRow, error) {
	row := q.db.QueryRow(ctx, setPositionStatus, arg.Status, arg.ID)
	var i SetPositionStatusRow
	err := row.Scan(
		&i.ID,
		&i.ServiceLineID,
		&i.Name,
		&i.Alias,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeletePosition = `-- name: SoftDeletePosition :exec
UPDATE positions
SET deleted_at = now(),
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

// Hard soft-delete: sets deleted_at so the position is invisible to all queries.
func (q *Queries) SoftDeletePosition(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, softDeletePosition, id)
	return err
}

const updatePosition = `-- name: UpdatePosition :one
UPDATE positions
SET name       = $1,
    alias      = $2,
    updated_at = now()
WHERE id = $3
  AND deleted_at IS NULL
RETURNING id, service_line_id, name, alias, status, created_at, updated_at
`

type UpdatePositionParams struct {
	Name  string
	Alias string
	ID    string
}

type UpdatePositionRow struct {
	ID            string
	ServiceLineID string
	Name          string
	Alias         string
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) UpdatePosition(ctx context.Context, arg UpdatePositionParams) (UpdatePositionRow, error) {
	row := q.db.QueryRow(ctx, updatePosition, arg.Name, arg.Alias, arg.ID)
	var i UpdatePositionRow
	err := row.Scan(
		&i.ID,
		&i.ServiceLineID,
		&i.Name,
		&i.Alias,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
