// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: positions_search.sql

package sqlcgen

import (
	"context"
)

const searchPositions = `-- name: SearchPositions :many

SELECT DISTINCT position
FROM placements
WHERE position ILIKE $1::text
  AND position <> ''
ORDER BY position
LIMIT 30
`

// Position typeahead query (E2 GET /positions:search, backed by E3 placements).
// Position is FREE-TEXT (no master, no FK, no ID) — the typeahead just surfaces
// the DISTINCT existing labels already recorded across placements so admins can
// reuse a consistent string or type a new one (decision 2026-06-12).
// Distinct existing free-text position labels matching the (case-insensitive)
// substring. The handler passes '%' || q || '%' so an empty q matches everything.
func (q *Queries) SearchPositions(ctx context.Context, q_ string) ([]string, error) {
	rows, err := q.db.Query(ctx, searchPositions, q_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var position string
		if err := rows.Scan(&position); err != nil {
			return nil, err
		}
		items = append(items, position)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
