// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reconcile.sql

package sqlcgen

import (
	"context"
	"time"
)

const findReconcileCandidate = `-- name: FindReconcileCandidate :one

SELECT a.id, a.check_in_at, a.flags, a.status, a.verification_status, a.is_payable,
       a.verified_by, a.rejected_by
FROM attendance a
WHERE a.employee_id = $1
  AND a.placement_id = $2
  AND a.schedule_id IS NULL
  AND a.deleted_at IS NULL
  AND 'UNSCHEDULED' = ANY(a.flags)
  AND a.check_in_at IS NOT NULL
  AND a.check_in_at >= $3::timestamptz
  AND a.check_in_at <= $4::timestamptz
ORDER BY a.check_in_at
LIMIT 1
FOR UPDATE
`

type FindReconcileCandidateParams struct {
	EmployeeID  string
	PlacementID string
	WindowStart time.Time
	WindowEnd   time.Time
}

type FindReconcileCandidateRow struct {
	ID                 string
	CheckInAt          *time.Time
	Flags              []string
	Status             string
	VerificationStatus string
	IsPayable          *bool
	VerifiedBy         *string
	RejectedBy         *string
}

// E5 attendance auto-reconcile queries (F5.7 / AR-1..AR-10). When a workable shift
// is created (scheduling.CreateEntry), an existing machine-owned UNSCHEDULED
// attendance record the shift covers is adopted: linked to the new schedule_id, its
// shift window snapshotted, and (for machine-owned rows) its lateness / status /
// flags / verification / payability re-derived with the same clock-in rules. The
// window [shift_start-2h, shift_end+4h] is computed in Go (Asia/Jakarta wall-clock,
// mirroring clock.sql GetTodayScheduleForEmployee) and passed as timestamptz bounds.
// `make gen` writes internal/repository/sqlc (NEVER hand-edit).
// The UNSCHEDULED attendance row a new shift adopts (AR-3 window). Match: same
// employee_id + placement_id, schedule_id IS NULL, not deleted, UNSCHEDULED in
// flags, and check_in_at within [window_start, window_end]; earliest check_in_at
// wins (AR-3 — earliest if several, no out-of-window fallback). The machine-owned
// vs human-decided split (AR-2 vs AR-9) is classified in Go from the returned
// verification_status / verified_by / rejected_by: a machine-owned row is
// re-derived (ReconcileAttendance); a human-decided one gets lineage-only
// (RelinkAttendanceLineage). FOR UPDATE row-locks the adoptee so a mid-review SL is
// serialized (C-AR-7).
func (q *Queries) FindReconcileCandidate(ctx context.Context, arg FindReconcileCandidateParams) (FindReconcileCandidateRow, error) {
	row := q.db.QueryRow(ctx, findReconcileCandidate,
		arg.EmployeeID,
		arg.PlacementID,
		arg.WindowStart,
		arg.WindowEnd,
	)
	var i FindReconcileCandidateRow
	err := row.Scan(
		&i.ID,
		&i.CheckInAt,
		&i.Flags,
		&i.Status,
		&i.VerificationStatus,
		&i.IsPayable,
		&i.VerifiedBy,
		&i.RejectedBy,
	)
	return i, err
}

const reconcileAttendance = `-- name: ReconcileAttendance :one
UPDATE attendance
SET schedule_id         = $1,
    shift_start_at      = $2,
    shift_end_at        = $3,
    status              = $4,
    is_late             = $5,
    late_minutes        = $6,
    flags               = $7::text[],
    verification_status = $8,
    is_payable          = COALESCE(is_payable, $9::boolean),
    updated_at          = now()
WHERE id = $10
  AND schedule_id IS NULL
  AND deleted_at IS NULL
RETURNING id
`

type ReconcileAttendanceParams struct {
	ScheduleID         *string
	ShiftStartAt       *time.Time
	ShiftEndAt         *time.Time
	Status             string
	IsLate             bool
	LateMinutes        int32
	Flags              []string
	VerificationStatus string
	IsPayable          *bool
	ID                 string
}

// Adopt a machine-owned UNSCHEDULED record (AR-5/6/7/8): link schedule_id + shift
// snapshot and write the Go-re-derived status / is_late / late_minutes / flags /
// verification_status / is_payable. flags is the caller-computed array (UNSCHEDULED
// removed, LATE added when derived; OUTSIDE_GEOFENCE / AUTO_CLOSED preserved).
// is_payable is COALESCE'd so an explicit true/false is never overridden, only a
// NULL is promoted to true (AR-8). Count-guarded by schedule_id IS NULL (AR-4) so a
// concurrent link cannot double-apply — zero rows ⇒ already linked (repo no-op).
func (q *Queries) ReconcileAttendance(ctx context.Context, arg ReconcileAttendanceParams) (string, error) {
	row := q.db.QueryRow(ctx, reconcileAttendance,
		arg.ScheduleID,
		arg.ShiftStartAt,
		arg.ShiftEndAt,
		arg.Status,
		arg.IsLate,
		arg.LateMinutes,
		arg.Flags,
		arg.VerificationStatus,
		arg.IsPayable,
		arg.ID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const relinkAttendanceLineage = `-- name: RelinkAttendanceLineage :one
UPDATE attendance
SET schedule_id    = $1,
    shift_start_at = $2,
    shift_end_at   = $3,
    updated_at     = now()
WHERE id = $4
  AND schedule_id IS NULL
  AND deleted_at IS NULL
RETURNING id
`

type RelinkAttendanceLineageParams struct {
	ScheduleID   *string
	ShiftStartAt *time.Time
	ShiftEndAt   *time.Time
	ID           string
}

// Lineage-only adoption of a HUMAN-decided record (AR-9): a record already
// VERIFIED/REJECTED/ESCALATED is NOT re-derived — its status / verification_status /
// flags / is_payable are the human's authoritative decision and stay untouched. Only
// the schedule_id + shift snapshot are attached so payroll/reporting tie the record
// to its shift. Count-guarded by schedule_id IS NULL (AR-4).
func (q *Queries) RelinkAttendanceLineage(ctx context.Context, arg RelinkAttendanceLineageParams) (string, error) {
	row := q.db.QueryRow(ctx, relinkAttendanceLineage,
		arg.ScheduleID,
		arg.ShiftStartAt,
		arg.ShiftEndAt,
		arg.ID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
