// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedule_entries.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelScheduleEntriesForLeave = `-- name: CancelScheduleEntriesForLeave :many
UPDATE schedule_entries
SET status = 'CANCELLED_BY_LEAVE', updated_at = now()
WHERE employee_id = $1
  AND work_date BETWEEN $2::date AND $3::date
  AND status <> 'CANCELLED_BY_LEAVE'
  AND deleted_at IS NULL
RETURNING id, work_date, status
`

type CancelScheduleEntriesForLeaveParams struct {
	EmployeeID string
	StartDate  pgtype.Date
	EndDate    pgtype.Date
}

type CancelScheduleEntriesForLeaveRow struct {
	ID       string
	WorkDate pgtype.Date
	Status   string
}

// INV-3 loop-closer (E6 / Phase 8): cancel overlapping live schedule entries for
// the leave dates on final/override approval. status='CANCELLED_BY_LEAVE' is the
// ONLY value the schedule_entries CHECK (migration 00024) permits for this
// transition — NEVER write 'LEAVE' to the column ('LEAVE' is the DTO boundary
// value the service maps to). The `status <> 'CANCELLED_BY_LEAVE'` guard makes the
// cancel idempotent across re-runs. RETURNING drives schedule_impact[] (id + date +
// the new DB status; the service maps DB 'CANCELLED_BY_LEAVE' → DTO new_status='LEAVE').
func (q *Queries) CancelScheduleEntriesForLeave(ctx context.Context, arg CancelScheduleEntriesForLeaveParams) ([]CancelScheduleEntriesForLeaveRow, error) {
	rows, err := q.db.Query(ctx, cancelScheduleEntriesForLeave, arg.EmployeeID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CancelScheduleEntriesForLeaveRow{}
	for rows.Next() {
		var i CancelScheduleEntriesForLeaveRow
		if err := rows.Scan(&i.ID, &i.WorkDate, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createScheduleEntry = `-- name: CreateScheduleEntry :one
INSERT INTO schedule_entries (
    employee_id, placement_id, service_line_id, shift_master_id,
    start_time, end_time, cross_midnight, work_date, status,
    is_day_off, replaced_entry_id, created_by
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
RETURNING id, employee_id, placement_id, service_line_id, shift_master_id,
          start_time, end_time, cross_midnight, work_date, status,
          is_day_off, replaced_entry_id, created_by, created_at, updated_at
`

type CreateScheduleEntryParams struct {
	EmployeeID      string
	PlacementID     string
	ServiceLineID   *string
	ShiftMasterID   *string
	StartTime       *string
	EndTime         *string
	CrossMidnight   bool
	WorkDate        pgtype.Date
	Status          string
	IsDayOff        bool
	ReplacedEntryID *string
	CreatedBy       *string
}

type CreateScheduleEntryRow struct {
	ID              string
	EmployeeID      string
	PlacementID     string
	ServiceLineID   *string
	ShiftMasterID   *string
	StartTime       *string
	EndTime         *string
	CrossMidnight   bool
	WorkDate        pgtype.Date
	Status          string
	IsDayOff        bool
	ReplacedEntryID *string
	CreatedBy       *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

// id allocated by the column DEFAULT ('SWP-SCH-' || swp_next_id('SCH')).
func (q *Queries) CreateScheduleEntry(ctx context.Context, arg CreateScheduleEntryParams) (CreateScheduleEntryRow, error) {
	row := q.db.QueryRow(ctx, createScheduleEntry,
		arg.EmployeeID,
		arg.PlacementID,
		arg.ServiceLineID,
		arg.ShiftMasterID,
		arg.StartTime,
		arg.EndTime,
		arg.CrossMidnight,
		arg.WorkDate,
		arg.Status,
		arg.IsDayOff,
		arg.ReplacedEntryID,
		arg.CreatedBy,
	)
	var i CreateScheduleEntryRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.PlacementID,
		&i.ServiceLineID,
		&i.ShiftMasterID,
		&i.StartTime,
		&i.EndTime,
		&i.CrossMidnight,
		&i.WorkDate,
		&i.Status,
		&i.IsDayOff,
		&i.ReplacedEntryID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findActivePlacementForAgentDate = `-- name: FindActivePlacementForAgentDate :one
SELECT p.id, p.client_company_id, p.service_line_id, p.site_id,
       p.start_date, p.end_date, p.lifecycle_status
FROM placements p
WHERE p.employee_id = $1
  AND p.lifecycle_status IN ('ACTIVE','EXPIRING')
  AND p.start_date <= $2::date
  AND (p.end_date IS NULL OR p.end_date >= $2::date)
  AND p.deleted_at IS NULL
LIMIT 1
`

type FindActivePlacementForAgentDateParams struct {
	EmployeeID string
	WorkDate   pgtype.Date
}

type FindActivePlacementForAgentDateRow struct {
	ID              string
	ClientCompanyID string
	ServiceLineID   string
	SiteID          string
	StartDate       pgtype.Date
	EndDate         pgtype.Date
	LifecycleStatus string
}

// INV-2 / OUTSIDE_PLACEMENT_PERIOD source: the agent's ACTIVE/EXPIRING placement
// whose period covers work_date (open-ended end_date treated as +inf).
func (q *Queries) FindActivePlacementForAgentDate(ctx context.Context, arg FindActivePlacementForAgentDateParams) (FindActivePlacementForAgentDateRow, error) {
	row := q.db.QueryRow(ctx, findActivePlacementForAgentDate, arg.EmployeeID, arg.WorkDate)
	var i FindActivePlacementForAgentDateRow
	err := row.Scan(
		&i.ID,
		&i.ClientCompanyID,
		&i.ServiceLineID,
		&i.SiteID,
		&i.StartDate,
		&i.EndDate,
		&i.LifecycleStatus,
	)
	return i, err
}

const findLiveEntryForAgentDate = `-- name: FindLiveEntryForAgentDate :one
SELECT se.id, se.shift_master_id, se.status, se.is_day_off
FROM schedule_entries se
WHERE se.employee_id = $1
  AND se.work_date = $2
  AND se.deleted_at IS NULL
`

type FindLiveEntryForAgentDateParams struct {
	EmployeeID string
	WorkDate   pgtype.Date
}

type FindLiveEntryForAgentDateRow struct {
	ID            string
	ShiftMasterID *string
	Status        string
	IsDayOff      bool
}

// DOUBLE_SHIFT pre-check / replace lookup: the live entry (if any) for an
// agent on a date. Mirrors the INV-1 partial unique index predicate.
func (q *Queries) FindLiveEntryForAgentDate(ctx context.Context, arg FindLiveEntryForAgentDateParams) (FindLiveEntryForAgentDateRow, error) {
	row := q.db.QueryRow(ctx, findLiveEntryForAgentDate, arg.EmployeeID, arg.WorkDate)
	var i FindLiveEntryForAgentDateRow
	err := row.Scan(
		&i.ID,
		&i.ShiftMasterID,
		&i.Status,
		&i.IsDayOff,
	)
	return i, err
}

const getScheduleEntry = `-- name: GetScheduleEntry :one
SELECT se.id, se.employee_id, se.placement_id, se.service_line_id,
       se.shift_master_id, se.start_time, se.end_time, se.cross_midnight,
       se.work_date, se.status, se.is_day_off, se.replaced_entry_id,
       se.created_by, se.created_at, se.updated_at,
       e.full_name AS employee_name,
       p.client_company_id AS company_id,
       c.name AS company_name,
       sm.name AS shift_master_name
FROM schedule_entries se
JOIN placements p             ON p.id  = se.placement_id
LEFT JOIN client_companies c  ON c.id  = p.client_company_id
LEFT JOIN employees e         ON e.id  = se.employee_id
LEFT JOIN shift_masters sm    ON sm.id = se.shift_master_id
WHERE se.id = $1
  AND se.deleted_at IS NULL
`

type GetScheduleEntryRow struct {
	ID              string
	EmployeeID      string
	PlacementID     string
	ServiceLineID   *string
	ShiftMasterID   *string
	StartTime       *string
	EndTime         *string
	CrossMidnight   bool
	WorkDate        pgtype.Date
	Status          string
	IsDayOff        bool
	ReplacedEntryID *string
	CreatedBy       *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	EmployeeName    *string
	CompanyID       string
	CompanyName     *string
	ShiftMasterName *string
}

// Single entry with denormalized names + company_id (from placement).
func (q *Queries) GetScheduleEntry(ctx context.Context, id string) (GetScheduleEntryRow, error) {
	row := q.db.QueryRow(ctx, getScheduleEntry, id)
	var i GetScheduleEntryRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.PlacementID,
		&i.ServiceLineID,
		&i.ShiftMasterID,
		&i.StartTime,
		&i.EndTime,
		&i.CrossMidnight,
		&i.WorkDate,
		&i.Status,
		&i.IsDayOff,
		&i.ReplacedEntryID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmployeeName,
		&i.CompanyID,
		&i.CompanyName,
		&i.ShiftMasterName,
	)
	return i, err
}

const getScheduleEntryForUpdate = `-- name: GetScheduleEntryForUpdate :one
SELECT se.id, se.employee_id, se.placement_id, se.service_line_id,
       se.shift_master_id, se.start_time, se.end_time, se.cross_midnight,
       se.work_date, se.status, se.is_day_off, se.replaced_entry_id,
       se.created_by, se.created_at, se.updated_at
FROM schedule_entries se
WHERE se.id = $1
  AND se.deleted_at IS NULL
FOR UPDATE
`

type GetScheduleEntryForUpdateRow struct {
	ID              string
	EmployeeID      string
	PlacementID     string
	ServiceLineID   *string
	ShiftMasterID   *string
	StartTime       *string
	EndTime         *string
	CrossMidnight   bool
	WorkDate        pgtype.Date
	Status          string
	IsDayOff        bool
	ReplacedEntryID *string
	CreatedBy       *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

// Row-lock for PATCH / soft-delete (omits joins; service re-reads for DTO).
func (q *Queries) GetScheduleEntryForUpdate(ctx context.Context, id string) (GetScheduleEntryForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getScheduleEntryForUpdate, id)
	var i GetScheduleEntryForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.PlacementID,
		&i.ServiceLineID,
		&i.ShiftMasterID,
		&i.StartTime,
		&i.EndTime,
		&i.CrossMidnight,
		&i.WorkDate,
		&i.Status,
		&i.IsDayOff,
		&i.ReplacedEntryID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSchedule = `-- name: ListSchedule :many

SELECT se.id, se.employee_id, se.placement_id, se.service_line_id,
       se.shift_master_id, se.start_time, se.end_time, se.cross_midnight,
       se.work_date, se.status, se.is_day_off, se.replaced_entry_id,
       se.created_by, se.created_at, se.updated_at,
       e.full_name AS employee_name,
       p.client_company_id AS company_id,
       c.name AS company_name,
       sm.name AS shift_master_name
FROM schedule_entries se
JOIN placements p             ON p.id  = se.placement_id
LEFT JOIN client_companies c  ON c.id  = p.client_company_id
LEFT JOIN employees e         ON e.id  = se.employee_id
LEFT JOIN shift_masters sm    ON sm.id = se.shift_master_id
WHERE se.deleted_at IS NULL
  AND p.client_company_id = $1
  AND se.work_date BETWEEN $2::date AND $3::date
  AND ($4::text IS NULL OR se.employee_id = $4::text)
  AND ($5::text[] IS NULL OR se.status = ANY($5::text[]))
ORDER BY se.employee_id ASC, se.work_date ASC, se.id ASC
`

type ListScheduleParams struct {
	CompanyID  string
	StartDate  pgtype.Date
	EndDate    pgtype.Date
	EmployeeID *string
	StatusIn   []string
}

type ListScheduleRow struct {
	ID              string
	EmployeeID      string
	PlacementID     string
	ServiceLineID   *string
	ShiftMasterID   *string
	StartTime       *string
	EndTime         *string
	CrossMidnight   bool
	WorkDate        pgtype.Date
	Status          string
	IsDayOff        bool
	ReplacedEntryID *string
	CreatedBy       *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	EmployeeName    *string
	CompanyID       string
	CompanyName     *string
	ShiftMasterName *string
}

// E4 schedule-entry queries (F4.2/F4.3 / SWP-SCH-*). Reads LEFT JOIN employees for
// employee_name, shift_masters for shift_master_name, and JOIN placements →
// client_companies for company_id/company_name. Times are text columns (HH:MM).
// Grid load for a company over a date range. Joins placement → company.
// Filters: company_id (via placement), work_date BETWEEN start/end,
//
//	employee_id (optional), status__in (optional text[] → status = ANY).
//
// Ordered by employee_id, work_date for a stable grid layout.
func (q *Queries) ListSchedule(ctx context.Context, arg ListScheduleParams) ([]ListScheduleRow, error) {
	rows, err := q.db.Query(ctx, listSchedule,
		arg.CompanyID,
		arg.StartDate,
		arg.EndDate,
		arg.EmployeeID,
		arg.StatusIn,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScheduleRow{}
	for rows.Next() {
		var i ListScheduleRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.PlacementID,
			&i.ServiceLineID,
			&i.ShiftMasterID,
			&i.StartTime,
			&i.EndTime,
			&i.CrossMidnight,
			&i.WorkDate,
			&i.Status,
			&i.IsDayOff,
			&i.ReplacedEntryID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmployeeName,
			&i.CompanyID,
			&i.CompanyName,
			&i.ShiftMasterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleByAgent = `-- name: ListScheduleByAgent :many
SELECT se.id, se.employee_id, se.placement_id, se.service_line_id,
       se.shift_master_id, se.start_time, se.end_time, se.cross_midnight,
       se.work_date, se.status, se.is_day_off, se.replaced_entry_id,
       se.created_by, se.created_at, se.updated_at,
       e.full_name AS employee_name,
       p.client_company_id AS company_id,
       c.name AS company_name,
       sm.name AS shift_master_name
FROM schedule_entries se
JOIN placements p             ON p.id  = se.placement_id
LEFT JOIN client_companies c  ON c.id  = p.client_company_id
LEFT JOIN employees e         ON e.id  = se.employee_id
LEFT JOIN shift_masters sm    ON sm.id = se.shift_master_id
WHERE se.deleted_at IS NULL
  AND se.employee_id = $1
  AND se.work_date BETWEEN $2::date AND $3::date
ORDER BY se.work_date ASC, se.start_time ASC, se.id ASC
`

type ListScheduleByAgentParams struct {
	EmployeeID string
	StartDate  pgtype.Date
	EndDate    pgtype.Date
}

type ListScheduleByAgentRow struct {
	ID              string
	EmployeeID      string
	PlacementID     string
	ServiceLineID   *string
	ShiftMasterID   *string
	StartTime       *string
	EndTime         *string
	CrossMidnight   bool
	WorkDate        pgtype.Date
	Status          string
	IsDayOff        bool
	ReplacedEntryID *string
	CreatedBy       *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	EmployeeName    *string
	CompanyID       string
	CompanyName     *string
	ShiftMasterName *string
}

// F4.3 "Jadwal Saya": ONE agent's schedule across ALL their placements (no
// company_id filter — by-agent spans companies). Same projected columns as
// ListSchedule so the row reuses the list mapper. Ordered by work_date,
// start_time for the agent's day/week timeline.
// TODO(SV-3): include_company geo/address enrichment (company_geo/address) is
//
//	deferred — this query returns the base ScheduleEntry projection only.
func (q *Queries) ListScheduleByAgent(ctx context.Context, arg ListScheduleByAgentParams) ([]ListScheduleByAgentRow, error) {
	rows, err := q.db.Query(ctx, listScheduleByAgent, arg.EmployeeID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScheduleByAgentRow{}
	for rows.Next() {
		var i ListScheduleByAgentRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.PlacementID,
			&i.ServiceLineID,
			&i.ShiftMasterID,
			&i.StartTime,
			&i.EndTime,
			&i.CrossMidnight,
			&i.WorkDate,
			&i.Status,
			&i.IsDayOff,
			&i.ReplacedEntryID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmployeeName,
			&i.CompanyID,
			&i.CompanyName,
			&i.ShiftMasterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteScheduleEntry = `-- name: SoftDeleteScheduleEntry :execrows
UPDATE schedule_entries
SET deleted_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteScheduleEntry(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteScheduleEntry, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateScheduleEntry = `-- name: UpdateScheduleEntry :one
UPDATE schedule_entries
SET shift_master_id   = $1,
    service_line_id   = $2,
    start_time        = $3,
    end_time          = $4,
    cross_midnight    = $5,
    status            = $6,
    is_day_off        = $7,
    replaced_entry_id = $8,
    updated_at        = now()
WHERE id = $9
  AND deleted_at IS NULL
RETURNING id, employee_id, placement_id, service_line_id, shift_master_id,
          start_time, end_time, cross_midnight, work_date, status,
          is_day_off, replaced_entry_id, created_by, created_at, updated_at
`

type UpdateScheduleEntryParams struct {
	ShiftMasterID   *string
	ServiceLineID   *string
	StartTime       *string
	EndTime         *string
	CrossMidnight   bool
	Status          string
	IsDayOff        bool
	ReplacedEntryID *string
	ID              string
}

type UpdateScheduleEntryRow struct {
	ID              string
	EmployeeID      string
	PlacementID     string
	ServiceLineID   *string
	ShiftMasterID   *string
	StartTime       *string
	EndTime         *string
	CrossMidnight   bool
	WorkDate        pgtype.Date
	Status          string
	IsDayOff        bool
	ReplacedEntryID *string
	CreatedBy       *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) UpdateScheduleEntry(ctx context.Context, arg UpdateScheduleEntryParams) (UpdateScheduleEntryRow, error) {
	row := q.db.QueryRow(ctx, updateScheduleEntry,
		arg.ShiftMasterID,
		arg.ServiceLineID,
		arg.StartTime,
		arg.EndTime,
		arg.CrossMidnight,
		arg.Status,
		arg.IsDayOff,
		arg.ReplacedEntryID,
		arg.ID,
	)
	var i UpdateScheduleEntryRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.PlacementID,
		&i.ServiceLineID,
		&i.ShiftMasterID,
		&i.StartTime,
		&i.EndTime,
		&i.CrossMidnight,
		&i.WorkDate,
		&i.Status,
		&i.IsDayOff,
		&i.ReplacedEntryID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
