// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedule_propagation.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const listPropagationCandidates = `-- name: ListPropagationCandidates :many

SELECT se.id,
       se.work_date,
       se.start_time,
       se.end_time,
       se.cross_midnight,
       a.check_in_at  AS att_check_in_at,
       a.check_out_at AS att_check_out_at
FROM schedule_entries se
LEFT JOIN attendance a
       ON a.schedule_id = se.id
      AND a.deleted_at IS NULL
WHERE se.shift_master_id = $1
  AND se.deleted_at IS NULL
  AND se.is_day_off = false
  AND se.status <> 'CANCELLED_BY_LEAVE'
  AND se.work_date >= ($2::timestamptz AT TIME ZONE 'Asia/Jakarta')::date
ORDER BY se.id
`

type ListPropagationCandidatesParams struct {
	ShiftMasterID *string
	Now           time.Time
}

type ListPropagationCandidatesRow struct {
	ID            string
	WorkDate      pgtype.Date
	StartTime     *string
	EndTime       *string
	CrossMidnight bool
	AttCheckInAt  *time.Time
	AttCheckOutAt *time.Time
}

// E4 shift-time propagation (F4.1 SM-2 ripple → F4.2 entries, with E5 attendance
// freezing). When a shift master's start_time/end_time/cross_midnight change, the
// snapshot times on its FUTURE schedule_entries are re-synced — UNLESS an
// attendance row has already frozen the entry (checked-in freezes the start;
// checked-out freezes everything). The per-row decision + cross_midnight + the
// Asia/Jakarta shift_end_at timestamptz math live in Go (schedule_propagation.go)
// for clarity/testability; these queries are the row-fetch + the two focused
// writes. Times are text columns (HH:MM, Asia/Jakarta wall-clock).
// The FUTURE, live, non-day-off, non-cancelled entries linked to a master, with
// their attendance check-in/out instants LEFT-JOINed (≤1 attendance per entry via
// the attendance_schedule_uq partial unique index). "future" = work_date >= the
// current Asia/Jakarta calendar date (passed as `now` and reduced to a date here,
// mirroring clock.sql). The Go layer inspects check_in_at/check_out_at to pick the
// freeze branch per row.
func (q *Queries) ListPropagationCandidates(ctx context.Context, arg ListPropagationCandidatesParams) ([]ListPropagationCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listPropagationCandidates, arg.ShiftMasterID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPropagationCandidatesRow{}
	for rows.Next() {
		var i ListPropagationCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkDate,
			&i.StartTime,
			&i.EndTime,
			&i.CrossMidnight,
			&i.AttCheckInAt,
			&i.AttCheckOutAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncOpenAttendanceShiftEnd = `-- name: SyncOpenAttendanceShiftEnd :execrows
UPDATE attendance
SET shift_end_at = $1,
    updated_at   = now()
WHERE schedule_id = $2
  AND check_out_at IS NULL
  AND deleted_at IS NULL
`

type SyncOpenAttendanceShiftEndParams struct {
	ShiftEndAt *time.Time
	ScheduleID *string
}

// DELIBERATE CROSS-EPIC WRITE (E4 → E5): when a master's end_time moves and an
// agent is mid-shift (checked in, NOT yet out), the entry keeps its frozen start
// but its end is re-synced; the OPEN attendance row's shift_end_at must follow so
// the auto-close / overtime windows stay correct. Guarded by check_out_at IS NULL
// (only open rows) + deleted_at IS NULL. shift_start_at is intentionally NOT
// touched (the start is frozen at clock-in). Computed shift_end_at (work_date +
// new end, +1 day when cross) is passed in from Go.
func (q *Queries) SyncOpenAttendanceShiftEnd(ctx context.Context, arg SyncOpenAttendanceShiftEndParams) (int64, error) {
	result, err := q.db.Exec(ctx, syncOpenAttendanceShiftEnd, arg.ShiftEndAt, arg.ScheduleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateScheduleEntryTimes = `-- name: UpdateScheduleEntryTimes :execrows
UPDATE schedule_entries
SET start_time     = $1,
    end_time       = $2,
    cross_midnight = $3,
    updated_at     = now()
WHERE id = $4
  AND deleted_at IS NULL
`

type UpdateScheduleEntryTimesParams struct {
	StartTime     *string
	EndTime       *string
	CrossMidnight bool
	ID            string
}

// Focused update of just the three snapshot time columns (start/end/cross), used
// by the propagation loop. Status / is_day_off / shift_master_id are untouched —
// this is a re-sync of the window only, not a reschedule.
func (q *Queries) UpdateScheduleEntryTimes(ctx context.Context, arg UpdateScheduleEntryTimesParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateScheduleEntryTimes,
		arg.StartTime,
		arg.EndTime,
		arg.CrossMidnight,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
