// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: service_lines.sql

package sqlcgen

import (
	"context"
	"time"
)

const countActivePositionsForLine = `-- name: CountActivePositionsForLine :one
SELECT count(*)
FROM positions
WHERE service_line_id = $1
  AND status = 'active'
  AND deleted_at IS NULL
`

// Used to populate position_count in the ServiceLine DTO and to guard :discontinue.
func (q *Queries) CountActivePositionsForLine(ctx context.Context, serviceLineID string) (int64, error) {
	row := q.db.QueryRow(ctx, countActivePositionsForLine, serviceLineID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createServiceLine = `-- name: CreateServiceLine :one
INSERT INTO service_lines (id, name)
VALUES (
    'SWP-SVC-' || swp_next_id('SVC'),
    $1
)
RETURNING id, name, status, created_at, updated_at
`

type CreateServiceLineRow struct {
	ID        string
	Name      string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

// Allocates the SWP-SVC id inline from the per-prefix sequence.
func (q *Queries) CreateServiceLine(ctx context.Context, name string) (CreateServiceLineRow, error) {
	row := q.db.QueryRow(ctx, createServiceLine, name)
	var i CreateServiceLineRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceLineByID = `-- name: GetServiceLineByID :one
SELECT id, name, status, created_at, updated_at
FROM service_lines
WHERE id = $1
  AND deleted_at IS NULL
`

type GetServiceLineByIDRow struct {
	ID        string
	Name      string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetServiceLineByID(ctx context.Context, id string) (GetServiceLineByIDRow, error) {
	row := q.db.QueryRow(ctx, getServiceLineByID, id)
	var i GetServiceLineByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listServiceLines = `-- name: ListServiceLines :many
SELECT id, name, status, created_at, updated_at
FROM service_lines
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR status = $1::text)
  AND (
        $2::timestamptz IS NULL
        OR (created_at, id) < ($2::timestamptz, $3::text)
      )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListServiceLinesParams struct {
	Status          *string
	CursorCreatedAt *time.Time
	CursorID        *string
	RowLimit        int32
}

type ListServiceLinesRow struct {
	ID        string
	Name      string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

// Cursor page ordered by (created_at desc, id desc). Fetch limit+1 for has_more.
func (q *Queries) ListServiceLines(ctx context.Context, arg ListServiceLinesParams) ([]ListServiceLinesRow, error) {
	rows, err := q.db.Query(ctx, listServiceLines,
		arg.Status,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServiceLinesRow{}
	for rows.Next() {
		var i ListServiceLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setServiceLineStatus = `-- name: SetServiceLineStatus :one
UPDATE service_lines
SET status     = $1,
    updated_at = now()
WHERE id = $2
  AND deleted_at IS NULL
RETURNING id, name, status, created_at, updated_at
`

type SetServiceLineStatusParams struct {
	Status string
	ID     string
}

type SetServiceLineStatusRow struct {
	ID        string
	Name      string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

// Drives :discontinue (status='inactive') and :reactivate (status='active').
func (q *Queries) SetServiceLineStatus(ctx context.Context, arg SetServiceLineStatusParams) (SetServiceLineStatusRow, error) {
	row := q.db.QueryRow(ctx, setServiceLineStatus, arg.Status, arg.ID)
	var i SetServiceLineStatusRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateServiceLine = `-- name: UpdateServiceLine :one
UPDATE service_lines
SET name       = $1,
    updated_at = now()
WHERE id = $2
  AND deleted_at IS NULL
RETURNING id, name, status, created_at, updated_at
`

type UpdateServiceLineParams struct {
	Name string
	ID   string
}

type UpdateServiceLineRow struct {
	ID        string
	Name      string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) UpdateServiceLine(ctx context.Context, arg UpdateServiceLineParams) (UpdateServiceLineRow, error) {
	row := q.db.QueryRow(ctx, updateServiceLine, arg.Name, arg.ID)
	var i UpdateServiceLineRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
