// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shift_masters.sql

package sqlcgen

import (
	"context"
	"time"
)

const createShiftMaster = `-- name: CreateShiftMaster :one
INSERT INTO shift_masters (
    name, start_time, end_time, break_start, break_end,
    cross_midnight, is_active, created_by
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, name, start_time, end_time, break_start, break_end,
          cross_midnight, is_active,
          created_by, created_at, updated_at
`

type CreateShiftMasterParams struct {
	Name          string
	StartTime     string
	EndTime       string
	BreakStart    *string
	BreakEnd      *string
	CrossMidnight bool
	IsActive      bool
	CreatedBy     *string
}

type CreateShiftMasterRow struct {
	ID            string
	Name          string
	StartTime     string
	EndTime       string
	BreakStart    *string
	BreakEnd      *string
	CrossMidnight bool
	IsActive      bool
	CreatedBy     *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// id allocated by the column DEFAULT ('SWP-SHF-' || swp_next_id('SHF')).
// cross_midnight is server-derived (end<=start) and passed in by the 06-02 service.
func (q *Queries) CreateShiftMaster(ctx context.Context, arg CreateShiftMasterParams) (CreateShiftMasterRow, error) {
	row := q.db.QueryRow(ctx, createShiftMaster,
		arg.Name,
		arg.StartTime,
		arg.EndTime,
		arg.BreakStart,
		arg.BreakEnd,
		arg.CrossMidnight,
		arg.IsActive,
		arg.CreatedBy,
	)
	var i CreateShiftMasterRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartTime,
		&i.EndTime,
		&i.BreakStart,
		&i.BreakEnd,
		&i.CrossMidnight,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShiftMaster = `-- name: GetShiftMaster :one
SELECT sm.id, sm.name, sm.start_time, sm.end_time, sm.break_start, sm.break_end,
       sm.cross_midnight, sm.is_active,
       sm.created_by, sm.created_at, sm.updated_at,
       (SELECT count(*) FROM schedule_entries se
         WHERE se.shift_master_id = sm.id AND se.deleted_at IS NULL) AS in_use_count
FROM shift_masters sm
WHERE sm.id = $1
  AND sm.deleted_at IS NULL
`

type GetShiftMasterRow struct {
	ID            string
	Name          string
	StartTime     string
	EndTime       string
	BreakStart    *string
	BreakEnd      *string
	CrossMidnight bool
	IsActive      bool
	CreatedBy     *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	InUseCount    int64
}

func (q *Queries) GetShiftMaster(ctx context.Context, id string) (GetShiftMasterRow, error) {
	row := q.db.QueryRow(ctx, getShiftMaster, id)
	var i GetShiftMasterRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartTime,
		&i.EndTime,
		&i.BreakStart,
		&i.BreakEnd,
		&i.CrossMidnight,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InUseCount,
	)
	return i, err
}

const getShiftMasterForUpdate = `-- name: GetShiftMasterForUpdate :one
SELECT sm.id, sm.name, sm.start_time, sm.end_time, sm.break_start, sm.break_end,
       sm.cross_midnight, sm.is_active,
       sm.created_by, sm.created_at, sm.updated_at
FROM shift_masters sm
WHERE sm.id = $1
  AND sm.deleted_at IS NULL
FOR UPDATE
`

type GetShiftMasterForUpdateRow struct {
	ID            string
	Name          string
	StartTime     string
	EndTime       string
	BreakStart    *string
	BreakEnd      *string
	CrossMidnight bool
	IsActive      bool
	CreatedBy     *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// Row-lock for the update / activate-toggle path (service re-reads for DTO).
func (q *Queries) GetShiftMasterForUpdate(ctx context.Context, id string) (GetShiftMasterForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getShiftMasterForUpdate, id)
	var i GetShiftMasterForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartTime,
		&i.EndTime,
		&i.BreakStart,
		&i.BreakEnd,
		&i.CrossMidnight,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listShiftMasters = `-- name: ListShiftMasters :many

SELECT sm.id, sm.name, sm.start_time, sm.end_time, sm.break_start, sm.break_end,
       sm.cross_midnight, sm.is_active,
       sm.created_by, sm.created_at, sm.updated_at,
       (SELECT count(*) FROM schedule_entries se
         WHERE se.shift_master_id = sm.id AND se.deleted_at IS NULL) AS in_use_count
FROM shift_masters sm
WHERE sm.deleted_at IS NULL
  AND ($1::boolean IS NULL OR sm.is_active = $1::boolean)
  AND ($2::text IS NULL OR sm.name ILIKE '%' || $2::text || '%')
  AND ($3::text IS NULL OR sm.id < $3::text)
ORDER BY sm.id DESC
LIMIT $4
`

type ListShiftMastersParams struct {
	IsActive *bool
	Q        *string
	CursorID *string
	RowLimit int32
}

type ListShiftMastersRow struct {
	ID            string
	Name          string
	StartTime     string
	EndTime       string
	BreakStart    *string
	BreakEnd      *string
	CrossMidnight bool
	IsActive      bool
	CreatedBy     *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	InUseCount    int64
}

// E4 shift-master queries (F4.1 / SM-* / SWP-SHF-*). Shift masters are fully
// INDEPENDENT (service_line removed entirely, 2026-06-12). in_use_count is a
// correlated subquery over live schedule_entries. Times are text columns
// (HH:MM, Asia/Jakarta).
// Cursor page ordered by id desc. Filters:
//
//	status (ACTIVE→is_active=true / INACTIVE→false) via the is_active narg,
//	q ILIKE over name. in_use_count = live schedule_entries referencing this master.
func (q *Queries) ListShiftMasters(ctx context.Context, arg ListShiftMastersParams) ([]ListShiftMastersRow, error) {
	rows, err := q.db.Query(ctx, listShiftMasters,
		arg.IsActive,
		arg.Q,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShiftMastersRow{}
	for rows.Next() {
		var i ListShiftMastersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartTime,
			&i.EndTime,
			&i.BreakStart,
			&i.BreakEnd,
			&i.CrossMidnight,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InUseCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setShiftMasterActive = `-- name: SetShiftMasterActive :one
UPDATE shift_masters
SET is_active  = $1,
    updated_at = now()
WHERE id = $2
  AND deleted_at IS NULL
RETURNING id, name, start_time, end_time, break_start, break_end,
          cross_midnight, is_active,
          created_by, created_at, updated_at
`

type SetShiftMasterActiveParams struct {
	IsActive bool
	ID       string
}

type SetShiftMasterActiveRow struct {
	ID            string
	Name          string
	StartTime     string
	EndTime       string
	BreakStart    *string
	BreakEnd      *string
	CrossMidnight bool
	IsActive      bool
	CreatedBy     *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// Drives :deactivate (active=false) / :reactivate (active=true).
func (q *Queries) SetShiftMasterActive(ctx context.Context, arg SetShiftMasterActiveParams) (SetShiftMasterActiveRow, error) {
	row := q.db.QueryRow(ctx, setShiftMasterActive, arg.IsActive, arg.ID)
	var i SetShiftMasterActiveRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartTime,
		&i.EndTime,
		&i.BreakStart,
		&i.BreakEnd,
		&i.CrossMidnight,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateShiftMaster = `-- name: UpdateShiftMaster :one
UPDATE shift_masters
SET name            = $1,
    start_time      = $2,
    end_time        = $3,
    break_start     = $4,
    break_end       = $5,
    cross_midnight  = $6,
    is_active       = $7,
    updated_at      = now()
WHERE id = $8
  AND deleted_at IS NULL
RETURNING id, name, start_time, end_time, break_start, break_end,
          cross_midnight, is_active,
          created_by, created_at, updated_at
`

type UpdateShiftMasterParams struct {
	Name          string
	StartTime     string
	EndTime       string
	BreakStart    *string
	BreakEnd      *string
	CrossMidnight bool
	IsActive      bool
	ID            string
}

type UpdateShiftMasterRow struct {
	ID            string
	Name          string
	StartTime     string
	EndTime       string
	BreakStart    *string
	BreakEnd      *string
	CrossMidnight bool
	IsActive      bool
	CreatedBy     *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// Full overwrite of the editable fields (06-02 builds the full param set from the
// current row + the PATCH overlay). cross_midnight re-derived by the service.
func (q *Queries) UpdateShiftMaster(ctx context.Context, arg UpdateShiftMasterParams) (UpdateShiftMasterRow, error) {
	row := q.db.QueryRow(ctx, updateShiftMaster,
		arg.Name,
		arg.StartTime,
		arg.EndTime,
		arg.BreakStart,
		arg.BreakEnd,
		arg.CrossMidnight,
		arg.IsActive,
		arg.ID,
	)
	var i UpdateShiftMasterRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartTime,
		&i.EndTime,
		&i.BreakStart,
		&i.BreakEnd,
		&i.CrossMidnight,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
