// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: templates.sql

package sqlcgen

import (
	"context"
)

const deleteApprovalLinesByTemplate = `-- name: DeleteApprovalLinesByTemplate :exec
DELETE FROM approval_lines
WHERE template_id = $1
`

// Clears a template's lines (members cascade) before re-inserting on edit.
func (q *Queries) DeleteApprovalLinesByTemplate(ctx context.Context, templateID string) error {
	_, err := q.db.Exec(ctx, deleteApprovalLinesByTemplate, templateID)
	return err
}

const deleteApprovalTemplate = `-- name: DeleteApprovalTemplate :exec
DELETE FROM approval_templates
WHERE id = $1
`

// Drops the template; lines + members cascade.
func (q *Queries) DeleteApprovalTemplate(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteApprovalTemplate, id)
	return err
}

const getApprovalTemplateByCompany = `-- name: GetApprovalTemplateByCompany :one

SELECT id, company_id, version, created_by, created_at, updated_at
FROM approval_templates
WHERE company_id = $1
`

// E11 approval-template queries (F11.1 / SWP-APT-*, SWP-APL-*). One template per
// company (INV-1). Lines are ordered 2..3 (INV-2); members are an OR-set per line.
// IDs allocated by the column DEFAULT ('SWP-APT-' / 'SWP-APL-' || swp_next_id(...)).
// The company's single template (INV-1). The service then loads lines + members.
func (q *Queries) GetApprovalTemplateByCompany(ctx context.Context, companyID string) (ApprovalTemplate, error) {
	row := q.db.QueryRow(ctx, getApprovalTemplateByCompany, companyID)
	var i ApprovalTemplate
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApprovalTemplateByID = `-- name: GetApprovalTemplateByID :one
SELECT id, company_id, version, created_by, created_at, updated_at
FROM approval_templates
WHERE id = $1
`

func (q *Queries) GetApprovalTemplateByID(ctx context.Context, id string) (ApprovalTemplate, error) {
	row := q.db.QueryRow(ctx, getApprovalTemplateByID, id)
	var i ApprovalTemplate
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertApprovalLine = `-- name: InsertApprovalLine :one
INSERT INTO approval_lines (template_id, line_no)
VALUES ($1, $2)
RETURNING id, template_id, line_no
`

type InsertApprovalLineParams struct {
	TemplateID string
	LineNo     int32
}

// One line of a template (line_no 1..3, unique within template). id from DEFAULT.
func (q *Queries) InsertApprovalLine(ctx context.Context, arg InsertApprovalLineParams) (ApprovalLine, error) {
	row := q.db.QueryRow(ctx, insertApprovalLine, arg.TemplateID, arg.LineNo)
	var i ApprovalLine
	err := row.Scan(&i.ID, &i.TemplateID, &i.LineNo)
	return i, err
}

const insertApprovalLineMember = `-- name: InsertApprovalLineMember :exec
INSERT INTO approval_line_members (line_id, user_id)
VALUES ($1, $2)
ON CONFLICT (line_id, user_id) DO NOTHING
`

type InsertApprovalLineMemberParams struct {
	LineID string
	UserID string
}

// Adds a user to a line's OR-set (composite PK line_id+user_id).
func (q *Queries) InsertApprovalLineMember(ctx context.Context, arg InsertApprovalLineMemberParams) error {
	_, err := q.db.Exec(ctx, insertApprovalLineMember, arg.LineID, arg.UserID)
	return err
}

const insertApprovalTemplate = `-- name: InsertApprovalTemplate :one
INSERT INTO approval_templates (company_id, created_by)
VALUES ($1, $2)
RETURNING id, company_id, version, created_by, created_at, updated_at
`

type InsertApprovalTemplateParams struct {
	CompanyID string
	CreatedBy *string
}

// Create a company's template (INV-1 unique company_id). id from column DEFAULT.
func (q *Queries) InsertApprovalTemplate(ctx context.Context, arg InsertApprovalTemplateParams) (ApprovalTemplate, error) {
	row := q.db.QueryRow(ctx, insertApprovalTemplate, arg.CompanyID, arg.CreatedBy)
	var i ApprovalTemplate
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApprovalLineMembersByTemplate = `-- name: ListApprovalLineMembersByTemplate :many
SELECT alm.line_id,
       al.line_no,
       alm.user_id,
       COALESCE(e.full_name, u.email) AS display_name,
       EXISTS (
           SELECT 1 FROM employment_agreements ea
           WHERE ea.employee_id = u.employee_id
             AND ea.status = 'active'
             AND ea.deleted_at IS NULL
       ) AS active
FROM approval_line_members alm
JOIN approval_lines al ON al.id = alm.line_id
LEFT JOIN users u      ON u.id  = alm.user_id
LEFT JOIN employees e  ON e.id  = u.employee_id
WHERE al.template_id = $1
ORDER BY al.line_no ASC, alm.user_id ASC
`

type ListApprovalLineMembersByTemplateRow struct {
	LineID      string
	LineNo      int32
	UserID      string
	DisplayName string
	Active      bool
}

// All members across a template's lines, joined to users + the linked employee for
// the LineMember readOnly fields: display_name (employee full_name) and active
// (an active employment_agreement exists, i.e. employment not ended — TM-3).
// Ordered by line_no then user_id for deterministic chain rendering.
func (q *Queries) ListApprovalLineMembersByTemplate(ctx context.Context, templateID string) ([]ListApprovalLineMembersByTemplateRow, error) {
	rows, err := q.db.Query(ctx, listApprovalLineMembersByTemplate, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApprovalLineMembersByTemplateRow{}
	for rows.Next() {
		var i ListApprovalLineMembersByTemplateRow
		if err := rows.Scan(
			&i.LineID,
			&i.LineNo,
			&i.UserID,
			&i.DisplayName,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApprovalLinesByTemplate = `-- name: ListApprovalLinesByTemplate :many
SELECT id, template_id, line_no
FROM approval_lines
WHERE template_id = $1
ORDER BY line_no ASC
`

// Ordered chain (line_no asc) for a template.
func (q *Queries) ListApprovalLinesByTemplate(ctx context.Context, templateID string) ([]ApprovalLine, error) {
	rows, err := q.db.Query(ctx, listApprovalLinesByTemplate, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApprovalLine{}
	for rows.Next() {
		var i ApprovalLine
		if err := rows.Scan(&i.ID, &i.TemplateID, &i.LineNo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApprovalTemplateVersion = `-- name: UpdateApprovalTemplateVersion :one
UPDATE approval_templates
SET version    = version + 1,
    updated_at = now()
WHERE id = $1
RETURNING id, company_id, version, created_by, created_at, updated_at
`

// Bump version on every edit (INV-6); the service then re-inserts lines/members and
// resets pending instances.
func (q *Queries) UpdateApprovalTemplateVersion(ctx context.Context, id string) (ApprovalTemplate, error) {
	row := q.db.QueryRow(ctx, updateApprovalTemplateVersion, id)
	var i ApprovalTemplate
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
