/**
 * Aggregated MSW handlers — generated by Orval from each spec's `*Example` payloads
 * (WEB-STACK §4). Each epic tag exposes a `get<Tag>Mock()` returning its handler array;
 * we flatten them so the app runs against the contract without the Go API.
 *
 * Add a line here when a new epic spec is wired in orval.config.ts.
 *
 * Action endpoints: CONVENTIONS models actions as `{id}:action` sub-resources, so Orval emits
 * MSW paths of the form "(prefix)/users/:userId:deactivate". The back-to-back ":param:action"
 * form is unparseable by MSW's matcher, so the `pnpm gen` post-gen step
 * (scripts/patch-msw-action-paths.mjs) rewrites those into anchored RegExp paths. With that fix
 * in place we include the full generated handler set (incl. the action mutations) via
 * `getUsersMock()`.
 */
import type { RequestHandler } from 'msw';
import { getAuditLogMock } from './gen/e1/audit-log/audit-log.msw.ts';
import { getAuthenticationMock } from './gen/e1/authentication/authentication.msw.ts';
import { getPlatformMock } from './gen/e1/platform/platform.msw.ts';
import { getUsersMock } from './gen/e1/users/users.msw.ts';
import { getAgreementsMock } from './gen/e2/agreements/agreements.msw.ts';
import { getChangeRequestsMock } from './gen/e2/change-requests/change-requests.msw.ts';
import { getClientCompaniesMock } from './gen/e2/client-companies/client-companies.msw.ts';
import { getEmployeesMock } from './gen/e2/employees/employees.msw.ts';
import { getMasterDataMock } from './gen/e2/master-data/master-data.msw.ts';
import { getServiceLinesPositionsMock } from './gen/e2/service-lines-positions/service-lines-positions.msw.ts';
import { getClientCompaniesMock as getE3RosterMock } from './gen/e3/client-companies/client-companies.msw.ts';
import { getPlacementsMock } from './gen/e3/placements/placements.msw.ts';
import { getShiftLeaderAssignmentsMock } from './gen/e3/shift-leader-assignments/shift-leader-assignments.msw.ts';
import { getScheduleMock } from './gen/e4/schedule/schedule.msw.ts';
import { getShiftMastersMock } from './gen/e4/shift-masters/shift-masters.msw.ts';
import { getAttendanceRecordsMock } from './gen/e5/attendance-records/attendance-records.msw.ts';
import { getAttendanceVerificationMock } from './gen/e5/attendance-verification/attendance-verification.msw.ts';
import { getClockInOutMock } from './gen/e5/clock-in-out/clock-in-out.msw.ts';
import { getCorrectionsMock as getE5CorrectionsMock } from './gen/e5/corrections/corrections.msw.ts';
import { getLeaveCalendarMock } from './gen/e6/leave-calendar/leave-calendar.msw.ts';
import { getLeaveQuotasMock } from './gen/e6/leave-quotas/leave-quotas.msw.ts';
import { getLeaveRequestsMock } from './gen/e6/leave-requests/leave-requests.msw.ts';

// E6 handlers omitted: mocks deferred for E6 (WEB-STACK §4 caveat). Add here once wired.
export const handlers: RequestHandler[] = [
  // E1 Foundations
  ...getAuthenticationMock(),
  ...getUsersMock(),
  ...getAuditLogMock(),
  ...getPlatformMock(),
  // E2 Identity / Karyawan & Master Data
  ...getEmployeesMock(),
  ...getChangeRequestsMock(),
  ...getAgreementsMock(),
  ...getClientCompaniesMock(),
  ...getServiceLinesPositionsMock(),
  ...getMasterDataMock(),
  // E3 Placement / Penempatan
  ...getPlacementsMock(),
  ...getShiftLeaderAssignmentsMock(),
  ...getE3RosterMock(),
  // E4 Shift Scheduling / Jadwal
  ...getShiftMastersMock(),
  ...getScheduleMock(),
  // E5 Attendance / Kehadiran
  ...getClockInOutMock(),
  ...getAttendanceRecordsMock(),
  ...getAttendanceVerificationMock(),
  ...getE5CorrectionsMock(),
  // E6 Leave / Cuti (leave-types served by E2 master-data; omitted here to avoid a path clash)
  ...getLeaveQuotasMock(),
  ...getLeaveRequestsMock(),
  ...getLeaveCalendarMock(),
];
